import React, { useMemo, useState, useCallback } from 'react'
import { Typography, Card, Space, Input, List, Tag, Radio, Alert, Button, message, Collapse } from 'antd'
import { CodeOutlined, SearchOutlined, CopyOutlined } from '@ant-design/icons'
import { useLanguage } from '../i18n/LanguageContext'

const { Title, Paragraph, Text } = Typography

const CATEGORIES = [
  'cli',
  'basics',
  'types',
  'control',
  'functions',
  'pointers',
  'strings',
  'stl',
  'algorithms',
  'oop',
  'modern',
  'concurrency',
  'files',
  'errors',
]

const CATEGORY_COLOR = {
  cli: 'geekblue',
  basics: 'blue',
  types: 'purple',
  control: 'cyan',
  functions: 'lime',
  pointers: 'magenta',
  strings: 'green',
  stl: 'volcano',
  algorithms: 'orange',
  oop: 'red',
  modern: 'gold',
  concurrency: 'cyan',
  files: 'blue',
  errors: 'red',
}

const labelOf = {
  cli: { pt: 'CLI & build', en: 'CLI & build' },
  basics: { pt: 'Básicos & sintaxe', en: 'Basics & syntax' },
  types: { pt: 'Tipos & conversão', en: 'Types & conversion' },
  control: { pt: 'Controle de fluxo', en: 'Control flow' },
  functions: { pt: 'Funções & lambdas', en: 'Functions & lambdas' },
  pointers: { pt: 'Ponteiros & memória', en: 'Pointers & memory' },
  strings: { pt: 'Strings', en: 'Strings' },
  stl: { pt: 'Containers STL', en: 'STL containers' },
  algorithms: { pt: 'Algoritmos STL', en: 'STL algorithms' },
  oop: { pt: 'Classes & OOP', en: 'Classes & OOP' },
  modern: { pt: 'C++ moderno', en: 'Modern C++' },
  concurrency: { pt: 'Concorrência & threads', en: 'Concurrency & threads' },
  files: { pt: 'I/O & arquivos', en: 'Files & I/O' },
  errors: { pt: 'Exceções & erros', en: 'Exceptions & errors' },
}

const COMMANDS = [
  // ─── CLI & build ─────────────────────────────────────────────────────────
  { cmd: 'g++ -std=c++20 -Wall -Wextra main.cpp -o app', cat: 'cli', pt: 'Compila um único arquivo (C++20, todos os warnings)', en: 'Compiles a single file (C++20, all warnings)' },
  { cmd: './app', cat: 'cli', pt: 'Roda o binário gerado', en: 'Runs the generated binary' },
  { cmd: 'g++ -O2 -O3 main.cpp -o app', cat: 'cli', pt: 'Otimiza para desempenho (-O2/-O3)', en: 'Optimizes for performance (-O2/-O3)' },
  { cmd: 'g++ -g main.cpp -o app', cat: 'cli', pt: 'Gera símbolos de debug (para gdb)', en: 'Generates debug symbols (for gdb)' },
  { cmd: 'gcc -x c++ main.cpp', cat: 'cli', pt: 'Compilar com gcc forçando C++ (g++ já faz isso)', en: 'Compiling with gcc by forcing C++ (g++ does this already)' },
  { cmd: 'g++ -c util.cpp', cat: 'cli', pt: 'Compila sem linkar — gera util.o', en: 'Compiles without linking — produces util.o' },
  { cmd: 'g++ main.o util.o -o app', cat: 'cli', pt: 'Liga os objetos em um executável', en: 'Links the objects into an executable' },
  { cmd: 'g++ -pthread main.cpp -o app', cat: 'cli', pt: 'Liga a lib pthread (obrigatório com std::thread)', en: 'Links the pthread lib (required with std::thread)' },
  { cmd: 'clang++ -std=c++20 main.cpp -o app', cat: 'cli', pt: 'Mesmo com o Clang (diagnósticos mais legíveis)', en: 'Same thing with Clang (friendlier diagnostics)' },
  { cmd: 'cmake -S . -B build && cmake --build build', cat: 'cli', pt: 'Configura e compila um projeto CMake', en: 'Configures and builds a CMake project' },
  { cmd: 'cmake_minimum_required(VERSION 3.20)\nproject(app)\nadd_executable(app main.cpp)\ntarget_compile_features(app PRIVATE cxx_std_20)', cat: 'cli', pt: 'CMakeLists.txt mínimo com C++20', en: 'Minimal CMakeLists.txt with C++20' },
  { cmd: 'make -j4', cat: 'cli', pt: 'Build paralelo com make (gerado pelo CMake)', en: 'Parallel build with make (generated by CMake)' },
  { cmd: 'pkg-config --cflags --libs openssl', cat: 'cli', pt: 'Flags de compilação/link de uma lib instalada', en: 'Compile/link flags of an installed library' },
  { cmd: 'ldd app', cat: 'cli', pt: 'Lista as bibliotecas dinâmicas que o binário precisa', en: 'Lists the shared libraries the binary needs' },
  { cmd: 'nm -C app | grep main', cat: 'cli', pt: 'Lista símbolos com nomes decodificados (demangled)', en: 'Lists symbols with demangled names' },
  { cmd: 'gdb ./app  (run, break, bt)', cat: 'cli', pt: 'Debugger — roda, breakpoint, backtrace', en: 'Debugger — run, break, backtrace' },
  { cmd: 'valgrind --leak-check=full ./app', cat: 'cli', pt: 'Detecta vazamentos de memória e acesso inválido', en: 'Detects memory leaks and invalid access' },
  { cmd: '#include <iostream>', cat: 'cli', pt: 'Diretiva de inclusão — importa a biblioteca', en: 'Include directive — imports the library' },

  // ─── Básicos & sintaxe ────────────────────────────────────────────────────
  { cmd: 'int main() { return 0; }', cat: 'basics', pt: 'Ponto de entrada — retorno 0 = sucesso', en: 'Entry point — return 0 means success' },
  { cmd: 'std::cout << "oi";', cat: 'basics', pt: 'Imprime texto no console', en: 'Prints text to the console' },
  { cmd: 'std::cout << x << "\\n";', cat: 'basics', pt: 'Imprime variável + quebra de linha', en: 'Prints a variable plus a newline' },
  { cmd: 'std::cin >> x;', cat: 'basics', pt: 'Lê um valor do console (separado por espaço)', en: 'Reads a value from stdin (space-separated)' },
  { cmd: 'std::cerr << "erro";', cat: 'basics', pt: 'Imprime no stderr (erros)', en: 'Prints to stderr (errors)' },
  { cmd: 'using namespace std;', cat: 'basics', pt: 'Evite em arquivos grandes — polui o namespace global', en: 'Avoid in large files — pollutes the global namespace' },
  { cmd: '// comentário  /* bloco */', cat: 'basics', pt: 'Comentário de linha e de bloco', en: 'Line and block comments' },
  { cmd: 'const int MAX = 10;', cat: 'basics', pt: 'Constante em tempo de compilação (melhor que #define)', en: 'Compile-time constant (prefer it to #define)' },
  { cmd: 'int x = 5;', cat: 'basics', pt: 'Declaração e inicialização', en: 'Declaration and initialization' },
  { cmd: 'bool ok = true;', cat: 'basics', pt: 'Booleano — true ou false', en: 'Boolean — true or false' },
  { cmd: 'char c = \'A\';', cat: 'basics', pt: 'Char usa aspas simples; string usa aspas duplas', en: 'Char uses single quotes; strings use double quotes' },
  { cmd: 'std::string s = "ola";', cat: 'basics', pt: 'String (requer #include <string>)', en: 'String (requires #include <string>)' },
  { cmd: 'nullptr', cat: 'basics', pt: 'Literal de ponteiro nulo (C++11) — substitui o NULL', en: 'Null pointer literal (C++11) — replaces NULL' },

  // ─── Tipos & conversão ────────────────────────────────────────────────────
  { cmd: 'int / long / short / char / bool / float / double', cat: 'types', pt: 'Tipos fundamentais — tamanho depende da plataforma', en: 'Fundamental types — size depends on the platform' },
  { cmd: 'unsigned int / unsigned long', cat: 'types', pt: 'Variantes sem sinal (só valores >= 0)', en: 'Unsigned variants (non-negative values only)' },
  { cmd: '#include <cstdint>\nint32_t / uint64_t / int8_t', cat: 'types', pt: 'Inteiros de tamanho fixo — portabilidade garantida', en: 'Fixed-size integers — guaranteed portability' },
  { cmd: 'sizeof(int)', cat: 'types', pt: 'Tamanho em bytes de um tipo/variável', en: 'Size in bytes of a type/variable' },
  { cmd: 'sizeof(arr) / sizeof(arr[0])', cat: 'types', pt: 'Número de elementos de um array em C', en: 'Number of elements of a C array' },
  { cmd: 'auto x = 3.14;', cat: 'types', pt: 'Inferência de tipo — compilador deduz double', en: 'Type inference — the compiler deduces double' },
  { cmd: 'static_cast<int>(d)', cat: 'types', pt: 'Cast seguro entre tipos relacionados — o mais usado', en: 'Safe cast between related types — the common one' },
  { cmd: 'reinterpret_cast<int*>(addr)', cat: 'types', pt: 'Cast cru entre ponteiros — use com muito cuidado', en: 'Raw pointer cast — use with great care' },
  { cmd: 'const_cast<char*>(s)', cat: 'types', pt: 'Remove/add const — sinal de design ruim, evite', en: 'Removes/adds const — smells, avoid it' },
  { cmd: 'std::stoi(s) / std::stod(s)', cat: 'types', pt: 'String para int/double (C++11)', en: 'String to int/double (C++11)' },
  { cmd: 'std::to_string(n)', cat: 'types', pt: 'Número para string', en: 'Number to string' },
  { cmd: '(int)d  /* cast estilo C */', cat: 'types', pt: 'Cast estilo C — menos seguro, prefira static_cast', en: 'C-style cast — less safe, prefer static_cast' },
  { cmd: 'long long / unsigned long long', cat: 'types', pt: 'Inteiros de 64 bits mais comuns', en: 'Common 64-bit integers' },

  // ─── Controle de fluxo ────────────────────────────────────────────────────
  { cmd: 'if (x > 0) { } else { }', cat: 'control', pt: 'Condicional clássico', en: 'Classic conditional' },
  { cmd: 'int v = (cond) ? a : b;', cat: 'control', pt: 'Ternário — condição inline', en: 'Ternary — inline condition' },
  { cmd: 'switch (x) { case 1: break; default: break; }', cat: 'control', pt: 'Seleção por valor (não esqueça o break)', en: 'Value selection (don\'t forget break)' },
  { cmd: 'for (int i = 0; i < 10; i++) { }', cat: 'control', pt: 'Loop com contador clássico', en: 'Classic counter loop' },
  { cmd: 'for (auto& v : vec) { }', cat: 'control', pt: 'Range-based for — itera sem índices (C++11)', en: 'Range-based for — iterates without indices (C++11)' },
  { cmd: 'while (x > 0) { }', cat: 'control', pt: 'Loop com condição no início', en: 'Loop with a head condition' },
  { cmd: 'do { } while (x > 0);', cat: 'control', pt: 'Loop que roda ao menos uma vez', en: 'Loop that runs at least once' },
  { cmd: 'break;  continue;', cat: 'control', pt: 'Sai do loop / pula para a próxima iteração', en: 'Exits the loop / skips to the next iteration' },
  { cmd: 'switch (x) { case 1: [[fallthrough]]; }', cat: 'control', pt: 'Fallthrough explícito — intencional e sinalizado', en: 'Explicit fallthrough — intentional and marked' },

  // ─── Funções & lambdas ────────────────────────────────────────────────────
  { cmd: 'int soma(int a, int b) { return a + b; }', cat: 'functions', pt: 'Função com retorno e parâmetros', en: 'Function with a return value and parameters' },
  { cmd: 'void log(const std::string& msg)', cat: 'functions', pt: 'Sem retorno, parâmetro por referência const (evita cópia)', en: 'No return, const-ref parameter (avoids a copy)' },
  { cmd: 'void f(int x, int y = 10);', cat: 'functions', pt: 'Argumento com valor padrão', en: 'Argument with a default value' },
  { cmd: 'int f(int a);  int f(double a);', cat: 'functions', pt: 'Sobrecarga — mesmo nome, assinaturas diferentes', en: 'Overloads — same name, different signatures' },
  { cmd: 'void f(int& x) { x = 42; }', cat: 'functions', pt: 'Passa por referência — função pode modificar o caller', en: 'Passes by reference — the function can mutate the caller' },
  { cmd: 'template <typename T> T max(T a, T b) { return a > b ? a : b; }', cat: 'functions', pt: 'Função template — um código para vários tipos', en: 'Template function — one code path for many types' },
  { cmd: 'template <typename T> T max(T a, T b) requires std::totally_ordered<T>', cat: 'functions', pt: 'Template com conceito — restringe os tipos aceitos (C++20)', en: 'Template constrained by a concept (C++20)' },
  { cmd: 'auto f(int x) -> int { return x; }', cat: 'functions', pt: 'Retorno à direita (trailing return)', en: 'Trailing return type' },
  { cmd: 'auto add = [](int a, int b) { return a + b; };', cat: 'functions', pt: 'Lambda — função anônima (C++11)', en: 'Lambda — anonymous function (C++11)' },
  { cmd: '[&] { }  [=] { }  [x] { }', cat: 'functions', pt: 'Captura: por referência, por valor, de x específico', en: 'Capture: by reference, by value, a specific x' },
  { cmd: 'std::function<int(int)> fn = f;', cat: 'functions', pt: 'Wrapper para guardar qualquer função/lambda (C++11)', en: 'Wrapper to store any function/lambda (C++11)' },

  // ─── Ponteiros & memória ──────────────────────────────────────────────────
  { cmd: 'int* p = &x;', cat: 'pointers', pt: 'Ponteiro — guarda o endereço de x', en: 'Pointer — holds the address of x' },
  { cmd: '*p', cat: 'pointers', pt: 'Dereferência — acessa o valor apontado', en: 'Dereference — accesses the pointed-to value' },
  { cmd: 'int* p = nullptr;', cat: 'pointers', pt: 'Ponteiro nulo (não aponta para nada)', en: 'Null pointer (points to nothing)' },
  { cmd: 'int& ref = x;', cat: 'pointers', pt: 'Referência — alias que não pode ser reatribuída', en: 'Reference — an alias that cannot be rebinded' },
  { cmd: 'int* p = new int(5);  delete p;', cat: 'pointers', pt: 'Alocação dinâmica manual — pareamento new/delete', en: 'Manual dynamic allocation — pair new/delete' },
  { cmd: 'int* arr = new int[10];  delete[] arr;', cat: 'pointers', pt: 'Array dinâmico — use new[] e delete[] (e prefira vector)', en: 'Dynamic array — use new[] and delete[] (prefer vector)' },
  { cmd: 'std::unique_ptr<int> p = std::make_unique<int>(5);', cat: 'pointers', pt: 'Smart pointer com posse exclusiva — deleta sozinho (C++11)', en: 'Owning smart pointer — self-deleting (C++11)' },
  { cmd: 'std::shared_ptr<int> p = std::make_shared<int>(5);', cat: 'pointers', pt: 'Posse compartilhada — deleta quando o último dono sai (C++11)', en: 'Shared ownership — deleted when the last owner goes away (C++11)' },
  { cmd: 'std::weak_ptr<int> w = p;', cat: 'pointers', pt: 'Referência fraca — não impede a deleção, evita ciclos', en: 'Weak reference — doesn\'t prevent deletion, breaks cycles' },
  { cmd: 'void f(const std::vector<int>& v)', cat: 'pointers', pt: 'Passe por const& para evitar cópias desnecessárias', en: 'Pass by const& to avoid unnecessary copies' },

  // ─── Strings ──────────────────────────────────────────────────────────────
  { cmd: 'std::string s = "hello";', cat: 'strings', pt: 'Cria uma string', en: 'Creates a string' },
  { cmd: 's.size()  s.empty()', cat: 'strings', pt: 'Tamanho e se está vazia', en: 'Size and emptiness' },
  { cmd: 's + " world"  s.append("!")', cat: 'strings', pt: 'Concatenação', en: 'Concatenation' },
  { cmd: 's[0]  s.at(i)', cat: 'strings', pt: 'Acesso por índice (at() lança se fora do limite)', en: 'Indexed access (at() throws when out of range)' },
  { cmd: 's.substr(0, 3)', cat: 'strings', pt: 'Fatia — posição e comprimento', en: 'Slice — position and length' },
  { cmd: 's.find("lo")', cat: 'strings', pt: 'Busca — retorna std::string::npos se não achar', en: 'Search — returns std::string::npos when not found' },
  { cmd: 's.replace(0, 1, "H")', cat: 'strings', pt: 'Substitui uma faixa por outra string', en: 'Replaces a range with another string' },
  { cmd: 's.c_str()', cat: 'strings', pt: 'Acesso ao buffer estilo C (const char*)', en: 'Access to the C-style buffer (const char*)' },
  { cmd: 'std::getline(std::cin, line)', cat: 'strings', pt: 'Lê uma linha inteira (com espaços)', en: 'Reads a whole line (with spaces)' },
  { cmd: 'std::string_view sv = "abc";', cat: 'strings', pt: 'Vista sem cópia sobre uma string (C++17)', en: 'Copy-free view over a string (C++17)' },
  { cmd: 'for (char c : s) { }', cat: 'strings', pt: 'Itera os caracteres', en: 'Iterates the characters' },
  { cmd: 'if (s == "fim")', cat: 'strings', pt: 'Comparação de conteúdo (== funciona nativamente)', en: 'Content comparison (== works natively)' },

  // ─── Containers STL ───────────────────────────────────────────────────────
  { cmd: 'std::vector<int> v;', cat: 'stl', pt: 'Array dinâmico — o container padrão', en: 'Dynamic array — the default container' },
  { cmd: 'v.push_back(1);  v.pop_back();', cat: 'stl', pt: 'Adiciona/remove no fim (amortizado O(1))', en: 'Push/pop at the end (amortized O(1))' },
  { cmd: 'v.emplace_back(1);', cat: 'stl', pt: 'Constrói in-place — evita cópia temporária', en: 'Constructs in-place — avoids a temporary copy' },
  { cmd: 'v.size()  v.empty()  v.clear()', cat: 'stl', pt: 'Tamanho, vazio e limpar', en: 'Size, emptiness and clear' },
  { cmd: 'v[0]  v.at(0)  v.front()  v.back()', cat: 'stl', pt: 'Acessos — at() valida os limites', en: 'Accesses — at() validates the bounds' },
  { cmd: 'v.reserve(100);', cat: 'stl', pt: 'Reserva capacidade — evita realocações (perf)', en: 'Reserves capacity — avoids reallocations (perf)' },
  { cmd: 'v.erase(v.begin() + i);', cat: 'stl', pt: 'Remove na posição (desloca o restante)', en: 'Removes at a position (shifts the rest)' },
  { cmd: 'std::map<std::string, int> m;', cat: 'stl', pt: 'Árvore ordenada por chave — O(log n)', en: 'Tree ordered by key — O(log n)' },
  { cmd: 'm["chave"] = 1;  m.at("chave")', cat: 'stl', pt: 'Insere/atualiza e lê (at() lança se não existir)', en: 'Insert/update and read (at() throws when missing)' },
  { cmd: 'std::unordered_map<std::string, int> m;', cat: 'stl', pt: 'Hash map — O(1) médio, ordem indefinida', en: 'Hash map — O(1) average, undefined order' },
  { cmd: 'std::set<int> s;  s.insert(3);  s.count(3)', cat: 'stl', pt: 'Conjunto ordenado de valores únicos', en: 'Ordered set of unique values' },
  { cmd: 'std::pair<int, std::string> p = {1, "a"};', cat: 'stl', pt: 'Par de dois valores', en: 'Pair of two values' },
  { cmd: 'std::tuple<int, int, int> t = {1, 2, 3};', cat: 'stl', pt: 'Tupla com vários valores (C++11)', en: 'Tuple with several values (C++11)' },
  { cmd: 'std::deque<int> / std::list<int> / std::stack<int> / std::queue<int>', cat: 'stl', pt: 'Outros containers: fila dupla, lista, pilha, fila', en: 'Other containers: deque, list, stack, queue' },
  { cmd: 'std::priority_queue<int> pq;', cat: 'stl', pt: 'Fila de prioridade (max-heap por padrão)', en: 'Priority queue (max-heap by default)' },
  { cmd: 'for (const auto& [k, v] : m) { }', cat: 'stl', pt: 'Structured bindings — desestrutura o par (C++17)', en: 'Structured bindings — destructures the pair (C++17)' },

  // ─── Algoritmos STL ───────────────────────────────────────────────────────
  { cmd: 'std::sort(v.begin(), v.end());', cat: 'algorithms', pt: 'Ordena (introsort, O(n log n))', en: 'Sorts (introsort, O(n log n))' },
  { cmd: 'std::sort(v.rbegin(), v.rend());', cat: 'algorithms', pt: 'Ordena em ordem decrescente', en: 'Sorts in descending order' },
  { cmd: 'std::sort(v.begin(), v.end(), [](int a, int b) { return a > b; });', cat: 'algorithms', pt: 'Ordena com comparador customizado', en: 'Sorts with a custom comparator' },
  { cmd: 'std::reverse(v.begin(), v.end());', cat: 'algorithms', pt: 'Inverte a ordem', en: 'Reverses the order' },
  { cmd: 'std::find(v.begin(), v.end(), 5);', cat: 'algorithms', pt: 'Procura um valor — retorna o iterador (end() se não achar)', en: 'Finds a value — returns the iterator (end() when absent)' },
  { cmd: 'std::count(v.begin(), v.end(), 5);', cat: 'algorithms', pt: 'Conta ocorrências de um valor', en: 'Counts occurrences of a value' },
  { cmd: 'std::min(a, b)  std::max(a, b)', cat: 'algorithms', pt: 'Menor/maior de dois', en: 'Min/max of two values' },
  { cmd: 'std::minmax_element(v.begin(), v.end());', cat: 'algorithms', pt: 'Retorna o par (menor, maior) em uma passada', en: 'Returns the (min, max) pair in one pass' },
  { cmd: 'std::accumulate(v.begin(), v.end(), 0);', cat: 'algorithms', pt: 'Soma — requer <numeric>', en: 'Sum — requires <numeric>' },
  { cmd: 'std::binary_search(v.begin(), v.end(), 5);', cat: 'algorithms', pt: 'Busca binária — exige vetor ordenado, O(log n)', en: 'Binary search — requires a sorted vector, O(log n)' },
  { cmd: 'std::lower_bound(v.begin(), v.end(), 5);', cat: 'algorithms', pt: 'Primeiro elemento >= 5 (com vetor ordenado)', en: 'First element >= 5 (on a sorted vector)' },
  { cmd: 'std::for_each(v.begin(), v.end(), [](int x) { std::cout << x; });', cat: 'algorithms', pt: 'Aplica uma função a cada elemento', en: 'Applies a function to every element' },
  { cmd: 'std::transform(a.begin(), a.end(), out.begin(), f);', cat: 'algorithms', pt: 'Mapeia cada elemento via função', en: 'Maps each element through a function' },
  { cmd: 'std::remove_if(v.begin(), v.end(), pred);', cat: 'algorithms', pt: 'Move os que sobram para a frente — use com erase()', en: 'Moves survivors forward — combine with erase()' },
  { cmd: 'v.erase(std::remove_if(v.begin(), v.end(), pred), v.end());', cat: 'algorithms', pt: 'O idioma erase-remove — remove de verdade', en: 'The erase-remove idiom — actually removes' },
  { cmd: 'std::swap(a, b);', cat: 'algorithms', pt: 'Troca valores', en: 'Swaps values' },

  // ─── Classes & OOP ────────────────────────────────────────────────────────
  { cmd: 'class Pessoa { public: std::string nome; };', cat: 'oop', pt: 'Classe com membro público', en: 'Class with a public member' },
  { cmd: 'struct Ponto { int x, y; };', cat: 'oop', pt: 'struct — tudo público por padrão', en: 'struct — everything public by default' },
  { cmd: 'private: / protected: / public:', cat: 'oop', pt: 'Controladores de acesso aos membros', en: 'Member access specifiers' },
  { cmd: 'Pessoa() : nome("sem nome") {}', cat: 'oop', pt: 'Construtor com lista de inicialização (preferida)', en: 'Constructor with an initializer list (preferred)' },
  { cmd: 'Pessoa(const Pessoa& o) = default;', cat: 'oop', pt: 'Copy constructor — default = compilador gera', en: 'Copy constructor — default = let the compiler generate' },
  { cmd: '~Pessoa() { limpar(); }', cat: 'oop', pt: 'Destrutor — roda ao sair do escopo (base do RAII)', en: 'Destructor — runs when leaving scope (core of RAII)' },
  { cmd: 'class Cachorro : public Animal { };', cat: 'oop', pt: 'Herança pública', en: 'Public inheritance' },
  { cmd: 'virtual void fala() = 0;', cat: 'oop', pt: 'Método virtual puro — classe abstrata, sem instância', en: 'Pure virtual method — abstract class, no instances' },
  { cmd: 'virtual void fala() {}', cat: 'oop', pt: 'Método virtual — dispatch em tempo de execução', en: 'Virtual method — runtime dispatch' },
  { cmd: 'void fala() override;', cat: 'oop', pt: 'override — garante que está sobrescrevendo (C++11)', en: 'override — guarantees you are overriding (C++11)' },
  { cmd: 'void f() final;', cat: 'oop', pt: 'final — impede sobrescrever em classes-filhas', en: 'final — stops further overriding' },
  { cmd: 'static int total;', cat: 'oop', pt: 'Membro estático — compartilhado entre instâncias', en: 'Static member — shared across instances' },
  { cmd: 'this->nome', cat: 'oop', pt: 'Ponteiro para a própria instância', en: 'Pointer to the current instance' },
  { cmd: 'friend class Outra;', cat: 'oop', pt: 'Concede acesso aos membros privados', en: 'Grants access to private members' },
  { cmd: 'Pessoa(const Pessoa&) = delete;', cat: 'oop', pt: 'Proíbe cópia (= delete) — ex.: classes com mutex', en: 'Deletes the copy — e.g. classes holding a mutex' },

  // ─── C++ moderno ──────────────────────────────────────────────────────────
  { cmd: 'auto x = f();', cat: 'modern', pt: 'auto — o compilador deduz o tipo (use com moderação)', en: 'auto — the compiler deduces the type' },
  { cmd: 'constexpr int quad(int n) { return n * n; }', cat: 'modern', pt: 'constexpr — avaliado em tempo de compilação', en: 'constexpr — evaluated at compile time' },
  { cmd: 'constexpr auto SIZE = 100;', cat: 'modern', pt: 'constinit/constexpr — valores fixos sem custo em runtime', en: 'constexpr — fixed values with no runtime cost' },
  { cmd: 'if constexpr (sizeof(T) > 4) { }', cat: 'modern', pt: 'Condicional avaliada em tempo de compilação (C++17)', en: 'Compile-time conditional (C++17)' },
  { cmd: 'auto [k, v] = m.front();', cat: 'modern', pt: 'Structured binding — desestrutura containers (C++17)', en: 'Structured binding — destructures containers (C++17)' },
  { cmd: 'std::optional<int> r = f();', cat: 'modern', pt: 'Valor que pode ou não existir — evita -1 sentinela (C++17)', en: 'A value that may or may not exist (C++17)' },
  { cmd: 'std::variant<int, std::string> v;', cat: 'modern', pt: 'Union type-safe (C++17)', en: 'Type-safe union (C++17)' },
  { cmd: 'std::string_view sv = url;', cat: 'modern', pt: 'Vista sem posse — passa strings sem copiar (C++17)', en: 'Non-owning view — pass strings without copying (C++17)' },
  { cmd: '[[nodiscard]] int f() { return 1; }', cat: 'modern', pt: 'Avisa se o retorno for ignorado (C++17)', en: 'Warns if the return value is ignored (C++17)' },
  { cmd: 'void f() noexcept;', cat: 'modern', pt: 'Garante que não lança exceção — otimização + contrato', en: 'Guarantees no exceptions — optimization + contract' },
  { cmd: 'std::format("{} {}!", "oi", "mundo");', cat: 'modern', pt: 'Formatação type-safe estilo Python (C++20)', en: 'Type-safe formatting, Python-style (C++20)' },
  { cmd: 'auto r = v | std::views::filter(pred) | std::views::transform(f);', cat: 'modern', pt: 'Ranges — pipelines lazy sobre containers (C++20)', en: 'Ranges — lazy pipelines over containers (C++20)' },
  { cmd: 'template <typename T> concept Numeric = std::is_arithmetic_v<T>;', cat: 'modern', pt: 'Conceito — restringe templates com semântica clara (C++20)', en: 'Concept — constrains templates with clear semantics (C++20)' },
  { cmd: '#include <span>\nvoid f(std::span<int> s)', cat: 'modern', pt: 'span — vista sobre um array/vector sem posse (C++20)', en: 'span — non-owning view over an array/vector (C++20)' },
  { cmd: 'std::array<int, 4> a = {1, 2, 3, 4};', cat: 'modern', pt: 'Array de tamanho fixo com API de container (C++11)', en: 'Fixed-size array with a container API (C++11)' },

  // ─── Concorrência & threads ───────────────────────────────────────────────
  { cmd: 'std::thread t(f);  t.join();', cat: 'concurrency', pt: 'Cria e aguarda uma thread (linke com -pthread)', en: 'Creates and waits for a thread (link with -pthread)' },
  { cmd: 't.detach();', cat: 'concurrency', pt: 'Desprende a thread — cuidado com variáveis locais', en: 'Detaches the thread — watch out for locals' },
  { cmd: 'std::thread t([] { doWork(); });', cat: 'concurrency', pt: 'Thread com lambda', en: 'Thread with a lambda' },
  { cmd: 'std::mutex mtx;  mtx.lock();  mtx.unlock();', cat: 'concurrency', pt: 'Mutex manual — evite, use lock_guard', en: 'Manual mutex — avoid, use lock_guard' },
  { cmd: 'std::lock_guard<std::mutex> lock(mtx);', cat: 'concurrency', pt: 'RAII — trava e destrava sozinho ao sair do escopo', en: 'RAII — locks and unlocks automatically' },
  { cmd: 'std::unique_lock<std::mutex> lock(mtx);', cat: 'concurrency', pt: 'Versão flexível — permite unlock manual e condition_variable', en: 'Flexible version — allows manual unlock and condition_variable' },
  { cmd: 'std::atomic<int> counter{0};', cat: 'concurrency', pt: 'Operação atômica — seguro entre threads sem mutex', en: 'Atomic operation — thread-safe without a mutex' },
  { cmd: 'counter.fetch_add(1);', cat: 'concurrency', pt: 'Incremento atômico', en: 'Atomic increment' },
  { cmd: 'std::async(std::launch::async, f);', cat: 'concurrency', pt: 'Roda assíncrono e retorna um future', en: 'Runs async and returns a future' },
  { cmd: 'auto f = std::async(compute);  int r = f.get();', cat: 'concurrency', pt: 'Espera o resultado da tarefa assíncrona', en: 'Waits for the async task result' },
  { cmd: 'std::this_thread::sleep_for(std::chrono::milliseconds(100));', cat: 'concurrency', pt: 'Dorme a thread atual', en: 'Sleeps the current thread' },
  { cmd: 'std::condition_variable cv;', cat: 'concurrency', pt: 'Sinaliza entre threads (com unique_lock)', en: 'Signals across threads (with unique_lock)' },

  // ─── I/O & arquivos ───────────────────────────────────────────────────────
  { cmd: '#include <fstream>\nstd::ofstream out("a.txt");', cat: 'files', pt: 'Abre arquivo para escrita', en: 'Opens a file for writing' },
  { cmd: 'out << "linha" << std::endl;', cat: 'files', pt: 'Escreve no arquivo', en: 'Writes to the file' },
  { cmd: 'std::ifstream in("a.txt");', cat: 'files', pt: 'Abre arquivo para leitura', en: 'Opens a file for reading' },
  { cmd: 'std::string line;  std::getline(in, line);', cat: 'files', pt: 'Lê linha por linha', en: 'Reads line by line' },
  { cmd: 'while (in >> x) { }', cat: 'files', pt: 'Lê valores separados por espaço até o fim', en: 'Reads space-separated values until EOF' },
  { cmd: 'in.is_open()', cat: 'files', pt: 'Verifica se o arquivo abriu de verdade', en: 'Checks whether the file really opened' },
  { cmd: 'std::ofstream out("a.bin", std::ios::binary);\nout.write(data, n);', cat: 'files', pt: 'Escrita binária', en: 'Binary writing' },
  { cmd: '#include <filesystem>\nstd::filesystem::exists("a.txt");', cat: 'files', pt: 'Verifica se o arquivo existe (C++17)', en: 'Checks whether a file exists (C++17)' },
  { cmd: 'std::filesystem::create_directories("a/b/c");', cat: 'files', pt: 'Cria diretórios recursivamente (C++17)', en: 'Creates directories recursively (C++17)' },
  { cmd: 'std::filesystem::remove("a.txt");', cat: 'files', pt: 'Remove um arquivo (C++17)', en: 'Removes a file (C++17)' },
  { cmd: 'std::cout << std::setprecision(2) << pi;', cat: 'files', pt: 'Precisão de saída (requer <iomanip>)', en: 'Output precision (requires <iomanip>)' },

  // ─── Exceções & erros ─────────────────────────────────────────────────────
  { cmd: 'try { } catch (const std::exception& e) { e.what(); }', cat: 'errors', pt: 'Captura qualquer exceção derivada de std::exception', en: 'Catches any exception derived from std::exception' },
  { cmd: 'throw std::runtime_error("falhou");', cat: 'errors', pt: 'Lança uma exceção com mensagem', en: 'Throws an exception with a message' },
  { cmd: 'catch (const std::out_of_range& e) { }', cat: 'errors', pt: 'Captura um tipo específico (ex.: v.at(i) fora do limite)', en: 'Catches a specific type (e.g. v.at(i) out of range)' },
  { cmd: 'catch (...) { }', cat: 'errors', pt: 'Captura qualquer coisa — use para não abortar', en: 'Catches anything — use it to avoid aborting' },
  { cmd: 'class MeuErro : public std::runtime_error { public: MeuErro() : std::runtime_error("erro") {} };', cat: 'errors', pt: 'Exceção customizada herdando de std::exception', en: 'Custom exception inheriting from std::exception' },
  { cmd: '#include <stdexcept>', cat: 'errors', pt: 'Biblioteca com runtime_error, out_of_range etc.', en: 'Library with runtime_error, out_of_range, etc.' },
  { cmd: 'void f() noexcept;', cat: 'errors', pt: 'Se lançar, o programa chama std::terminate — use com certeza', en: 'If it throws, the program calls std::terminate — be sure' },
]

const translations = {
  pt: {
    title: 'Cheat Sheet de C++',
    intro: (
      <>
        Referência pesquisável da linguagem C++ (padrões C++11 a C++20) —
        CLI e build com g++/CMake, básicos da sintaxe, tipos e conversões,
        controle de fluxo, funções e lambdas, ponteiros e gerenciamento de
        memória, strings, containers e algoritmos da STL, classes e OOP,
        C++ moderno (auto, move, constexpr, ranges, concepts), concorrência
        com threads, I/O de arquivos e tratamento de exceções. Tudo 100%
        client-side (só texto de referência).
      </>
    ),
    tipTitle: 'Dicas rápidas',
    tipBody: (
      <>
        Prefira containers a <Text code>new</Text>/<Text code>delete</Text>:
        use <Text code>std::vector</Text>, smart pointers ({' '}
        <Text code>unique_ptr</Text>/<Text code>shared_ptr</Text>) e passe
        argumentos por <Text code>const&</Text>. Compile sempre com{' '}
        <Text code>-Wall -Wextra</Text> e mire em C++20. Prefira{' '}
        <Text code>std::array</Text>/<Text code>std::string</Text> a arrays e
        char* crus. Evite <Text code>new</Text>/<Text code>delete</Text>{' '}
        manuais — o RAII e os smart pointers já cuidam da memória.
      </>
    ),
    search: 'Buscar snippet ou descrição...',
    all: 'Todos',
    empty: 'Nenhum item encontrado. Tente outra busca ou categoria.',
    resultsOne: 'item encontrado',
    resultsMany: 'itens encontrados',
    copy: 'Copiar como Markdown',
    copied: 'Tabela Markdown copiada',
    copiedError: 'Não foi possível copiar',
    source: 'Fonte de dados (JSON)',
  },
  en: {
    title: 'C++ Cheat Sheet',
    intro: (
      <>
        A searchable reference for the C++ language (C++11 through C++20
        standards) — CLI and builds with g++/CMake, syntax basics, types and
        conversions, control flow, functions and lambdas, pointers and memory
        management, strings, STL containers and algorithms, classes and OOP,
        modern C++ (auto, move, constexpr, ranges, concepts), threading,
        file I/O and exception handling. 100% client-side (reference text
        only).
      </>
    ),
    tipTitle: 'Quick tips',
    tipBody: (
      <>
        Prefer containers over raw <Text code>new</Text>/<Text code>delete</Text>:
        use <Text code>std::vector</Text>, smart pointers ({' '}
        <Text code>unique_ptr</Text>/<Text code>shared_ptr</Text>) and pass
        arguments by <Text code>const&</Text>. Always compile with{' '}
        <Text code>-Wall -Wextra</Text> and target C++20. Prefer{' '}
        <Text code>std::array</Text>/<Text code>std::string</Text> over raw
        arrays and char*. Avoid manual <Text code>new</Text>/
        <Text code>delete</Text> — RAII and smart pointers handle memory for
        you.
      </>
    ),
    search: 'Search a snippet or description...',
    all: 'All',
    empty: 'No matches found. Try another search or category.',
    resultsOne: 'item found',
    resultsMany: 'items found',
    copy: 'Copy as Markdown',
    copied: 'Markdown table copied',
    copiedError: 'Could not copy',
    source: 'Data source (JSON)',
  },
}

export default function CppCheatsheetPage() {
  const { lang } = useLanguage()
  const t = translations[lang]
  const [category, setCategory] = useState('all')
  const [query, setQuery] = useState('')
  const [messageApi, messageContextHolder] = message.useMessage()

  const normalized = useCallback((s) => String(s).trim().toLowerCase(), [])

  const filtered = useMemo(() => {
    const q = normalized(query)
    return COMMANDS.filter((c) => {
      if (category !== 'all' && c.cat !== category) return false
      if (!q) return true
      return (
        c.cmd.toLowerCase().includes(q) ||
        (c[lang] || '').toLowerCase().includes(q) ||
        labelOf[c.cat][lang].toLowerCase().includes(q)
      )
    })
  }, [category, query, lang, normalized])

  const mdTable = useMemo(() => {
    const head = '| Command | Category | Description |\n|---|---|---|\n'
    const rows = filtered.map((c) =>
      `| \`${c.cmd.replace(/\|/g, '\\|').replace(/\n/g, '\\n')}\` | ${labelOf[c.cat][lang]} | ${(c[lang] || '').replace(/\|/g, '\\|')} |`
    )
    return head + rows.join('\n')
  }, [filtered, lang])

  const copyText = useCallback(
    async (text, okMsg) => {
      try {
        await navigator.clipboard.writeText(text)
        messageApi.success(okMsg || t.copied)
      } catch {
        messageApi.error(t.copiedError || 'Error')
      }
    },
    [t, messageApi]
  )

  const resultLabel = filtered.length === 1 ? t.resultsOne : t.resultsMany

  return (
    <Space direction="vertical" size="large" style={{ width: '100%' }}>
      {messageContextHolder}
      <Title level={2}><CodeOutlined /> {t.title}</Title>
      <Paragraph type="secondary">{t.intro}</Paragraph>

      <Alert type="info" showIcon icon={<CodeOutlined />} message={t.tipTitle} description={t.tipBody} />

      <Space direction="vertical" style={{ width: '100%' }}>
        <Input
          prefix={<SearchOutlined />}
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder={t.search}
          allowClear
        />
        <Radio.Group value={category} onChange={(e) => setCategory(e.target.value)} optionType="button">
          <Radio.Button value="all">{t.all}</Radio.Button>
          {CATEGORIES.map((cat) => (
            <Radio.Button key={cat} value={cat}>{labelOf[cat][lang]}</Radio.Button>
          ))}
        </Radio.Group>
      </Space>

      <Space style={{ width: '100%', justifyContent: 'space-between' }}>
        <Text type="secondary">
          {filtered.length} {resultLabel}
        </Text>
        {filtered.length > 0 && (
          <Button size="small" icon={<CopyOutlined />} onClick={() => copyText(mdTable)}>
            {t.copy}
          </Button>
        )}
      </Space>

      <Card>
        <List
          dataSource={filtered}
          locale={{ emptyText: t.empty }}
          renderItem={(item) => (
            <List.Item key={item.cmd}>
              <Space direction="vertical" size={6} style={{ width: '100%' }}>
                <Space wrap style={{ rowGap: 6 }}>
                  <Text code style={{ fontSize: 13, whiteSpace: 'pre-wrap' }}>{item.cmd}</Text>
                  <Tag color={CATEGORY_COLOR[item.cat]}>{labelOf[item.cat][lang]}</Tag>
                  <Button size="small" type="text" icon={<CopyOutlined />} onClick={() => copyText(item.cmd)} />
                </Space>
                <Text type="secondary">{item[lang]}</Text>
              </Space>
            </List.Item>
          )}
        />
      </Card>

      <Collapse items={[
        {
          key: 'source',
          label: t.source,
          children: (
            <pre style={{ margin: 0, overflow: 'auto', fontSize: 12 }}>
              <code>{JSON.stringify(COMMANDS, null, 2)}</code>
            </pre>
          ),
        },
      ]} />
    </Space>
  )
}
