import React, { useEffect, useRef, useState } from 'react'
import { Layout, Menu, Segmented, Tag, theme, Drawer } from 'antd'
import {
  HomeOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  ToolOutlined,
  BgColorsOutlined,
  CodeOutlined,
  KeyOutlined,
  FieldTimeOutlined,
  NumberOutlined,
  FileTextOutlined,
  ApiOutlined,
  DatabaseOutlined,
  CloudOutlined,
  SafetyCertificateOutlined,
  FolderOutlined,
  GlobalOutlined,
  RobotOutlined,
  MobileOutlined,
  FontSizeOutlined,
  ReadOutlined,
  CalendarOutlined,
  SearchOutlined,
  SwapOutlined,
  IdcardOutlined,
  DiffOutlined,
  FileMarkdownOutlined,
  BranchesOutlined,
  LinkOutlined,
  ColumnWidthOutlined,
  OrderedListOutlined,
  FileProtectOutlined,
  ExperimentOutlined,
  UserOutlined,
  InboxOutlined,
  TableOutlined,
  ClusterOutlined,
  PictureOutlined,
  ContainerOutlined,
  LineChartOutlined,
  SendOutlined,
  HistoryOutlined,
  CreditCardOutlined,
  QrcodeOutlined,
  GithubOutlined,
  AudioOutlined,
} from '@ant-design/icons'
import { Outlet, useNavigate, useLocation } from 'react-router-dom'
import { useLanguage } from '../i18n/LanguageContext'
import { NEW_ITEM_KEYS } from '../newItems'
import { useNewItemKeys } from '../hooks/useNewItemKeys'
import useMediaQuery from '../hooks/useMediaQuery'
import BugReportWidget from './BugReportWidget'

const { Header, Sider, Content } = Layout

// Labels do menu por idioma — rótulos apenas, a lista de rotas/ícones fica
// fixa abaixo. Rodadas futuras do agente: ao adicionar uma página nova,
// adicione o par pt/en aqui também.
export const LABELS = {
  pt: {
    home: 'Home',
    tools: 'Ferramentas',
    styles: 'Estilos',
    snippets: 'Snippets',
    frontend: 'Front-end',
    apis: 'APIs',
    devops: 'DevOps',
    database: 'Banco de Dados',
    cloud: 'Cloud',
    security: 'Segurança',
    data: 'Arquivos & Dados',
    network: 'Rede',
    ai: 'IA',
    mobile: 'Mobile',
    text: 'Texto',
    references: 'Referências',
    extras: 'Fora da caixa',
    new: 'Novo',
    'jwt-decoder': 'Decodificador JWT',
    'cron-parser': 'Explicador de Cron',
    'hash-generator': 'Gerador de Hash',
    'json-formatter': 'Formatador de JSON',
    'color-converter': 'Conversor de Cor',
    'timestamp-converter': 'Conversor de Timestamp',
    'glass-card': 'Glass Card',
    'copy-button': 'Botão de Copiar Animado',
    'skeleton-shimmer': 'Skeleton Shimmer',
    'gradient-border-button': 'Botão com Borda Gradiente',
    'use-debounce': 'useDebounce',
    'use-local-storage': 'useLocalStorage',
    'use-click-outside': 'useClickOutside',
    'use-media-query': 'useMediaQuery',
    'contrast-checker': 'Checador de Contraste',
    'curl-generator': 'Gerador de cURL',
    'curl-to-code': 'cURL → Código (fetch/axios)',
    'gitignore-generator': 'Gerador de .gitignore',
    'rate-limit-calculator': 'Calculadora de Rate Limit',
    'arn-parser': 'AWS ARN Parser',
    'password-strength': 'Força de Senha',
    'json-tree-viewer': 'Visualizador de Árvore JSON',
    'subnet-calculator': 'Calculadora de Sub-rede',
    'anthropic-cost-calculator': 'Calculadora de Custo Anthropic',
    'deep-link-tester': 'Testador de Deep Link',
    'word-counter': 'Contador de Palavras',
    'git-commands': 'Comandos Git',
    'days-until': 'Quantos dias até...',
    'regex-tester': 'Regex Tester',
    'base64-tool': 'Base64 Encode/Decode',
    'uuid-generator': 'Gerador de UUID',
    'case-converter': 'Conversor de Case',
    'password-generator': 'Gerador de Senha',
    'url-encoder': 'URL Encode/Decode',
    'url-parser': 'URL Parser & Query Editor',
    'gradient-generator': 'Gerador de Gradiente CSS',
    'use-copy-to-clipboard': 'useCopyToClipboard',
    'http-status-codes': 'HTTP Status Codes',
    'diff-checker': 'Comparador de Texto (Diff)',
    'box-shadow-generator': 'Gerador de Box Shadow',
    'csv-json-converter': 'Conversor CSV ↔ JSON',
    'use-interval': 'useInterval',
    'markdown-previewer': 'Markdown → HTML (Preview)',
    'neumorphic-card': 'Cartão Neumórfico',
    'use-previous': 'usePrevious',
    'fake-data-generator': 'Gerador de Dados Fake',
    'webhook-payload-generator': 'Gerador de Payload de Webhook',
    'cpf-cnpj-generator': 'Gerador de CPF/CNPJ',
    'base-converter': 'Conversor de Base Numérica',
    'use-toggle': 'useToggle',
    'use-window-size': 'useWindowSize',
    'bouncing-dots-loader': 'Loading de Dots Saltitantes',
    'docker-commands': 'Comandos Docker',
    'semver-comparator': 'Comparador de SemVer',
    'slug-generator': 'Gerador de Slug',
    'palette-generator': 'Gerador de Paleta de Cores',
    'ripple-button': 'Botão com Efeito Ripple',
    'use-on-screen': 'useOnScreen',
    'flexbox-cheatsheet': 'Cheat Sheet de Flexbox',
    'css-unit-converter': 'Conversor de Unidades CSS',
    'css-specificity-calculator': 'Calculadora de Especificidade CSS',
    'floating-label-input': 'Input com Label Flutuante',
    'use-key-press': 'useKeyPress',
    'sql-commands': 'Comandos SQL',
    'nanoid-generator': 'Gerador de NanoID',
    'html-entity-encoder': 'HTML Entity Encode/Decode',
    'border-radius-generator': 'Gerador de Border Radius',
    'ios-toggle-switch': 'Switch Estilo iOS',
    'use-event-listener': 'useEventListener',
    'package-manager-commands': 'npm vs yarn vs pnpm',
    'hmac-generator': 'Gerador de HMAC',
    'lorem-ipsum-generator': 'Gerador de Lorem Ipsum',
    'json-diff': 'JSON Diff',
    'dark-mode-toggle': 'Dark Mode Toggle',
    'use-throttle': 'useThrottle',
    'vscode-shortcuts': 'Atalhos VSCode',
    'json-path-explorer': 'JSON Path Explorer',
    'css-grid-cheatsheet': 'Cheat Sheet de CSS Grid',
    'fisher-yates-shuffle': 'Fisher-Yates Shuffle',
    'team-roulette': 'Roleta de Sorteio',
    'jwt-generator': 'Gerador de JWT',
    'toast-notification': 'Toast com Auto-Dismiss',
    'use-undo': 'useUndo',
    'bash-shortcuts': 'Atalhos de Terminal/Bash',
    'commit-message-generator': 'Gerador de Mensagem de Commit',
    'robots-txt-generator': 'Gerador de robots.txt',
    'scroll-progress-bar': 'Indicador de Progresso de Scroll',
    'confetti-effect': 'Efeito de Confete',
    'debounce-throttle-functions': 'debounce/throttle (função)',
    'jwt-timeline': 'Timeline de Expiração do JWT',
    'typewriter-effect': 'Efeito de Máquina de Escrever',
    'lru-cache': 'LRU Cache',
    'csp-generator': 'Gerador de CSP',
    'token-counter': 'Contador de Tokens',
    'pomodoro-timer': 'Timer Pomodoro',
    'env-tool': 'Validador de .env',
    'remove-accents': 'Remover Acentos',
    'xml-formatter': 'Formatador de XML',
    'deep-clone-deep-equal': 'deepClone & deepEqual',
    'branch-name-generator': 'Gerador de Nome de Branch',
    'lines-tool': 'Processador de Linhas',
    'html-to-jsx-converter': 'Conversor HTML → JSX',
    'html-to-markdown': 'Conversor HTML → Markdown',
    'uuid-collision-simulator': 'Simulador de Colisão de UUID',
    'unicode-inspector': 'Inspetor de Unicode',
    'json-to-sql': 'JSON → SQL INSERT',
    'sorting-visualizer': 'Visualizador de Ordenação',
    'otp-input': 'Input OTP (código de verificação)',
    'timezone-converter': 'Conversor de Fuso Horário',
    'user-agent-parser': 'Parser de User-Agent',
    'cron-builder': 'Construtor de Cron',
    'mime-lookup': 'Lookup de MIME Types',
    'http-methods': 'Métodos HTTP',
    'number-to-words': 'Número por Extenso',
    'json-schema-generator': 'Gerador de JSON Schema',
    'json-schema-validator': 'Validador de JSON Schema',
    'css-formatter': 'Formatador de CSS',
    'sql-formatter': 'Formatador de SQL',
    'common-ports': 'Portas de Rede Comuns',
    'ipv6-explorer': 'Explorador IPv6',
    'csv-markdown-table': 'CSV → Tabela Markdown',
    'markdown-syntax': 'Sintaxe Markdown',
    'kubectl-commands': 'Comandos kubectl',
    'chmod-calculator': 'Calculadora de Permissões (chmod)',
    'float-explorer': 'Explorador de Float (IEEE-754)',
    'svg-placeholder-generator': 'Gerador de Placeholder SVG',
    'dockerfile-generator': 'Gerador de Dockerfile',
    'cubic-bezier-editor': 'Editor de Curva de Easing',
    'ansi-colors': 'Cores ANSI (terminal)',
    'ascii-table': 'Tabela ASCII',
    'svg-wave-generator': 'Gerador de Onda SVG',
    'css-filter-generator': 'Gerador de Filtros CSS',
    'keyframe-generator': 'Gerador de Keyframes',
    'meta-tags-generator': 'Gerador de Meta Tags (SEO/OG)',
    'clip-path-generator': 'Gerador de clip-path (Polygon)',
    'toml-formatter': 'Formatador de TOML',
    'regex-cheatsheet': 'Cheat Sheet de Regex',
    'crc-calculator': 'Calculadora de CRC',
    'json-to-typescript': 'JSON → TypeScript',
    'json-to-yaml': 'JSON → YAML',
    'caddyfile-generator': 'Gerador de Caddyfile',
    'docker-compose-generator': 'Gerador de docker-compose',
    'openssl-commands': 'Comandos OpenSSL',
    'units-converter': 'Conversor de Unidades',
    'http-headers': 'Cabeçalhos HTTP',
    'javascript-cheatsheet': 'Cheat Sheet de JavaScript (ES6+)',
    'tmux-cheatsheet': 'Comandos tmux',
    'devtools-shortcuts': 'Atalhos do DevTools',
    'vim-cheatsheet': 'Comandos Vim',
    'ssh-cheatsheet': 'Comandos SSH',
    'python-cheatsheet': 'Cheat Sheet de Python',
    'grep-sed-awk': 'grep/sed/awk',
    'jq-cheatsheet': 'Comandos jq',
    'changelog-generator': 'Gerador de Changelog',
    'scrollbar-generator': 'Gerador de Scrollbar CSS',
    'bash-scripting': 'Scripts em Bash (shell scripting)',
    'systemd-commands': 'Comandos systemd',
    'sla-calculator': 'Calculadora de SLA (downtime)',
    'credit-card-tool': 'Gerador/Validador de Cartão (Luhn)',
    'qr-code-generator': 'Gerador de QR Code',
    'html-formatter': 'Formatador de HTML',
    'github-actions-cheatsheet': 'GitHub Actions (workflows)',
    'css-to-js': 'CSS ↔ JS (style object)',
    'nginx-cheatsheet': 'Cheat Sheet de Nginx',
    'redis-commands': 'Comandos Redis',
    'gh-cli-cheatsheet': 'GitHub CLI (gh)',
    'typescript-cheatsheet': 'Cheat Sheet de TypeScript',
    'clamp-generator': 'Tipografia Fluida (clamp)',
    'morse-code-converter': 'Conversor de Código Morse',
    'glob-tester': 'Glob Pattern Tester (gitignore)',
    'html-cheatsheet': 'Cheat Sheet de HTML',
    'js-testing-cheatsheet': 'Cheat Sheet de Testes JS (Jest/Vitest)',
    'react-cheatsheet': 'Cheat Sheet de React',
  },
  en: {
    home: 'Home',
    tools: 'Tools',
    styles: 'Styles',
    snippets: 'Snippets',
    frontend: 'Front-end',
    apis: 'APIs',
    devops: 'DevOps',
    database: 'Database',
    cloud: 'Cloud',
    security: 'Security',
    data: 'Files & Data',
    network: 'Network',
    ai: 'AI',
    mobile: 'Mobile',
    text: 'Text',
    references: 'References',
    extras: 'Out of the box',
    new: 'New',
    'jwt-decoder': 'JWT Decoder',
    'cron-parser': 'Cron Expression Explainer',
    'hash-generator': 'Hash Generator',
    'json-formatter': 'JSON Formatter',
    'color-converter': 'Color Converter',
    'timestamp-converter': 'Timestamp Converter',
    'glass-card': 'Glass Card',
    'copy-button': 'Animated Copy Button',
    'skeleton-shimmer': 'Skeleton Shimmer',
    'gradient-border-button': 'Gradient Border Button',
    'use-debounce': 'useDebounce',
    'use-local-storage': 'useLocalStorage',
    'use-click-outside': 'useClickOutside',
    'use-media-query': 'useMediaQuery',
    'contrast-checker': 'Contrast Checker',
    'curl-generator': 'cURL Generator',
    'curl-to-code': 'cURL → Code (fetch/axios)',
    'gitignore-generator': '.gitignore Generator',
    'rate-limit-calculator': 'Rate Limit Calculator',
    'arn-parser': 'AWS ARN Parser',
    'password-strength': 'Password Strength',
    'json-tree-viewer': 'JSON Tree Viewer',
    'subnet-calculator': 'Subnet Calculator',
    'anthropic-cost-calculator': 'Anthropic Cost Calculator',
    'deep-link-tester': 'Deep Link Tester',
    'word-counter': 'Word Counter',
    'git-commands': 'Git Commands',
    'days-until': 'Days Until...',
    'regex-tester': 'Regex Tester',
    'base64-tool': 'Base64 Encode/Decode',
    'uuid-generator': 'UUID Generator',
    'case-converter': 'Case Converter',
    'password-generator': 'Password Generator',
    'url-encoder': 'URL Encode/Decode',
    'url-parser': 'URL Parser & Query Editor',
    'gradient-generator': 'CSS Gradient Generator',
    'use-copy-to-clipboard': 'useCopyToClipboard',
    'http-status-codes': 'HTTP Status Codes',
    'diff-checker': 'Text Diff Checker',
    'box-shadow-generator': 'Box Shadow Generator',
    'csv-json-converter': 'CSV ↔ JSON Converter',
    'use-interval': 'useInterval',
    'markdown-previewer': 'Markdown → HTML (Preview)',
    'neumorphic-card': 'Neumorphic Card',
    'use-previous': 'usePrevious',
    'fake-data-generator': 'Fake Data Generator',
    'webhook-payload-generator': 'Webhook Payload Generator',
    'cpf-cnpj-generator': 'CPF/CNPJ Generator',
    'base-converter': 'Number Base Converter',
    'use-toggle': 'useToggle',
    'use-window-size': 'useWindowSize',
    'bouncing-dots-loader': 'Bouncing Dots Loader',
    'docker-commands': 'Docker Commands',
    'semver-comparator': 'SemVer Comparator',
    'slug-generator': 'Slug Generator',
    'palette-generator': 'Color Palette Generator',
    'ripple-button': 'Ripple Effect Button',
    'use-on-screen': 'useOnScreen',
    'flexbox-cheatsheet': 'Flexbox Cheat Sheet',
    'css-unit-converter': 'CSS Unit Converter',
    'css-specificity-calculator': 'CSS Specificity Calculator',
    'floating-label-input': 'Floating Label Input',
    'use-key-press': 'useKeyPress',
    'sql-commands': 'SQL Commands',
    'nanoid-generator': 'NanoID Generator',
    'html-entity-encoder': 'HTML Entity Encode/Decode',
    'border-radius-generator': 'Border Radius Generator',
    'ios-toggle-switch': 'iOS-style Switch',
    'use-event-listener': 'useEventListener',
    'package-manager-commands': 'npm vs yarn vs pnpm',
    'hmac-generator': 'HMAC Generator',
    'lorem-ipsum-generator': 'Lorem Ipsum Generator',
    'json-diff': 'JSON Diff',
    'dark-mode-toggle': 'Dark Mode Toggle',
    'use-throttle': 'useThrottle',
    'vscode-shortcuts': 'VSCode Shortcuts',
    'json-path-explorer': 'JSON Path Explorer',
    'css-grid-cheatsheet': 'CSS Grid Cheat Sheet',
    'fisher-yates-shuffle': 'Fisher-Yates Shuffle',
    'team-roulette': 'Team Roulette',
    'jwt-generator': 'JWT Generator',
    'toast-notification': 'Toast with Auto-Dismiss',
    'use-undo': 'useUndo',
    'bash-shortcuts': 'Terminal/Bash Shortcuts',
    'commit-message-generator': 'Commit Message Generator',
    'robots-txt-generator': 'robots.txt Generator',
    'scroll-progress-bar': 'Scroll Progress Indicator',
    'confetti-effect': 'Confetti Effect',
    'debounce-throttle-functions': 'debounce/throttle (function)',
    'jwt-timeline': 'JWT Expiration Timeline',
    'typewriter-effect': 'Typewriter Effect',
    'lru-cache': 'LRU Cache',
    'csp-generator': 'CSP Generator',
    'token-counter': 'Token Counter',
    'pomodoro-timer': 'Pomodoro Timer',
    'env-tool': '.env File Validator',
    'remove-accents': 'Remove Accents',
    'xml-formatter': 'XML Formatter',
    'deep-clone-deep-equal': 'deepClone & deepEqual',
    'branch-name-generator': 'Branch Name Generator',
    'lines-tool': 'Lines Tool',
    'html-to-jsx-converter': 'HTML → JSX Converter',
    'html-to-markdown': 'HTML → Markdown Converter',
    'uuid-collision-simulator': 'UUID Collision Simulator',
    'unicode-inspector': 'Unicode Inspector',
    'json-to-sql': 'JSON → SQL INSERT',
    'sorting-visualizer': 'Sorter Visualizer',
    'otp-input': 'OTP Input (verification code)',
    'timezone-converter': 'Timezone Converter',
    'user-agent-parser': 'User-Agent Parser',
    'cron-builder': 'Cron Builder',
    'mime-lookup': 'MIME Types Lookup',
    'http-methods': 'HTTP Methods',
    'number-to-words': 'Number to Words',
    'json-schema-generator': 'JSON Schema Generator',
    'json-schema-validator': 'JSON Schema Validator',
    'css-formatter': 'CSS Formatter',
    'sql-formatter': 'SQL Formatter',
    'common-ports': 'Common Network Ports',
    'ipv6-explorer': 'IPv6 Explorer',
    'csv-markdown-table': 'CSV → Markdown Table',
    'markdown-syntax': 'Markdown Syntax',
    'kubectl-commands': 'kubectl Commands',
    'chmod-calculator': 'File Permission Calculator (chmod)',
    'float-explorer': 'Float Explorer (IEEE-754)',
    'svg-placeholder-generator': 'SVG Placeholder Generator',
    'dockerfile-generator': 'Dockerfile Generator',
    'cubic-bezier-editor': 'Cubic Bézier Easing Editor',
    'ansi-colors': 'ANSI Colors',
    'ascii-table': 'ASCII Table',
    'svg-wave-generator': 'SVG Wave Generator',
    'css-filter-generator': 'CSS Filter Generator',
    'keyframe-generator': 'Keyframes Generator',
    'meta-tags-generator': 'Meta Tags Generator (SEO/OG)',
    'clip-path-generator': 'clip-path Generator (Polygon)',
    'toml-formatter': 'TOML Formatter',
    'regex-cheatsheet': 'Regex Cheat Sheet',
    'crc-calculator': 'CRC Checksum Calculator',
    'json-to-typescript': 'JSON → TypeScript',
    'json-to-yaml': 'JSON → YAML',
    'caddyfile-generator': 'Caddyfile Generator',
    'docker-compose-generator': 'docker-compose Generator',
    'openssl-commands': 'OpenSSL Commands',
    'units-converter': 'Units Converter',
    'http-headers': 'HTTP Headers',
    'javascript-cheatsheet': 'JavaScript Cheat Sheet (ES6+)',
    'tmux-cheatsheet': 'tmux Commands',
    'devtools-shortcuts': 'Browser DevTools Shortcuts',
    'vim-cheatsheet': 'Vim Commands',
    'ssh-cheatsheet': 'SSH Commands',
    'python-cheatsheet': 'Python Cheat Sheet',
    'grep-sed-awk': 'grep/sed/awk',
    'jq-cheatsheet': 'jq Commands',
    'changelog-generator': 'Changelog Generator',
    'scrollbar-generator': 'CSS Scrollbar Generator',
    'bash-scripting': 'Bash Scripting',
    'systemd-commands': 'systemd Commands',
    'sla-calculator': 'SLA Calculator (downtime budget)',
    'credit-card-tool': 'Credit Card Generator/Validator (Luhn)',
    'qr-code-generator': 'QR Code Generator',
    'html-formatter': 'HTML Formatter',
    'github-actions-cheatsheet': 'GitHub Actions (workflows)',
    'css-to-js': 'CSS ↔ JS (style object)',
    'nginx-cheatsheet': 'Nginx Cheat Sheet',
    'redis-commands': 'Redis Commands',
    'gh-cli-cheatsheet': 'GitHub CLI (gh)',
    'typescript-cheatsheet': 'TypeScript Cheat Sheet',
    'clamp-generator': 'Fluid Typography (clamp)',
    'morse-code-converter': 'Morse Code Converter',
    'glob-tester': 'Glob Pattern Tester (gitignore)',
    'html-cheatsheet': 'HTML Cheat Sheet',
    'js-testing-cheatsheet': 'JS Testing Cheat Sheet (Jest/Vitest)',
    'react-cheatsheet': 'React Cheat Sheet',
  },
}

function withNewBadge(key, label, l) {
  if (!NEW_ITEM_KEYS.includes(key)) return label
  return (
    <span>
      {label} <Tag color="green" style={{ marginLeft: 4, lineHeight: '16px', fontSize: 11 }}>{l.new}</Tag>
    </span>
  )
}

// Exportado pra HomePage.jsx remontar a mesma árvore de categorias/itens na
// grade da home, sem duplicar a fonte da verdade — o agente noturno só
// mexe aqui, então a home fica sincronizada de graça.
export function buildMenuItems(l) {
  return [
    { key: '/', icon: <HomeOutlined />, label: l.home },
    {
      key: 'group-tools',
      icon: <ToolOutlined />,
      label: l.tools,
      children: [
        { key: '/tools/jwt-decoder', icon: <KeyOutlined />, label: l['jwt-decoder'] },
        { key: '/tools/html-to-jsx-converter', icon: <CodeOutlined />, label: withNewBadge('/tools/html-to-jsx-converter', l['html-to-jsx-converter'], l) },
        { key: '/tools/html-to-markdown', icon: <FileMarkdownOutlined />, label: withNewBadge('/tools/html-to-markdown', l['html-to-markdown'], l) },
        { key: '/tools/cron-parser', icon: <FieldTimeOutlined />, label: withNewBadge('/tools/cron-parser', l['cron-parser'], l) },
        { key: '/tools/cron-builder', icon: <FieldTimeOutlined />, label: withNewBadge('/tools/cron-builder', l['cron-builder'], l) },
        { key: '/tools/hash-generator', icon: <NumberOutlined />, label: l['hash-generator'] },
        { key: '/tools/json-formatter', icon: <FileTextOutlined />, label: l['json-formatter'] },
        { key: '/tools/color-converter', icon: <BgColorsOutlined />, label: l['color-converter'] },
        { key: '/tools/xml-formatter', icon: <FileTextOutlined />, label: withNewBadge('/tools/xml-formatter', l['xml-formatter'], l) },
        { key: '/tools/css-formatter', icon: <FileTextOutlined />, label: withNewBadge('/tools/css-formatter', l['css-formatter'], l) },
        { key: '/tools/toml-formatter', icon: <FileTextOutlined />, label: withNewBadge('/tools/toml-formatter', l['toml-formatter'], l) },
        { key: '/tools/html-formatter', icon: <FileTextOutlined />, label: withNewBadge('/tools/html-formatter', l['html-formatter'], l) },
        { key: '/tools/timestamp-converter', icon: <FieldTimeOutlined />, label: l['timestamp-converter'] },
        { key: '/tools/regex-tester', icon: <SearchOutlined />, label: withNewBadge('/tools/regex-tester', l['regex-tester'], l) },
        { key: '/tools/base64-tool', icon: <SwapOutlined />, label: withNewBadge('/tools/base64-tool', l['base64-tool'], l) },
        { key: '/tools/uuid-generator', icon: <IdcardOutlined />, label: withNewBadge('/tools/uuid-generator', l['uuid-generator'], l) },
        { key: '/tools/case-converter', icon: <FontSizeOutlined />, label: withNewBadge('/tools/case-converter', l['case-converter'], l) },
        { key: '/tools/password-generator', icon: <KeyOutlined />, label: withNewBadge('/tools/password-generator', l['password-generator'], l) },
        { key: '/tools/url-encoder', icon: <SwapOutlined />, label: withNewBadge('/tools/url-encoder', l['url-encoder'], l) },
        { key: '/tools/url-parser', icon: <LinkOutlined />, label: withNewBadge('/tools/url-parser', l['url-parser'], l) },
        { key: '/tools/diff-checker', icon: <DiffOutlined />, label: withNewBadge('/tools/diff-checker', l['diff-checker'], l) },
        { key: '/tools/markdown-previewer', icon: <FileMarkdownOutlined />, label: withNewBadge('/tools/markdown-previewer', l['markdown-previewer'], l) },
        { key: '/tools/cpf-cnpj-generator', icon: <IdcardOutlined />, label: withNewBadge('/tools/cpf-cnpj-generator', l['cpf-cnpj-generator'], l) },
        { key: '/tools/base-converter', icon: <NumberOutlined />, label: withNewBadge('/tools/base-converter', l['base-converter'], l) },
        { key: '/tools/semver-comparator', icon: <BranchesOutlined />, label: withNewBadge('/tools/semver-comparator', l['semver-comparator'], l) },
        { key: '/tools/slug-generator', icon: <LinkOutlined />, label: withNewBadge('/tools/slug-generator', l['slug-generator'], l) },
        { key: '/tools/css-unit-converter', icon: <ColumnWidthOutlined />, label: withNewBadge('/tools/css-unit-converter', l['css-unit-converter'], l) },
        { key: '/tools/css-specificity-calculator', icon: <OrderedListOutlined />, label: withNewBadge('/tools/css-specificity-calculator', l['css-specificity-calculator'], l) },
        { key: '/tools/nanoid-generator', icon: <IdcardOutlined />, label: withNewBadge('/tools/nanoid-generator', l['nanoid-generator'], l) },
        { key: '/tools/html-entity-encoder', icon: <SwapOutlined />, label: withNewBadge('/tools/html-entity-encoder', l['html-entity-encoder'], l) },
        { key: '/tools/hmac-generator', icon: <KeyOutlined />, label: withNewBadge('/tools/hmac-generator', l['hmac-generator'], l) },
        { key: '/tools/lorem-ipsum-generator', icon: <FileTextOutlined />, label: withNewBadge('/tools/lorem-ipsum-generator', l['lorem-ipsum-generator'], l) },
        { key: '/tools/jwt-generator', icon: <KeyOutlined />, label: withNewBadge('/tools/jwt-generator', l['jwt-generator'], l) },
        { key: '/tools/jwt-timeline', icon: <FieldTimeOutlined />, label: withNewBadge('/tools/jwt-timeline', l['jwt-timeline'], l) },
        { key: '/tools/unicode-inspector', icon: <CodeOutlined />, label: withNewBadge('/tools/unicode-inspector', l['unicode-inspector'], l) },
        { key: '/tools/timezone-converter', icon: <GlobalOutlined />, label: withNewBadge('/tools/timezone-converter', l['timezone-converter'], l) },
        { key: '/tools/number-to-words', icon: <NumberOutlined />, label: withNewBadge('/tools/number-to-words', l['number-to-words'], l) },
        { key: '/tools/float-explorer', icon: <NumberOutlined />, label: withNewBadge('/tools/float-explorer', l['float-explorer'], l) },
        { key: '/tools/crc-calculator', icon: <SafetyCertificateOutlined />, label: withNewBadge('/tools/crc-calculator', l['crc-calculator'], l) },
        { key: '/tools/units-converter', icon: <SwapOutlined />, label: withNewBadge('/tools/units-converter', l['units-converter'], l) },
        { key: '/tools/credit-card-tool', icon: <CreditCardOutlined />, label: withNewBadge('/tools/credit-card-tool', l['credit-card-tool'], l) },
        { key: '/tools/qr-code-generator', icon: <QrcodeOutlined />, label: withNewBadge('/tools/qr-code-generator', l['qr-code-generator'], l) },
        { key: '/tools/morse-code-converter', icon: <AudioOutlined />, label: withNewBadge('/tools/morse-code-converter', l['morse-code-converter'], l) },
        { key: '/tools/glob-tester', icon: <SearchOutlined />, label: withNewBadge('/tools/glob-tester', l['glob-tester'], l) },
      ],
    },
    {
      key: 'group-styles',
      icon: <BgColorsOutlined />,
      label: l.styles,
      children: [
        { key: '/styles/glass-card', label: l['glass-card'] },
        { key: '/styles/copy-button', label: l['copy-button'] },
        { key: '/styles/skeleton-shimmer', label: l['skeleton-shimmer'] },
        { key: '/styles/gradient-border-button', label: l['gradient-border-button'] },
        { key: '/styles/neumorphic-card', label: withNewBadge('/styles/neumorphic-card', l['neumorphic-card'], l) },
        { key: '/styles/bouncing-dots-loader', label: withNewBadge('/styles/bouncing-dots-loader', l['bouncing-dots-loader'], l) },
        { key: '/styles/ripple-button', label: withNewBadge('/styles/ripple-button', l['ripple-button'], l) },
        { key: '/styles/floating-label-input', label: withNewBadge('/styles/floating-label-input', l['floating-label-input'], l) },
        { key: '/styles/ios-toggle-switch', label: withNewBadge('/styles/ios-toggle-switch', l['ios-toggle-switch'], l) },
        { key: '/styles/dark-mode-toggle', label: withNewBadge('/styles/dark-mode-toggle', l['dark-mode-toggle'], l) },
        { key: '/styles/toast-notification', label: withNewBadge('/styles/toast-notification', l['toast-notification'], l) },
        { key: '/styles/scroll-progress-bar', label: withNewBadge('/styles/scroll-progress-bar', l['scroll-progress-bar'], l) },
        { key: '/styles/confetti-effect', label: withNewBadge('/styles/confetti-effect', l['confetti-effect'], l) },
        { key: '/styles/typewriter-effect', label: withNewBadge('/styles/typewriter-effect', l['typewriter-effect'], l) },
        { key: '/styles/otp-input', icon: <NumberOutlined />, label: withNewBadge('/styles/otp-input', l['otp-input'], l) },
      ],
    },
    {
      key: 'group-snippets',
      icon: <CodeOutlined />,
      label: l.snippets,
      children: [
        { key: '/snippets/use-debounce', label: l['use-debounce'] },
        { key: '/snippets/use-local-storage', label: l['use-local-storage'] },
        { key: '/snippets/use-click-outside', label: l['use-click-outside'] },
        { key: '/snippets/use-media-query', label: l['use-media-query'] },
        { key: '/snippets/use-copy-to-clipboard', label: withNewBadge('/snippets/use-copy-to-clipboard', l['use-copy-to-clipboard'], l) },
        { key: '/snippets/use-interval', label: withNewBadge('/snippets/use-interval', l['use-interval'], l) },
        { key: '/snippets/use-previous', label: withNewBadge('/snippets/use-previous', l['use-previous'], l) },
        { key: '/snippets/use-toggle', label: withNewBadge('/snippets/use-toggle', l['use-toggle'], l) },
        { key: '/snippets/use-window-size', label: withNewBadge('/snippets/use-window-size', l['use-window-size'], l) },
        { key: '/snippets/use-on-screen', label: withNewBadge('/snippets/use-on-screen', l['use-on-screen'], l) },
        { key: '/snippets/use-key-press', label: withNewBadge('/snippets/use-key-press', l['use-key-press'], l) },
        { key: '/snippets/use-event-listener', label: withNewBadge('/snippets/use-event-listener', l['use-event-listener'], l) },
        { key: '/snippets/use-throttle', label: withNewBadge('/snippets/use-throttle', l['use-throttle'], l) },
        { key: '/snippets/fisher-yates-shuffle', label: withNewBadge('/snippets/fisher-yates-shuffle', l['fisher-yates-shuffle'], l) },
        { key: '/snippets/use-undo', label: withNewBadge('/snippets/use-undo', l['use-undo'], l) },
        { key: '/snippets/debounce-throttle-functions', label: withNewBadge('/snippets/debounce-throttle-functions', l['debounce-throttle-functions'], l) },
        { key: '/snippets/lru-cache', label: withNewBadge('/snippets/lru-cache', l['lru-cache'], l) },
        { key: '/snippets/deep-clone-deep-equal', label: withNewBadge('/snippets/deep-clone-deep-equal', l['deep-clone-deep-equal'], l) },
      ],
    },
    {
      key: 'group-frontend',
      icon: <BgColorsOutlined />,
      label: l.frontend,
      children: [
        { key: '/frontend/contrast-checker', label: l['contrast-checker'] },
        { key: '/frontend/gradient-generator', label: withNewBadge('/frontend/gradient-generator', l['gradient-generator'], l) },
        { key: '/frontend/box-shadow-generator', label: withNewBadge('/frontend/box-shadow-generator', l['box-shadow-generator'], l) },
        { key: '/frontend/palette-generator', label: withNewBadge('/frontend/palette-generator', l['palette-generator'], l) },
        { key: '/frontend/border-radius-generator', label: withNewBadge('/frontend/border-radius-generator', l['border-radius-generator'], l) },
        { key: '/frontend/svg-placeholder-generator', icon: <PictureOutlined />, label: withNewBadge('/frontend/svg-placeholder-generator', l['svg-placeholder-generator'], l) },
        { key: '/frontend/cubic-bezier-editor', icon: <LineChartOutlined />, label: withNewBadge('/frontend/cubic-bezier-editor', l['cubic-bezier-editor'], l) },
        { key: '/frontend/svg-wave-generator', icon: <PictureOutlined />, label: withNewBadge('/frontend/svg-wave-generator', l['svg-wave-generator'], l) },
        { key: '/frontend/css-filter-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-filter-generator', l['css-filter-generator'], l) },
        { key: '/frontend/meta-tags-generator', icon: <GlobalOutlined />, label: withNewBadge('/frontend/meta-tags-generator', l['meta-tags-generator'], l) },
        { key: '/frontend/keyframe-generator', icon: <LineChartOutlined />, label: withNewBadge('/frontend/keyframe-generator', l['keyframe-generator'], l) },
        { key: '/frontend/clip-path-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/clip-path-generator', l['clip-path-generator'], l) },
        { key: '/frontend/scrollbar-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/scrollbar-generator', l['scrollbar-generator'], l) },
        { key: '/frontend/css-to-js', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-to-js', l['css-to-js'], l) },
        { key: '/frontend/clamp-generator', icon: <FontSizeOutlined />, label: withNewBadge('/frontend/clamp-generator', l['clamp-generator'], l) },
      ],
    },
    {
      key: 'group-apis',
      icon: <ApiOutlined />,
      label: l.apis,
      children: [
        { key: '/apis/curl-generator', label: l['curl-generator'] },
        { key: '/apis/curl-to-code', icon: <CodeOutlined />, label: withNewBadge('/apis/curl-to-code', l['curl-to-code'], l) },
        { key: '/apis/webhook-payload-generator', label: withNewBadge('/apis/webhook-payload-generator', l['webhook-payload-generator'], l) },
      ],
    },
    {
      key: 'group-devops',
      icon: <ToolOutlined />,
      label: l.devops,
      children: [
        { key: '/devops/gitignore-generator', label: l['gitignore-generator'] },
        { key: '/devops/commit-message-generator', label: withNewBadge('/devops/commit-message-generator', l['commit-message-generator'], l) },
        { key: '/devops/changelog-generator', icon: <HistoryOutlined />, label: withNewBadge('/devops/changelog-generator', l['changelog-generator'], l) },
        { key: '/devops/env-tool', icon: <FileProtectOutlined />, label: withNewBadge('/devops/env-tool', l['env-tool'], l) },
        { key: '/devops/branch-name-generator', icon: <BranchesOutlined />, label: withNewBadge('/devops/branch-name-generator', l['branch-name-generator'], l) },
        { key: '/devops/kubectl-commands', icon: <ClusterOutlined />, label: withNewBadge('/devops/kubectl-commands', l['kubectl-commands'], l) },
        { key: '/devops/chmod-calculator', icon: <SafetyCertificateOutlined />, label: withNewBadge('/devops/chmod-calculator', l['chmod-calculator'], l) },
        { key: '/devops/dockerfile-generator', icon: <ContainerOutlined />, label: withNewBadge('/devops/dockerfile-generator', l['dockerfile-generator'], l) },
        { key: '/devops/caddyfile-generator', icon: <ContainerOutlined />, label: withNewBadge('/devops/caddyfile-generator', l['caddyfile-generator'], l) },
        { key: '/devops/docker-compose-generator', icon: <ContainerOutlined />, label: withNewBadge('/devops/docker-compose-generator', l['docker-compose-generator'], l) },
        { key: '/devops/ansi-colors', icon: <BgColorsOutlined />, label: withNewBadge('/devops/ansi-colors', l['ansi-colors'], l) },
        { key: '/devops/openssl-commands', icon: <ContainerOutlined />, label: withNewBadge('/devops/openssl-commands', l['openssl-commands'], l) },
        { key: '/devops/sla-calculator', icon: <ExperimentOutlined />, label: withNewBadge('/devops/sla-calculator', l['sla-calculator'], l) },
      ],
    },
    {
      key: 'group-database',
      icon: <DatabaseOutlined />,
      label: l.database,
      children: [
        { key: '/database/rate-limit-calculator', label: l['rate-limit-calculator'] },
        { key: '/database/json-to-sql', icon: <DatabaseOutlined />, label: withNewBadge('/database/json-to-sql', l['json-to-sql'], l) },
        { key: '/database/sql-formatter', icon: <FileTextOutlined />, label: withNewBadge('/database/sql-formatter', l['sql-formatter'], l) },
      ],
    },
    {
      key: 'group-cloud',
      icon: <CloudOutlined />,
      label: l.cloud,
      children: [
        { key: '/cloud/arn-parser', label: l['arn-parser'] },
      ],
    },
    {
      key: 'group-security',
      icon: <SafetyCertificateOutlined />,
      label: l.security,
      children: [
        { key: '/security/password-strength', label: l['password-strength'] },
        { key: '/security/robots-txt-generator', label: withNewBadge('/security/robots-txt-generator', l['robots-txt-generator'], l) },
        { key: '/security/csp-generator', label: withNewBadge('/security/csp-generator', l['csp-generator'], l) },
      ],
    },
    {
      key: 'group-data',
      icon: <FolderOutlined />,
      label: l.data,
      children: [
        { key: '/data/json-tree-viewer', label: l['json-tree-viewer'] },
        { key: '/data/csv-json-converter', label: withNewBadge('/data/csv-json-converter', l['csv-json-converter'], l) },
        { key: '/data/fake-data-generator', label: withNewBadge('/data/fake-data-generator', l['fake-data-generator'], l) },
        { key: '/data/json-diff', label: withNewBadge('/data/json-diff', l['json-diff'], l) },
        { key: '/data/json-path-explorer', label: withNewBadge('/data/json-path-explorer', l['json-path-explorer'], l) },
        { key: '/data/json-schema-generator', icon: <CodeOutlined />, label: withNewBadge('/data/json-schema-generator', l['json-schema-generator'], l) },
        { key: '/data/json-schema-validator', icon: <CodeOutlined />, label: withNewBadge('/data/json-schema-validator', l['json-schema-validator'], l) },
        { key: '/data/csv-markdown-table', icon: <TableOutlined />, label: withNewBadge('/data/csv-markdown-table', l['csv-markdown-table'], l) },
        { key: '/data/json-to-typescript', icon: <CodeOutlined />, label: withNewBadge('/data/json-to-typescript', l['json-to-typescript'], l) },
        { key: '/data/json-to-yaml', icon: <CodeOutlined />, label: withNewBadge('/data/json-to-yaml', l['json-to-yaml'], l) },
      ],
    },
    {
      key: 'group-network',
      icon: <GlobalOutlined />,
      label: l.network,
      children: [
        { key: '/network/subnet-calculator', label: l['subnet-calculator'] },
        { key: '/network/user-agent-parser', icon: <UserOutlined />, label: withNewBadge('/network/user-agent-parser', l['user-agent-parser'], l) },
        { key: '/network/mime-lookup', icon: <InboxOutlined />, label: withNewBadge('/network/mime-lookup', l['mime-lookup'], l) },
        { key: '/network/common-ports', icon: <GlobalOutlined />, label: withNewBadge('/network/common-ports', l['common-ports'], l) },
        { key: '/network/ipv6-explorer', icon: <GlobalOutlined />, label: withNewBadge('/network/ipv6-explorer', l['ipv6-explorer'], l) },
      ],
    },
    {
      key: 'group-ai',
      icon: <RobotOutlined />,
      label: l.ai,
      children: [
        { key: '/ai/anthropic-cost-calculator', label: l['anthropic-cost-calculator'] },
        { key: '/ai/token-counter', label: withNewBadge('/ai/token-counter', l['token-counter'], l) },
      ],
    },
    {
      key: 'group-mobile',
      icon: <MobileOutlined />,
      label: l.mobile,
      children: [
        { key: '/mobile/deep-link-tester', label: l['deep-link-tester'] },
      ],
    },
    {
      key: 'group-text',
      icon: <FontSizeOutlined />,
      label: l.text,
      children: [
        { key: '/text/word-counter', label: l['word-counter'] },
        { key: '/text/remove-accents', icon: <FontSizeOutlined />, label: withNewBadge('/text/remove-accents', l['remove-accents'], l) },
        { key: '/text/lines-tool', icon: <OrderedListOutlined />, label: withNewBadge('/text/lines-tool', l['lines-tool'], l) },
      ],
    },
    {
      key: 'group-references',
      icon: <ReadOutlined />,
      label: l.references,
      children: [
        { key: '/references/git-commands', label: l['git-commands'] },
        { key: '/references/http-status-codes', label: withNewBadge('/references/http-status-codes', l['http-status-codes'], l) },
        { key: '/references/docker-commands', label: withNewBadge('/references/docker-commands', l['docker-commands'], l) },
        { key: '/references/flexbox-cheatsheet', label: withNewBadge('/references/flexbox-cheatsheet', l['flexbox-cheatsheet'], l) },
        { key: '/references/sql-commands', label: withNewBadge('/references/sql-commands', l['sql-commands'], l) },
        { key: '/references/package-manager-commands', label: withNewBadge('/references/package-manager-commands', l['package-manager-commands'], l) },
        { key: '/references/vscode-shortcuts', label: withNewBadge('/references/vscode-shortcuts', l['vscode-shortcuts'], l) },
        { key: '/references/css-grid-cheatsheet', label: withNewBadge('/references/css-grid-cheatsheet', l['css-grid-cheatsheet'], l) },
        { key: '/references/bash-shortcuts', label: withNewBadge('/references/bash-shortcuts', l['bash-shortcuts'], l) },
        { key: '/references/http-methods', label: withNewBadge('/references/http-methods', l['http-methods'], l) },
        { key: '/references/markdown-syntax', icon: <FileMarkdownOutlined />, label: withNewBadge('/references/markdown-syntax', l['markdown-syntax'], l) },
        { key: '/references/html-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/html-cheatsheet', l['html-cheatsheet'], l) },
        { key: '/references/ascii-table', icon: <FontSizeOutlined />, label: withNewBadge('/references/ascii-table', l['ascii-table'], l) },
        { key: '/references/regex-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/regex-cheatsheet', l['regex-cheatsheet'], l) },
        { key: '/references/http-headers', icon: <SendOutlined />, label: withNewBadge('/references/http-headers', l['http-headers'], l) },
        { key: '/references/javascript-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/javascript-cheatsheet', l['javascript-cheatsheet'], l) },
        { key: '/references/tmux-cheatsheet', icon: <ColumnWidthOutlined />, label: withNewBadge('/references/tmux-cheatsheet', l['tmux-cheatsheet'], l) },
        { key: '/references/devtools-shortcuts', icon: <CodeOutlined />, label: withNewBadge('/references/devtools-shortcuts', l['devtools-shortcuts'], l) },
        { key: '/references/vim-cheatsheet', icon: <ColumnWidthOutlined />, label: withNewBadge('/references/vim-cheatsheet', l['vim-cheatsheet'], l) },
        { key: '/references/ssh-cheatsheet', icon: <SafetyCertificateOutlined />, label: withNewBadge('/references/ssh-cheatsheet', l['ssh-cheatsheet'], l) },
        { key: '/references/python-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/python-cheatsheet', l['python-cheatsheet'], l) },
        { key: '/references/grep-sed-awk', icon: <ColumnWidthOutlined />, label: withNewBadge('/references/grep-sed-awk', l['grep-sed-awk'], l) },
        { key: '/references/jq-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/jq-cheatsheet', l['jq-cheatsheet'], l) },
        { key: '/references/bash-scripting', icon: <CodeOutlined />, label: l['bash-scripting'] },
        { key: '/references/systemd-commands', icon: <ContainerOutlined />, label: withNewBadge('/references/systemd-commands', l['systemd-commands'], l) },
        { key: '/references/github-actions-cheatsheet', icon: <GithubOutlined />, label: withNewBadge('/references/github-actions-cheatsheet', l['github-actions-cheatsheet'], l) },
        { key: '/references/nginx-cheatsheet', icon: <GlobalOutlined />, label: withNewBadge('/references/nginx-cheatsheet', l['nginx-cheatsheet'], l) },
        { key: '/references/redis-commands', icon: <DatabaseOutlined />, label: withNewBadge('/references/redis-commands', l['redis-commands'], l) },
        { key: '/references/gh-cli-cheatsheet', icon: <GithubOutlined />, label: withNewBadge('/references/gh-cli-cheatsheet', l['gh-cli-cheatsheet'], l) },
        { key: '/references/typescript-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/typescript-cheatsheet', l['typescript-cheatsheet'], l) },
        { key: '/references/js-testing-cheatsheet', icon: <ExperimentOutlined />, label: withNewBadge('/references/js-testing-cheatsheet', l['js-testing-cheatsheet'], l) },
        { key: '/references/react-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/react-cheatsheet', l['react-cheatsheet'], l) },
      ],
    },
    {
      key: 'group-extras',
      icon: <CalendarOutlined />,
      label: l.extras,
      children: [
        { key: '/extras/days-until', label: l['days-until'] },
        { key: '/extras/team-roulette', label: withNewBadge('/extras/team-roulette', l['team-roulette'], l) },
        { key: '/extras/pomodoro-timer', icon: <FieldTimeOutlined />, label: withNewBadge('/extras/pomodoro-timer', l['pomodoro-timer'], l) },
        { key: '/extras/uuid-collision-simulator', icon: <ExperimentOutlined />, label: withNewBadge('/extras/uuid-collision-simulator', l['uuid-collision-simulator'], l) },
        { key: '/extras/sorting-visualizer', icon: <OrderedListOutlined />, label: withNewBadge('/extras/sorting-visualizer', l['sorting-visualizer'], l) },
      ],
    },
  ]
}

const MOBILE_MENU_OPEN_KEYS = [
  'group-tools', 'group-styles', 'group-snippets', 'group-frontend', 'group-apis',
  'group-devops', 'group-database', 'group-cloud', 'group-security', 'group-data',
  'group-network', 'group-ai', 'group-mobile', 'group-text', 'group-references', 'group-extras',
]

export default function AppLayout() {
  const [collapsed, setCollapsed] = useState(false)
  const [mobileNavOpen, setMobileNavOpen] = useState(false)
  const navigate = useNavigate()
  const location = useLocation()
  const { lang, setLang } = useLanguage()
  const { token: { colorBgContainer, borderRadiusLG } } = theme.useToken()
  const contentRef = useRef(null)
  // Abaixo de 768px o Sider fixo não cabe — vira um Drawer sobreposto,
  // aberto só sob demanda pelo botão de hambúrguer do header.
  const isMobile = useMediaQuery('(max-width: 768px)')

  // Sincroniza NEW_ITEM_KEYS com os 24 itens mais recentes (ver
  // useNewItemKeys.js) antes de montar o menu — não precisamos do valor de
  // retorno aqui, só que o efeito rode e force este componente (e a
  // HomePage, filha dele) a re-renderizar quando os dados chegarem.
  useNewItemKeys()

  const menuItems = buildMenuItems(LABELS[lang])

  // O menu (Sider/Drawer) e o conteúdo rolam em containers separados — ao
  // trocar de rota, o scroll do conteúdo precisa voltar pro topo mesmo que o
  // menu continue rolado onde o usuário clicou. No mobile, a troca de rota
  // também fecha o drawer de navegação sozinha.
  useEffect(() => {
    contentRef.current?.scrollTo(0, 0)
    setMobileNavOpen(false)
  }, [location.pathname])

  const handleMenuClick = ({ key }) => {
    if (key.startsWith('/')) navigate(key)
  }

  const navMenu = (
    <Menu
      theme="dark"
      mode="inline"
      selectedKeys={[location.pathname]}
      defaultOpenKeys={MOBILE_MENU_OPEN_KEYS}
      items={menuItems}
      onClick={handleMenuClick}
    />
  )

  return (
    <Layout style={{ height: '100vh' }}>
      {isMobile ? (
        <Drawer
          placement="left"
          closable={false}
          onClose={() => setMobileNavOpen(false)}
          open={mobileNavOpen}
          width="min(80vw, 300px)"
          styles={{ body: { padding: 0, background: '#001529' } }}
        >
          <div style={{
            height: 32,
            margin: 16,
            display: 'flex',
            alignItems: 'center',
            color: '#fff',
            fontWeight: 700,
          }}>
            DevTools
          </div>
          {navMenu}
        </Drawer>
      ) : (
        <Sider trigger={null} collapsible collapsed={collapsed} style={{ height: '100vh', overflow: 'auto' }}>
          <div style={{
            height: 32,
            margin: 16,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: '#fff',
            fontWeight: 700,
            overflow: 'hidden',
            whiteSpace: 'nowrap',
          }}>
            {collapsed ? 'DT' : 'DevTools'}
          </div>
          {navMenu}
        </Sider>
      )}
      <Layout style={{ height: '100vh' }}>
        <Header style={{
          padding: '0 12px',
          background: colorBgContainer,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: 8,
        }}>
          {React.createElement(
            isMobile ? MenuUnfoldOutlined : (collapsed ? MenuUnfoldOutlined : MenuFoldOutlined),
            {
              onClick: () => (isMobile ? setMobileNavOpen(true) : setCollapsed(!collapsed)),
              style: { fontSize: 18, cursor: 'pointer', padding: 8, margin: -8 },
            }
          )}
          <Segmented
            value={lang}
            onChange={setLang}
            options={[
              { label: 'PT', value: 'pt' },
              { label: 'EN', value: 'en' },
            ]}
          />
        </Header>
        <Content style={{
          margin: isMobile ? 12 : 24,
          padding: isMobile ? 12 : 24,
          background: colorBgContainer,
          borderRadius: borderRadiusLG,
          minHeight: 0,
          overflow: 'hidden',
          display: 'flex',
          flexDirection: 'column',
        }}>
          <div ref={contentRef} style={{ overflow: 'auto', flex: 1 }}>
            <Outlet />
          </div>
        </Content>
      </Layout>
      <BugReportWidget />
    </Layout>
  )
}
