import React, { useEffect, useRef, useState } from 'react'
import { Layout, Menu, Segmented, Tag, theme, Drawer } from 'antd'
import {
  HomeOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  MenuOutlined,
  ToolOutlined,
  CompressOutlined,
  BgColorsOutlined,
  CodeOutlined,
  KeyOutlined,
  FieldTimeOutlined,
  NumberOutlined,
  FileTextOutlined,
  ApiOutlined,
  DatabaseOutlined,
  CloudOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  FolderOutlined,
  GlobalOutlined,
  RobotOutlined,
  MobileOutlined,
  FontSizeOutlined,
  ReadOutlined,
  CalendarOutlined,
  SearchOutlined,
  SwapOutlined,
  IdcardOutlined,
  DiffOutlined,
  FileMarkdownOutlined,
  BranchesOutlined,
  CalculatorOutlined,
  LinkOutlined,
  ColumnWidthOutlined,
  OrderedListOutlined,
  FileProtectOutlined,
  ExperimentOutlined,
  UserOutlined,
  InboxOutlined,
  TableOutlined,
  ClusterOutlined,
  TeamOutlined,
  PictureOutlined,
  ContainerOutlined,
  LineChartOutlined,
  PercentageOutlined,
  SendOutlined,
  HistoryOutlined,
  ClockCircleOutlined,
  CreditCardOutlined,
  QrcodeOutlined,
  BarcodeOutlined,
  GithubOutlined,
  AudioOutlined,
  SelectOutlined,
  AppstoreOutlined,
  LoadingOutlined,
  LockOutlined,
  EyeOutlined,
  PicCenterOutlined,
  PartitionOutlined,
  LayoutOutlined,
  SlidersOutlined,
  StarOutlined,
  DownOutlined,
  SmileOutlined,
  EditOutlined,
  WarningOutlined,
  ThunderboltOutlined,
  EnvironmentOutlined,
  BankOutlined,
  SoundOutlined,
} from '@ant-design/icons'
import { Outlet, useNavigate, useLocation } from 'react-router-dom'
import { useLanguage } from '../i18n/LanguageContext'
import { NEW_ITEM_KEYS } from '../newItems'
import { useNewItemKeys } from '../hooks/useNewItemKeys'
import useMediaQuery from '../hooks/useMediaQuery'
import useVisitTracker from '../hooks/useVisitTracker'
import BugReportWidget from './BugReportWidget'

const { Header, Sider, Content } = Layout

// Labels do menu por idioma — rótulos apenas, a lista de rotas/ícones fica
// fixa abaixo. Rodadas futuras do agente: ao adicionar uma página nova,
// adicione o par pt/en aqui também.
export const LABELS = {
  pt: {
    home: 'Home',
    bastidores: 'Bastidores',
    tools: 'Ferramentas',
    styles: 'Estilos',
    snippets: 'Snippets',
    frontend: 'Front-end',
    apis: 'APIs',
    devops: 'DevOps',
    database: 'Banco de Dados',
    cloud: 'Cloud',
    security: 'Segurança',
    data: 'Arquivos & Dados',
    network: 'Rede',
    ai: 'IA',
    mobile: 'Mobile',
    text: 'Texto',
    references: 'Referências',
    extras: 'Fora da caixa',
    new: 'Novo',
    'jwt-decoder': 'Decodificador JWT',
    'cron-parser': 'Explicador de Cron',
    'hash-generator': 'Gerador de Hash',
    'json-formatter': 'Formatador de JSON',
    'color-converter': 'Conversor de Cor',
    'timestamp-converter': 'Conversor de Timestamp',
    'glass-card': 'Glass Card',
    'copy-button': 'Botão de Copiar Animado',
    'skeleton-shimmer': 'Skeleton Shimmer',
    'spotlight-card': 'Spotlight Card',
    'gradient-border-button': 'Botão com Borda Gradiente',
    'use-debounce': 'useDebounce',
    'use-local-storage': 'useLocalStorage',
    'use-session-storage': 'useSessionStorage',
    'use-click-outside': 'useClickOutside',
    'use-media-query': 'useMediaQuery',
    'contrast-checker': 'Checador de Contraste',
    'curl-generator': 'Gerador de cURL',
    'curl-to-code': 'cURL → Código (fetch/axios)',
    'gitignore-generator': 'Gerador de .gitignore',
    'gitattributes-generator': 'Gerador de .gitattributes',
    'rate-limit-calculator': 'Calculadora de Rate Limit',
    'arn-parser': 'AWS ARN Parser',
    'password-strength': 'Força de Senha',
    'json-tree-viewer': 'Visualizador de Árvore JSON',
    'subnet-calculator': 'Calculadora de Sub-rede',
    'anthropic-cost-calculator': 'Calculadora de Custo Anthropic',
    'deep-link-tester': 'Testador de Deep Link',
    'word-counter': 'Contador de Palavras',
    'git-commands': 'Comandos Git',
    'days-until': 'Quantos dias até...',
    'date-time-calculator': 'Calculadora de Data e Hora',
    'regex-tester': 'Regex Tester',
    'keyboard-event-tester': 'Testador de Eventos de Teclado',
    'base64-tool': 'Base64 Encode/Decode',
    'uuid-generator': 'Gerador de UUID',
    'uuid-v7-generator': 'Gerador / Decoder de UUID v7',
    'ulid-tool': 'ULID Generator / Decoder',
    'case-converter': 'Conversor de Case',
    'password-generator': 'Gerador de Senha',
    'payload-compression-calculator': 'Calculadora de Compressão de Payload',
    'url-email-extractor': 'Extrator de URLs e E-mails',
    'passphrase-generator': 'Gerador de Passphrase',
    'totp-generator': 'Gerador de TOTP (2FA)',
    'url-encoder': 'URL Encode/Decode',
    'url-parser': 'URL Parser & Query Editor',
    'xml-json-converter': 'Conversor XML ↔ JSON',
    'gradient-generator': 'Gerador de Gradiente CSS',
    'use-copy-to-clipboard': 'useCopyToClipboard',
    'http-status-codes': 'HTTP Status Codes',
    'diff-checker': 'Comparador de Texto (Diff)',
    'box-shadow-generator': 'Gerador de Box Shadow',
    'csv-json-converter': 'Conversor CSV ↔ JSON',
    'use-interval': 'useInterval',
    'use-timeout': 'useTimeout',
    'use-countdown': 'useCountdown',
    'use-fetch': 'useFetch',
    'markdown-previewer': 'Markdown → HTML (Preview)',
    'neumorphic-card': 'Cartão Neumórfico',
    'use-previous': 'usePrevious',
    'fake-data-generator': 'Gerador de Dados Fake',
    'webhook-payload-generator': 'Gerador de Payload de Webhook',
    'cpf-cnpj-generator': 'Gerador de CPF/CNPJ',
    'base-converter': 'Conversor de Base Numérica',
    'use-toggle': 'useToggle',
    'use-window-size': 'useWindowSize',
    'bouncing-dots-loader': 'Loading de Dots Saltitantes',
    'docker-commands': 'Comandos Docker',
    'semver-comparator': 'Comparador de SemVer',
    'slug-generator': 'Gerador de Slug',
    'palette-generator': 'Gerador de Paleta de Cores',
    'ripple-button': 'Botão com Efeito Ripple',
    'use-on-screen': 'useOnScreen',
    'flexbox-cheatsheet': 'Cheat Sheet de Flexbox',
    'css-unit-converter': 'Conversor de Unidades CSS',
    'aspect-ratio-calculator': 'Calculadora de Proporção (Aspect Ratio)',
    'css-specificity-calculator': 'Calculadora de Especificidade CSS',
    'css-selector-tester': 'Testador de Seletores CSS',
    'floating-label-input': 'Input com Label Flutuante',
    'use-key-press': 'useKeyPress',
    'sql-commands': 'Comandos SQL',
    'nanoid-generator': 'Gerador de NanoID',
    'html-entity-encoder': 'HTML Entity Encode/Decode',
    'border-radius-generator': 'Gerador de Border Radius',
    'ios-toggle-switch': 'Switch Estilo iOS',
    'use-event-listener': 'useEventListener',
    'package-manager-commands': 'npm vs yarn vs pnpm',
    'hmac-generator': 'Gerador de HMAC',
    'lorem-ipsum-generator': 'Gerador de Lorem Ipsum',
    'json-diff': 'JSON Diff',
    'dark-mode-toggle': 'Dark Mode Toggle',
    'use-throttle': 'useThrottle',
    'vscode-shortcuts': 'Atalhos VSCode',
    'json-path-explorer': 'JSON Path Explorer',
    'css-grid-cheatsheet': 'Cheat Sheet de CSS Grid',
    'fisher-yates-shuffle': 'Fisher-Yates Shuffle',
    'team-roulette': 'Roleta de Sorteio',
    'jwt-generator': 'Gerador de JWT',
    'jwt-secret-generator': 'Gerador de Secret JWT',
    'toast-notification': 'Toast com Auto-Dismiss',
    'use-undo': 'useUndo',
    'use-network-status': 'useNetworkStatus',
    'use-element-size': 'useElementSize',
    'use-mouse-position': 'useMousePosition',
    'use-page-visibility': 'usePageVisibility',
    'use-async': 'useAsync',
    'use-update-effect': 'useUpdateEffect',
    'use-why-did-you-update': 'useWhyDidYouUpdate',
    'use-boolean': 'useBoolean',
    'use-set': 'useSet',
    'use-counter': 'useCounter',
    'use-lock-body-scroll': 'useLockBodyScroll',
    'use-stable-callback': 'useStableCallback',
    'use-hover': 'useHover',
    'use-merged-ref': 'useMergedRef',
    'use-queue': 'useQueue',
    'use-long-press': 'useLongPress',
    'use-form': 'useForm',
    'use-preferred-color-scheme': 'usePreferredColorScheme',
    'use-favicon': 'useFavicon',
    'use-document-title': 'useDocumentTitle',
    'use-list': 'useList',
    'use-map': 'useMap',
    'use-state-with-history': 'useStateWithHistory',
    'use-window-focus': 'useWindowFocus',
    'use-before-unload': 'useBeforeUnload',
    'use-count-up': 'useCountUp',
    'use-script': 'useScript',
    'use-battery': 'useBattery',
    'use-geolocation': 'useGeolocation',
    'use-idle': 'useIdle',
    'use-mutation-observer': 'useMutationObserver',
    'use-resize-observer': 'useResizeObserver',
    'use-hotkeys': 'useHotkeys',
    'use-speech-synthesis': 'useSpeechSynthesis',
    'use-pagination': 'usePagination',
    'use-controllable-state': 'useControllableState',
    'typing-speed-test': 'Teste de Velocidade de Digitação',
    'bash-shortcuts': 'Atalhos de Terminal/Bash',
    'commit-message-generator': 'Gerador de Mensagem de Commit',
    'robots-txt-generator': 'Gerador de robots.txt',
    'scroll-progress-bar': 'Indicador de Progresso de Scroll',
    'confetti-effect': 'Efeito de Confete',
    'debounce-throttle-functions': 'debounce/throttle (função)',
    'jwt-timeline': 'Timeline de Expiração do JWT',
    'typewriter-effect': 'Efeito de Máquina de Escrever',
    'lru-cache': 'LRU Cache',
    'csp-generator': 'Gerador de CSP',
    'security-headers-generator': 'Gerador de Cabeçalhos de Segurança',
    'sri-hash-generator': 'Gerador de Hash SRI',
    'security-txt-generator': 'Gerador de security.txt',
    'webhook-signature-validator': 'Validador de Assinatura de Webhook',
    'asymmetric-key-generator': 'Gerador de Par de Chaves Assimétricas',
    'token-counter': 'Contador de Tokens',
    'pomodoro-timer': 'Timer Pomodoro',
    'env-tool': 'Validador de .env',
    'remove-accents': 'Remover Acentos',
    'xml-formatter': 'Formatador de XML',
    'deep-clone-deep-equal': 'deepClone & deepEqual',
    'branch-name-generator': 'Gerador de Nome de Branch',
    'lines-tool': 'Processador de Linhas',
    'html-to-jsx-converter': 'Conversor HTML → JSX',
    'html-to-markdown': 'Conversor HTML → Markdown',
    'uuid-collision-simulator': 'Simulador de Colisão de UUID',
    'unicode-inspector': 'Inspetor de Unicode',
    'json-to-sql': 'JSON → SQL INSERT',
    'sorting-visualizer': 'Visualizador de Ordenação',
    'otp-input': 'Input OTP (código de verificação)',
    'timezone-converter': 'Conversor de Fuso Horário',
    'user-agent-parser': 'Parser de User-Agent',
    'cron-builder': 'Construtor de Cron',
    'mime-lookup': 'Lookup de MIME Types',
    'http-methods': 'Métodos HTTP',
    'number-to-words': 'Número por Extenso',
    'json-schema-generator': 'Gerador de JSON Schema',
    'json-schema-validator': 'Validador de JSON Schema',
    'css-formatter': 'Formatador de CSS',
    'sql-formatter': 'Formatador de SQL',
    'common-ports': 'Portas de Rede Comuns',
    'ipv6-explorer': 'Explorador IPv6',
    'mac-address-tool': 'Gerador/Validador de MAC',
    'iban-tool': 'Gerador/Validador de IBAN',
    'roman-numeral-converter': 'Conversor de Números Romanos',
    'file-size-converter': 'Conversor de Tamanho de Arquivo',
    'file-hash-calculator': 'Calculadora de Hashes de Arquivo',
    'geo-coordinates-converter': 'Conversor de Coordenadas',
    'levenshtein-calculator': 'Calculadora de Levenshtein',
    'bandwidth-calculator': 'Calculadora de Largura de Banda',
    'cookie-tool': 'Analisador / Builder de Cookies',
    'compound-interest-calculator': 'Calculadora de Juros Compostos',
    'percentage-calculator': 'Calculadora de Porcentagem',
    'sql-joins': 'Visualizador de JOINs SQL',
    'csv-markdown-table': 'CSV → Tabela Markdown',
    'markdown-syntax': 'Sintaxe Markdown',
    'kubectl-commands': 'Comandos kubectl',
    'chmod-calculator': 'Calculadora de Permissões (chmod)',
    'float-explorer': 'Explorador de Float (IEEE-754)',
    'svg-placeholder-generator': 'Gerador de Placeholder SVG',
    'dockerfile-generator': 'Gerador de Dockerfile',
    'cubic-bezier-editor': 'Editor de Curva de Easing',
    'ansi-colors': 'Cores ANSI (terminal)',
    'ascii-table': 'Tabela ASCII',
    'svg-wave-generator': 'Gerador de Onda SVG',
    'css-filter-generator': 'Gerador de Filtros CSS',
    'keyframe-generator': 'Gerador de Keyframes',
    'meta-tags-generator': 'Gerador de Meta Tags (SEO/OG)',
    'clip-path-generator': 'Gerador de clip-path (Polygon)',
    'toml-formatter': 'Formatador de TOML',
    'regex-cheatsheet': 'Cheat Sheet de Regex',
    'crc-calculator': 'Calculadora de CRC',
    'json-to-typescript': 'JSON → TypeScript',
    'json-to-yaml': 'JSON → YAML',
    'json-flatten': 'JSON Flatten & Unflatten',
    'caddyfile-generator': 'Gerador de Caddyfile',
    'htaccess-generator': 'Gerador de .htaccess',
    'docker-compose-generator': 'Gerador de docker-compose',
    'openssl-commands': 'Comandos OpenSSL',
    'units-converter': 'Conversor de Unidades',
    'http-headers': 'Cabeçalhos HTTP',
    'javascript-cheatsheet': 'Cheat Sheet de JavaScript (ES6+)',
    'tmux-cheatsheet': 'Comandos tmux',
    'devtools-shortcuts': 'Atalhos do DevTools',
    'vim-cheatsheet': 'Comandos Vim',
    'ssh-cheatsheet': 'Comandos SSH',
    'python-cheatsheet': 'Cheat Sheet de Python',
    'grep-sed-awk': 'grep/sed/awk',
    'jq-cheatsheet': 'Comandos jq',
    'changelog-generator': 'Gerador de Changelog',
    'scrollbar-generator': 'Gerador de Scrollbar CSS',
    'bash-scripting': 'Scripts em Bash (shell scripting)',
    'systemd-commands': 'Comandos systemd',
    'sla-calculator': 'Calculadora de SLA (downtime)',
    'credit-card-tool': 'Gerador/Validador de Cartão (Luhn)',
    'qr-code-generator': 'Gerador de QR Code',
    'barcode-generator': 'Gerador de Código de Barras',
    'html-formatter': 'Formatador de HTML',
    'github-actions-cheatsheet': 'GitHub Actions (workflows)',
    'css-to-js': 'CSS ↔ JS (style object)',
    'nginx-cheatsheet': 'Cheat Sheet de Nginx',
    'redis-commands': 'Comandos Redis',
    'gh-cli-cheatsheet': 'GitHub CLI (gh)',
    'typescript-cheatsheet': 'Cheat Sheet de TypeScript',
    'clamp-generator': 'Tipografia Fluida (clamp)',
    'css-triangle-generator': 'Gerador de Triângulo CSS',
    'font-face-generator': 'Gerador de @font-face CSS',
    'morse-code-converter': 'Conversor de Código Morse',
    'glob-tester': 'Glob Pattern Tester (gitignore)',
    'data-uri-tool': 'Data URI Generator / Decoder',
    'directory-tree-generator': 'Gerador de Árvore de Diretórios',
    'html-cheatsheet': 'Cheat Sheet de HTML',
    'js-testing-cheatsheet': 'Cheat Sheet de Testes JS (Jest/Vitest)',
    'react-cheatsheet': 'Cheat Sheet de React',
    'tailwind-cheatsheet': 'Cheat Sheet de Tailwind CSS',
    'css-selectors-cheatsheet': 'Cheat Sheet de Seletores CSS',
    'a11y-cheatsheet': 'Cheat Sheet de Acessibilidade (a11y)',
    'jwt-claims-cheatsheet': 'Cheat Sheet de Claims JWT',
    'grid-areas-generator': 'Gerador de Grid Areas CSS',
    'pattern-background-generator': 'Gerador de Padrões de Fundo CSS',
    'sitemap-generator': 'Gerador de Sitemap XML',
    'web-app-manifest': 'Gerador de Web App Manifest',
    'editorconfig-generator': 'Gerador de .editorconfig',
    'codeowners-generator': 'Gerador de CODEOWNERS',
    'license-generator': 'Gerador de LICENSE',
    'dockerignore-generator': 'Gerador de .dockerignore',
    'prettierrc-generator': 'Gerador de .prettierrc',
    'makefile-generator': 'Gerador de Makefile',
    'tsconfig-generator': 'Gerador de tsconfig.json',
    'css-spinner-generator': 'Gerador de Loading Spinner CSS',
    'color-blindness-simulator': 'Simulador de Daltonismo',
    'text-shadow-generator': 'Gerador de Text Shadow',
    'transform-generator': 'Gerador de Transform CSS',
    'container-query-generator': 'Gerador de Container Queries CSS',
    'scroll-snap-generator': 'Gerador de Scroll Snap CSS',
    'css-transition-generator': 'Gerador de CSS Transition',
    'css-tooltip-generator': 'Gerador de Tooltip CSS',
    'gradient-text-generator': 'Gerador de Texto Gradiente CSS',
    'custom-properties-generator': 'Gerador de CSS Custom Properties',
    'css-columns-generator': 'Gerador de CSS Columns (Multicol)',
    'css-breadcrumbs-generator': 'Gerador de Breadcrumbs CSS',
    'css-tabs-generator': 'Gerador de Tabs CSS',
    'css-progress-bar-generator': 'Gerador de Progress Bar CSS',
    'css-modal-generator': 'Gerador de Modal/Dialog CSS',
    'css-accordion-generator': 'Gerador de Accordion CSS',
    'css-range-slider-generator': 'Gerador de Range Slider CSS',
    'css-star-rating-generator': 'Gerador de Star Rating CSS',
    'css-glassmorphism-generator': 'Gerador de Glassmorphism CSS',
    'css-toggle-switch-generator': 'Gerador de Toggle Switch CSS',
    'css-custom-checkbox-generator': 'Gerador de Checkbox CSS',
    'css-radio-button-generator': 'Gerador de Radio Button CSS',
    'css-chip-generator': 'Gerador de Chip/Badge CSS',
    'css-pagination-generator': 'Gerador de Paginação CSS',
    'css-card-generator': 'Gerador de Card CSS',
    'css-dropdown-menu-generator': 'Gerador de Dropdown Menu CSS',
    'css-skeleton-generator': 'Gerador de Skeleton CSS',
    'css-timeline-generator': 'Gerador de Timeline CSS',
    'css-stepper-generator': 'Gerador de Stepper/Wizard CSS',
    'css-speech-bubble-generator': 'Gerador de Speech Bubble CSS',
    'css-button-generator': 'Gerador de Button CSS',
    'css-alert-generator': 'Gerador de Alert CSS',
    'css-avatar-generator': 'Gerador de Avatar CSS',
    'css-hamburger-menu-generator': 'Gerador de Hambúrguer Menu CSS',
    'css-corner-ribbon-generator': 'Gerador de Corner Ribbon CSS',
    'css-pricing-table-generator': 'Gerador de Pricing Table CSS',
    'css-image-hover-generator': 'Gerador de Efeitos de Hover em Imagens CSS',
    'css-segmented-control-generator': 'Gerador de Segmented Control CSS',
    'css-table-generator': 'Gerador de Tabela CSS',
    'css-cursor-generator': 'Gerador de Cursor Personalizado CSS',
    'css-flip-card-generator': 'Gerador de Flip Card CSS',
    'css-progress-ring-generator': 'Gerador de Progress Ring CSS',
    'css-divider-generator': 'Gerador de Divider CSS',
    'svg-badge-generator': 'Gerador de Badge SVG',
    'css-marquee-generator': 'Gerador de Marquee CSS',
    'css-carousel-generator': 'Gerador de Carrossel CSS',
    'css-login-form-generator': 'Gerador de CSS Login Form',
    'css-neumorphism-generator': 'Gerador de Neumorfismo CSS',
    'css-text-stroke-generator': 'Gerador de Texto com Contorno CSS',
    'css-line-clamp-generator': 'Gerador de Line Clamp CSS',
    'css-pulse-generator': 'Gerador de Efeito Pulse CSS',
  },
  en: {
    home: 'Home',
    bastidores: 'Behind the scenes',
    tools: 'Tools',
    styles: 'Styles',
    snippets: 'Snippets',
    frontend: 'Front-end',
    apis: 'APIs',
    devops: 'DevOps',
    database: 'Database',
    cloud: 'Cloud',
    security: 'Security',
    data: 'Files & Data',
    network: 'Network',
    ai: 'AI',
    mobile: 'Mobile',
    text: 'Text',
    references: 'References',
    extras: 'Out of the box',
    new: 'New',
    'jwt-decoder': 'JWT Decoder',
    'cron-parser': 'Cron Expression Explainer',
    'hash-generator': 'Hash Generator',
    'json-formatter': 'JSON Formatter',
    'color-converter': 'Color Converter',
    'timestamp-converter': 'Timestamp Converter',
    'glass-card': 'Glass Card',
    'copy-button': 'Animated Copy Button',
    'skeleton-shimmer': 'Skeleton Shimmer',
    'spotlight-card': 'Spotlight Card',
    'gradient-border-button': 'Gradient Border Button',
    'use-debounce': 'useDebounce',
    'use-local-storage': 'useLocalStorage',
    'use-session-storage': 'useSessionStorage',
    'use-click-outside': 'useClickOutside',
    'use-media-query': 'useMediaQuery',
    'contrast-checker': 'Contrast Checker',
    'curl-generator': 'cURL Generator',
    'curl-to-code': 'cURL → Code (fetch/axios)',
    'gitignore-generator': '.gitignore Generator',
    'gitattributes-generator': '.gitattributes Generator',
    'rate-limit-calculator': 'Rate Limit Calculator',
    'arn-parser': 'AWS ARN Parser',
    'password-strength': 'Password Strength',
    'json-tree-viewer': 'JSON Tree Viewer',
    'subnet-calculator': 'Subnet Calculator',
    'anthropic-cost-calculator': 'Anthropic Cost Calculator',
    'deep-link-tester': 'Deep Link Tester',
    'word-counter': 'Word Counter',
    'git-commands': 'Git Commands',
    'days-until': 'Days Until...',
    'date-time-calculator': 'Date & Time Calculator',
    'regex-tester': 'Regex Tester',
    'keyboard-event-tester': 'Keyboard Event Tester',
    'base64-tool': 'Base64 Encode/Decode',
    'uuid-generator': 'UUID Generator',
    'uuid-v7-generator': 'UUID v7 Generator / Decoder',
    'ulid-tool': 'ULID Generator / Decoder',
    'case-converter': 'Case Converter',
    'password-generator': 'Password Generator',
    'payload-compression-calculator': 'Payload Compression Calculator',
    'url-email-extractor': 'URL & E-mail Extractor',
    'passphrase-generator': 'Passphrase Generator',
    'totp-generator': 'TOTP Generator (2FA)',
    'url-encoder': 'URL Encode/Decode',
    'url-parser': 'URL Parser & Query Editor',
    'xml-json-converter': 'XML ↔ JSON Converter',
    'gradient-generator': 'CSS Gradient Generator',
    'use-copy-to-clipboard': 'useCopyToClipboard',
    'http-status-codes': 'HTTP Status Codes',
    'diff-checker': 'Text Diff Checker',
    'box-shadow-generator': 'Box Shadow Generator',
    'csv-json-converter': 'CSV ↔ JSON Converter',
    'use-interval': 'useInterval',
    'use-timeout': 'useTimeout',
    'use-countdown': 'useCountdown',
    'use-fetch': 'useFetch',
    'markdown-previewer': 'Markdown → HTML (Preview)',
    'neumorphic-card': 'Neumorphic Card',
    'use-previous': 'usePrevious',
    'fake-data-generator': 'Fake Data Generator',
    'webhook-payload-generator': 'Webhook Payload Generator',
    'cpf-cnpj-generator': 'CPF/CNPJ Generator',
    'base-converter': 'Number Base Converter',
    'use-toggle': 'useToggle',
    'use-window-size': 'useWindowSize',
    'bouncing-dots-loader': 'Bouncing Dots Loader',
    'docker-commands': 'Docker Commands',
    'semver-comparator': 'SemVer Comparator',
    'slug-generator': 'Slug Generator',
    'palette-generator': 'Color Palette Generator',
    'ripple-button': 'Ripple Effect Button',
    'use-on-screen': 'useOnScreen',
    'flexbox-cheatsheet': 'Flexbox Cheat Sheet',
    'css-unit-converter': 'CSS Unit Converter',
    'aspect-ratio-calculator': 'Aspect Ratio Calculator',
    'css-specificity-calculator': 'CSS Specificity Calculator',
    'css-selector-tester': 'CSS Selector Tester',
    'floating-label-input': 'Floating Label Input',
    'use-key-press': 'useKeyPress',
    'sql-commands': 'SQL Commands',
    'nanoid-generator': 'NanoID Generator',
    'html-entity-encoder': 'HTML Entity Encode/Decode',
    'border-radius-generator': 'Border Radius Generator',
    'ios-toggle-switch': 'iOS-style Switch',
    'use-event-listener': 'useEventListener',
    'package-manager-commands': 'npm vs yarn vs pnpm',
    'hmac-generator': 'HMAC Generator',
    'lorem-ipsum-generator': 'Lorem Ipsum Generator',
    'json-diff': 'JSON Diff',
    'dark-mode-toggle': 'Dark Mode Toggle',
    'use-throttle': 'useThrottle',
    'vscode-shortcuts': 'VSCode Shortcuts',
    'json-path-explorer': 'JSON Path Explorer',
    'css-grid-cheatsheet': 'CSS Grid Cheat Sheet',
    'fisher-yates-shuffle': 'Fisher-Yates Shuffle',
    'team-roulette': 'Team Roulette',
    'jwt-generator': 'JWT Generator',
    'jwt-secret-generator': 'JWT Secret Generator',
    'toast-notification': 'Toast with Auto-Dismiss',
    'use-undo': 'useUndo',
    'use-network-status': 'useNetworkStatus',
    'use-element-size': 'useElementSize',
    'use-mouse-position': 'useMousePosition',
    'use-page-visibility': 'usePageVisibility',
    'use-async': 'useAsync',
    'use-update-effect': 'useUpdateEffect',
    'use-why-did-you-update': 'useWhyDidYouUpdate',
    'use-boolean': 'useBoolean',
    'use-set': 'useSet',
    'use-counter': 'useCounter',
    'use-lock-body-scroll': 'useLockBodyScroll',
    'use-stable-callback': 'useStableCallback',
    'use-hover': 'useHover',
    'use-merged-ref': 'useMergedRef',
    'use-queue': 'useQueue',
    'use-long-press': 'useLongPress',
    'use-form': 'useForm',
    'use-preferred-color-scheme': 'usePreferredColorScheme',
    'use-favicon': 'useFavicon',
    'use-document-title': 'useDocumentTitle',
    'use-list': 'useList',
    'use-map': 'useMap',
    'use-state-with-history': 'useStateWithHistory',
    'use-window-focus': 'useWindowFocus',
    'use-before-unload': 'useBeforeUnload',
    'use-count-up': 'useCountUp',
    'use-script': 'useScript',
    'use-battery': 'useBattery',
    'use-geolocation': 'useGeolocation',
    'use-idle': 'useIdle',
    'use-mutation-observer': 'useMutationObserver',
    'use-resize-observer': 'useResizeObserver',
    'use-hotkeys': 'useHotkeys',
    'use-speech-synthesis': 'useSpeechSynthesis',
    'use-pagination': 'usePagination',
    'use-controllable-state': 'useControllableState',
    'typing-speed-test': 'Typing Speed Test',
    'bash-shortcuts': 'Terminal/Bash Shortcuts',
    'commit-message-generator': 'Commit Message Generator',
    'robots-txt-generator': 'robots.txt Generator',
    'scroll-progress-bar': 'Scroll Progress Indicator',
    'confetti-effect': 'Confetti Effect',
    'debounce-throttle-functions': 'debounce/throttle (function)',
    'jwt-timeline': 'JWT Expiration Timeline',
    'typewriter-effect': 'Typewriter Effect',
    'lru-cache': 'LRU Cache',
    'csp-generator': 'CSP Generator',
    'security-headers-generator': 'Security Headers Generator',
    'sri-hash-generator': 'SRI Hash Generator',
    'security-txt-generator': 'security.txt Generator',
    'webhook-signature-validator': 'Webhook Signature Validator',
    'asymmetric-key-generator': 'Asymmetric Key Pair Generator',
    'token-counter': 'Token Counter',
    'pomodoro-timer': 'Pomodoro Timer',
    'env-tool': '.env File Validator',
    'remove-accents': 'Remove Accents',
    'xml-formatter': 'XML Formatter',
    'deep-clone-deep-equal': 'deepClone & deepEqual',
    'branch-name-generator': 'Branch Name Generator',
    'lines-tool': 'Lines Tool',
    'html-to-jsx-converter': 'HTML → JSX Converter',
    'html-to-markdown': 'HTML → Markdown Converter',
    'uuid-collision-simulator': 'UUID Collision Simulator',
    'unicode-inspector': 'Unicode Inspector',
    'json-to-sql': 'JSON → SQL INSERT',
    'sorting-visualizer': 'Sorter Visualizer',
    'otp-input': 'OTP Input (verification code)',
    'timezone-converter': 'Timezone Converter',
    'user-agent-parser': 'User-Agent Parser',
    'cron-builder': 'Cron Builder',
    'mime-lookup': 'MIME Types Lookup',
    'http-methods': 'HTTP Methods',
    'number-to-words': 'Number to Words',
    'json-schema-generator': 'JSON Schema Generator',
    'json-schema-validator': 'JSON Schema Validator',
    'css-formatter': 'CSS Formatter',
    'sql-formatter': 'SQL Formatter',
    'common-ports': 'Common Network Ports',
    'ipv6-explorer': 'IPv6 Explorer',
    'mac-address-tool': 'MAC Generator / Validator',
    'iban-tool': 'IBAN Generator / Validator',
    'roman-numeral-converter': 'Roman Numeral Converter',
    'file-size-converter': 'File Size Converter',
    'file-hash-calculator': 'File Hash Calculator',
    'geo-coordinates-converter': 'Geographic Coordinates Converter',
    'levenshtein-calculator': 'Levenshtein Calculator',
    'bandwidth-calculator': 'Bandwidth Calculator',
    'cookie-tool': 'Cookie Parser / Builder',
    'compound-interest-calculator': 'Compound Interest Calculator',
    'percentage-calculator': 'Percentage Calculator',
    'sql-joins': 'SQL JOIN Visualizer',
    'csv-markdown-table': 'CSV → Markdown Table',
    'markdown-syntax': 'Markdown Syntax',
    'kubectl-commands': 'kubectl Commands',
    'chmod-calculator': 'File Permission Calculator (chmod)',
    'float-explorer': 'Float Explorer (IEEE-754)',
    'svg-placeholder-generator': 'SVG Placeholder Generator',
    'dockerfile-generator': 'Dockerfile Generator',
    'cubic-bezier-editor': 'Cubic Bézier Easing Editor',
    'ansi-colors': 'ANSI Colors',
    'ascii-table': 'ASCII Table',
    'svg-wave-generator': 'SVG Wave Generator',
    'css-filter-generator': 'CSS Filter Generator',
    'keyframe-generator': 'Keyframes Generator',
    'meta-tags-generator': 'Meta Tags Generator (SEO/OG)',
    'clip-path-generator': 'clip-path Generator (Polygon)',
    'toml-formatter': 'TOML Formatter',
    'regex-cheatsheet': 'Regex Cheat Sheet',
    'crc-calculator': 'CRC Checksum Calculator',
    'json-to-typescript': 'JSON → TypeScript',
    'json-to-yaml': 'JSON → YAML',
    'json-flatten': 'JSON Flatten & Unflatten',
    'caddyfile-generator': 'Caddyfile Generator',
    'htaccess-generator': '.htaccess Generator',
    'docker-compose-generator': 'docker-compose Generator',
    'openssl-commands': 'OpenSSL Commands',
    'units-converter': 'Units Converter',
    'http-headers': 'HTTP Headers',
    'javascript-cheatsheet': 'JavaScript Cheat Sheet (ES6+)',
    'tmux-cheatsheet': 'tmux Commands',
    'devtools-shortcuts': 'Browser DevTools Shortcuts',
    'vim-cheatsheet': 'Vim Commands',
    'ssh-cheatsheet': 'SSH Commands',
    'python-cheatsheet': 'Python Cheat Sheet',
    'grep-sed-awk': 'grep/sed/awk',
    'jq-cheatsheet': 'jq Commands',
    'changelog-generator': 'Changelog Generator',
    'scrollbar-generator': 'CSS Scrollbar Generator',
    'bash-scripting': 'Bash Scripting',
    'systemd-commands': 'systemd Commands',
    'sla-calculator': 'SLA Calculator (downtime budget)',
    'credit-card-tool': 'Credit Card Generator/Validator (Luhn)',
    'qr-code-generator': 'QR Code Generator',
    'barcode-generator': 'Barcode Generator',
    'html-formatter': 'HTML Formatter',
    'github-actions-cheatsheet': 'GitHub Actions (workflows)',
    'css-to-js': 'CSS ↔ JS (style object)',
    'nginx-cheatsheet': 'Nginx Cheat Sheet',
    'redis-commands': 'Redis Commands',
    'gh-cli-cheatsheet': 'GitHub CLI (gh)',
    'typescript-cheatsheet': 'TypeScript Cheat Sheet',
    'clamp-generator': 'Fluid Typography (clamp)',
    'css-triangle-generator': 'CSS Triangle Generator',
    'font-face-generator': 'CSS @font-face Generator',
    'morse-code-converter': 'Morse Code Converter',
    'glob-tester': 'Glob Pattern Tester (gitignore)',
    'data-uri-tool': 'Data URI Generator / Decoder',
    'directory-tree-generator': 'Directory Tree Generator',
    'html-cheatsheet': 'HTML Cheat Sheet',
    'js-testing-cheatsheet': 'JS Testing Cheat Sheet (Jest/Vitest)',
    'react-cheatsheet': 'React Cheat Sheet',
    'tailwind-cheatsheet': 'Tailwind CSS Cheat Sheet',
    'css-selectors-cheatsheet': 'CSS Selectors Cheat Sheet',
    'a11y-cheatsheet': 'Accessibility Cheat Sheet (a11y)',
    'jwt-claims-cheatsheet': 'JWT Claims Cheat Sheet',
    'grid-areas-generator': 'CSS Grid Areas Generator',
    'pattern-background-generator': 'CSS Pattern Background Generator',
    'sitemap-generator': 'XML Sitemap Generator',
    'web-app-manifest': 'Web App Manifest Generator',
    'editorconfig-generator': '.editorconfig Generator',
    'codeowners-generator': 'CODEOWNERS Generator',
    'license-generator': 'LICENSE Generator',
    'dockerignore-generator': '.dockerignore Generator',
    'prettierrc-generator': '.prettierrc Generator',
    'makefile-generator': 'Makefile Generator',
    'tsconfig-generator': 'tsconfig.json Generator',
    'css-spinner-generator': 'CSS Loading Spinner Generator',
    'color-blindness-simulator': 'Color Blindness Simulator',
    'text-shadow-generator': 'Text Shadow Generator',
    'transform-generator': 'CSS Transform Generator',
    'container-query-generator': 'CSS Container Queries Generator',
    'scroll-snap-generator': 'CSS Scroll Snap Generator',
    'css-transition-generator': 'CSS Transition Generator',
    'css-tooltip-generator': 'CSS Tooltip Generator',
    'gradient-text-generator': 'CSS Gradient Text Generator',
    'custom-properties-generator': 'CSS Custom Properties Generator',
    'css-columns-generator': 'CSS Columns (Multicol) Generator',
    'css-breadcrumbs-generator': 'CSS Breadcrumbs Generator',
    'css-tabs-generator': 'CSS Tabs Generator',
    'css-progress-bar-generator': 'CSS Progress Bar Generator',
    'css-modal-generator': 'CSS Modal/Dialog Generator',
    'css-accordion-generator': 'CSS Accordion Generator',
    'css-range-slider-generator': 'CSS Range Slider Generator',
    'css-star-rating-generator': 'CSS Star Rating Generator',
    'css-glassmorphism-generator': 'CSS Glassmorphism Generator',
    'css-toggle-switch-generator': 'CSS Toggle Switch Generator',
    'css-custom-checkbox-generator': 'CSS Custom Checkbox Generator',
    'css-radio-button-generator': 'CSS Radio Button Generator',
    'css-chip-generator': 'CSS Chip/Badge Generator',
    'css-pagination-generator': 'CSS Pagination Generator',
    'css-card-generator': 'CSS Card Generator',
    'css-dropdown-menu-generator': 'CSS Dropdown Menu Generator',
    'css-skeleton-generator': 'CSS Skeleton Generator',
    'css-timeline-generator': 'CSS Timeline Generator',
    'css-stepper-generator': 'CSS Stepper/Wizard Generator',
    'css-speech-bubble-generator': 'CSS Speech Bubble Generator',
    'css-button-generator': 'CSS Button Generator',
    'css-alert-generator': 'CSS Alert Generator',
    'css-avatar-generator': 'CSS Avatar Generator',
    'css-hamburger-menu-generator': 'CSS Hamburger Menu Generator',
    'css-corner-ribbon-generator': 'CSS Corner Ribbon Generator',
    'css-pricing-table-generator': 'CSS Pricing Table Generator',
    'css-image-hover-generator': 'CSS Image Hover Effects Generator',
    'css-segmented-control-generator': 'CSS Segmented Control Generator',
    'css-table-generator': 'CSS Table Generator',
    'css-cursor-generator': 'CSS Custom Cursor Generator',
    'css-flip-card-generator': 'CSS Flip Card Generator',
    'css-progress-ring-generator': 'CSS Progress Ring Generator',
    'css-divider-generator': 'CSS Divider Generator',
    'svg-badge-generator': 'SVG Badge Generator',
    'css-marquee-generator': 'CSS Marquee Generator',
    'css-carousel-generator': 'CSS Carousel Generator',
    'css-login-form-generator': 'CSS Login Form Generator',
    'css-neumorphism-generator': 'CSS Neumorphism Generator',
    'css-text-stroke-generator': 'CSS Text Stroke / Outline Generator',
    'css-line-clamp-generator': 'CSS Line Clamp Generator',
    'css-pulse-generator': 'CSS Pulse Effect Generator',
  },
}

function withNewBadge(key, label, l) {
  if (!NEW_ITEM_KEYS.includes(key)) return label
  return (
    <span>
      {label} <Tag color="green" style={{ marginLeft: 4, lineHeight: '16px', fontSize: 11 }}>{l.new}</Tag>
    </span>
  )
}

// Exportado pra HomePage.jsx remontar a mesma árvore de categorias/itens na
// grade da home, sem duplicar a fonte da verdade — o agente noturno só
// mexe aqui, então a home fica sincronizada de graça.
export function buildMenuItems(l) {
  return [
    { key: '/', icon: <HomeOutlined />, label: l.home },
    { key: '/bastidores', icon: <HistoryOutlined />, label: l.bastidores },
    {
      key: 'group-tools',
      icon: <ToolOutlined />,
      label: l.tools,
      children: [
        { key: '/tools/jwt-decoder', icon: <KeyOutlined />, label: l['jwt-decoder'] },
        { key: '/tools/html-to-jsx-converter', icon: <CodeOutlined />, label: withNewBadge('/tools/html-to-jsx-converter', l['html-to-jsx-converter'], l) },
        { key: '/tools/html-to-markdown', icon: <FileMarkdownOutlined />, label: withNewBadge('/tools/html-to-markdown', l['html-to-markdown'], l) },
        { key: '/tools/cron-parser', icon: <FieldTimeOutlined />, label: withNewBadge('/tools/cron-parser', l['cron-parser'], l) },
        { key: '/tools/cron-builder', icon: <FieldTimeOutlined />, label: withNewBadge('/tools/cron-builder', l['cron-builder'], l) },
        { key: '/tools/hash-generator', icon: <NumberOutlined />, label: l['hash-generator'] },
        { key: '/tools/json-formatter', icon: <FileTextOutlined />, label: l['json-formatter'] },
        { key: '/tools/color-converter', icon: <BgColorsOutlined />, label: l['color-converter'] },
        { key: '/tools/xml-formatter', icon: <FileTextOutlined />, label: withNewBadge('/tools/xml-formatter', l['xml-formatter'], l) },
        { key: '/tools/css-formatter', icon: <FileTextOutlined />, label: withNewBadge('/tools/css-formatter', l['css-formatter'], l) },
        { key: '/tools/toml-formatter', icon: <FileTextOutlined />, label: withNewBadge('/tools/toml-formatter', l['toml-formatter'], l) },
        { key: '/tools/html-formatter', icon: <FileTextOutlined />, label: withNewBadge('/tools/html-formatter', l['html-formatter'], l) },
        { key: '/tools/timestamp-converter', icon: <FieldTimeOutlined />, label: l['timestamp-converter'] },
        { key: '/tools/date-time-calculator', icon: <FieldTimeOutlined />, label: withNewBadge('/tools/date-time-calculator', l['date-time-calculator'], l) },
        { key: '/tools/regex-tester', icon: <SearchOutlined />, label: withNewBadge('/tools/regex-tester', l['regex-tester'], l) },
        { key: '/tools/keyboard-event-tester', icon: <KeyOutlined />, label: withNewBadge('/tools/keyboard-event-tester', l['keyboard-event-tester'], l) },
        { key: '/tools/base64-tool', icon: <SwapOutlined />, label: withNewBadge('/tools/base64-tool', l['base64-tool'], l) },
        { key: '/tools/uuid-generator', icon: <IdcardOutlined />, label: withNewBadge('/tools/uuid-generator', l['uuid-generator'], l) },
        { key: '/tools/uuid-v7-generator', icon: <IdcardOutlined />, label: withNewBadge('/tools/uuid-v7-generator', l['uuid-v7-generator'], l) },
        { key: '/tools/ulid-tool', icon: <IdcardOutlined />, label: withNewBadge('/tools/ulid-tool', l['ulid-tool'], l) },
        { key: '/tools/case-converter', icon: <FontSizeOutlined />, label: withNewBadge('/tools/case-converter', l['case-converter'], l) },
        { key: '/tools/password-generator', icon: <KeyOutlined />, label: withNewBadge('/tools/password-generator', l['password-generator'], l) },
        { key: '/tools/url-encoder', icon: <SwapOutlined />, label: withNewBadge('/tools/url-encoder', l['url-encoder'], l) },
        { key: '/tools/url-parser', icon: <LinkOutlined />, label: withNewBadge('/tools/url-parser', l['url-parser'], l) },
        { key: '/tools/xml-json-converter', icon: <SwapOutlined />, label: withNewBadge('/tools/xml-json-converter', l['xml-json-converter'], l) },
        { key: '/tools/diff-checker', icon: <DiffOutlined />, label: withNewBadge('/tools/diff-checker', l['diff-checker'], l) },
        { key: '/tools/markdown-previewer', icon: <FileMarkdownOutlined />, label: withNewBadge('/tools/markdown-previewer', l['markdown-previewer'], l) },
        { key: '/tools/cpf-cnpj-generator', icon: <IdcardOutlined />, label: withNewBadge('/tools/cpf-cnpj-generator', l['cpf-cnpj-generator'], l) },
        { key: '/tools/base-converter', icon: <NumberOutlined />, label: withNewBadge('/tools/base-converter', l['base-converter'], l) },
        { key: '/tools/semver-comparator', icon: <BranchesOutlined />, label: withNewBadge('/tools/semver-comparator', l['semver-comparator'], l) },
        { key: '/tools/slug-generator', icon: <LinkOutlined />, label: withNewBadge('/tools/slug-generator', l['slug-generator'], l) },
        { key: '/tools/css-unit-converter', icon: <ColumnWidthOutlined />, label: withNewBadge('/tools/css-unit-converter', l['css-unit-converter'], l) },
        { key: '/tools/aspect-ratio-calculator', icon: <PictureOutlined />, label: withNewBadge('/tools/aspect-ratio-calculator', l['aspect-ratio-calculator'], l) },
        { key: '/tools/css-specificity-calculator', icon: <OrderedListOutlined />, label: withNewBadge('/tools/css-specificity-calculator', l['css-specificity-calculator'], l) },
        { key: '/tools/css-selector-tester', icon: <SelectOutlined />, label: withNewBadge('/tools/css-selector-tester', l['css-selector-tester'], l) },
        { key: '/tools/nanoid-generator', icon: <IdcardOutlined />, label: withNewBadge('/tools/nanoid-generator', l['nanoid-generator'], l) },
        { key: '/tools/html-entity-encoder', icon: <SwapOutlined />, label: withNewBadge('/tools/html-entity-encoder', l['html-entity-encoder'], l) },
        { key: '/tools/hmac-generator', icon: <KeyOutlined />, label: withNewBadge('/tools/hmac-generator', l['hmac-generator'], l) },
        { key: '/tools/lorem-ipsum-generator', icon: <FileTextOutlined />, label: withNewBadge('/tools/lorem-ipsum-generator', l['lorem-ipsum-generator'], l) },
        { key: '/tools/jwt-generator', icon: <KeyOutlined />, label: withNewBadge('/tools/jwt-generator', l['jwt-generator'], l) },
        { key: '/tools/jwt-secret-generator', icon: <KeyOutlined />, label: withNewBadge('/tools/jwt-secret-generator', l['jwt-secret-generator'], l) },
        { key: '/tools/jwt-timeline', icon: <FieldTimeOutlined />, label: withNewBadge('/tools/jwt-timeline', l['jwt-timeline'], l) },
        { key: '/tools/unicode-inspector', icon: <CodeOutlined />, label: withNewBadge('/tools/unicode-inspector', l['unicode-inspector'], l) },
        { key: '/tools/timezone-converter', icon: <GlobalOutlined />, label: withNewBadge('/tools/timezone-converter', l['timezone-converter'], l) },
        { key: '/tools/number-to-words', icon: <NumberOutlined />, label: withNewBadge('/tools/number-to-words', l['number-to-words'], l) },
        { key: '/tools/float-explorer', icon: <NumberOutlined />, label: withNewBadge('/tools/float-explorer', l['float-explorer'], l) },
        { key: '/tools/crc-calculator', icon: <SafetyCertificateOutlined />, label: withNewBadge('/tools/crc-calculator', l['crc-calculator'], l) },
        { key: '/tools/units-converter', icon: <SwapOutlined />, label: withNewBadge('/tools/units-converter', l['units-converter'], l) },
        { key: '/tools/credit-card-tool', icon: <CreditCardOutlined />, label: withNewBadge('/tools/credit-card-tool', l['credit-card-tool'], l) },
        { key: '/tools/qr-code-generator', icon: <QrcodeOutlined />, label: withNewBadge('/tools/qr-code-generator', l['qr-code-generator'], l) },
        { key: '/tools/barcode-generator', icon: <BarcodeOutlined />, label: withNewBadge('/tools/barcode-generator', l['barcode-generator'], l) },
        { key: '/tools/morse-code-converter', icon: <AudioOutlined />, label: withNewBadge('/tools/morse-code-converter', l['morse-code-converter'], l) },
        { key: '/tools/glob-tester', icon: <SearchOutlined />, label: withNewBadge('/tools/glob-tester', l['glob-tester'], l) },
        { key: '/tools/data-uri-tool', icon: <LinkOutlined />, label: withNewBadge('/tools/data-uri-tool', l['data-uri-tool'], l) },
        { key: '/tools/directory-tree-generator', icon: <FolderOutlined />, label: withNewBadge('/tools/directory-tree-generator', l['directory-tree-generator'], l) },
        { key: '/tools/passphrase-generator', icon: <KeyOutlined />, label: withNewBadge('/tools/passphrase-generator', l['passphrase-generator'], l) },
        { key: '/tools/totp-generator', icon: <SafetyOutlined />, label: withNewBadge('/tools/totp-generator', l['totp-generator'], l) },
        { key: '/tools/payload-compression-calculator', icon: <CompressOutlined />, label: withNewBadge('/tools/payload-compression-calculator', l['payload-compression-calculator'], l) },
        { key: '/tools/url-email-extractor', icon: <LinkOutlined />, label: withNewBadge('/tools/url-email-extractor', l['url-email-extractor'], l) },
        { key: '/tools/iban-tool', icon: <BankOutlined />, label: withNewBadge('/tools/iban-tool', l['iban-tool'], l) },
        { key: '/tools/roman-numeral-converter', icon: <NumberOutlined />, label: withNewBadge('/tools/roman-numeral-converter', l['roman-numeral-converter'], l) },
        { key: '/tools/file-size-converter', icon: <SwapOutlined />, label: withNewBadge('/tools/file-size-converter', l['file-size-converter'], l) },
        { key: '/tools/file-hash-calculator', icon: <SafetyOutlined />, label: withNewBadge('/tools/file-hash-calculator', l['file-hash-calculator'], l) },
        { key: '/tools/geo-coordinates-converter', icon: <EnvironmentOutlined />, label: withNewBadge('/tools/geo-coordinates-converter', l['geo-coordinates-converter'], l) },
        { key: '/tools/levenshtein-calculator', icon: <CalculatorOutlined />, label: withNewBadge('/tools/levenshtein-calculator', l['levenshtein-calculator'], l) },
        { key: '/tools/bandwidth-calculator', icon: <ThunderboltOutlined />, label: withNewBadge('/tools/bandwidth-calculator', l['bandwidth-calculator'], l) },
        { key: '/tools/cookie-tool', icon: <ContainerOutlined />, label: withNewBadge('/tools/cookie-tool', l['cookie-tool'], l) },
        { key: '/tools/compound-interest-calculator', icon: <LineChartOutlined />, label: withNewBadge('/tools/compound-interest-calculator', l['compound-interest-calculator'], l) },
        { key: '/tools/percentage-calculator', icon: <PercentageOutlined />, label: withNewBadge('/tools/percentage-calculator', l['percentage-calculator'], l) },
      ],
    },
    {
      key: 'group-styles',
      icon: <BgColorsOutlined />,
      label: l.styles,
      children: [
        { key: '/styles/glass-card', label: l['glass-card'] },
        { key: '/styles/copy-button', label: l['copy-button'] },
        { key: '/styles/skeleton-shimmer', label: l['skeleton-shimmer'] },
        { key: '/styles/spotlight-card', label: withNewBadge('/styles/spotlight-card', l['spotlight-card'], l) },
        { key: '/styles/gradient-border-button', label: l['gradient-border-button'] },
        { key: '/styles/neumorphic-card', label: withNewBadge('/styles/neumorphic-card', l['neumorphic-card'], l) },
        { key: '/styles/bouncing-dots-loader', label: withNewBadge('/styles/bouncing-dots-loader', l['bouncing-dots-loader'], l) },
        { key: '/styles/ripple-button', label: withNewBadge('/styles/ripple-button', l['ripple-button'], l) },
        { key: '/styles/floating-label-input', label: withNewBadge('/styles/floating-label-input', l['floating-label-input'], l) },
        { key: '/styles/ios-toggle-switch', label: withNewBadge('/styles/ios-toggle-switch', l['ios-toggle-switch'], l) },
        { key: '/styles/dark-mode-toggle', label: withNewBadge('/styles/dark-mode-toggle', l['dark-mode-toggle'], l) },
        { key: '/styles/toast-notification', label: withNewBadge('/styles/toast-notification', l['toast-notification'], l) },
        { key: '/styles/scroll-progress-bar', label: withNewBadge('/styles/scroll-progress-bar', l['scroll-progress-bar'], l) },
        { key: '/styles/confetti-effect', label: withNewBadge('/styles/confetti-effect', l['confetti-effect'], l) },
        { key: '/styles/typewriter-effect', label: withNewBadge('/styles/typewriter-effect', l['typewriter-effect'], l) },
        { key: '/styles/otp-input', icon: <NumberOutlined />, label: withNewBadge('/styles/otp-input', l['otp-input'], l) },
      ],
    },
    {
      key: 'group-snippets',
      icon: <CodeOutlined />,
      label: l.snippets,
      children: [
        { key: '/snippets/use-debounce', label: l['use-debounce'] },
        { key: '/snippets/use-local-storage', label: l['use-local-storage'] },
        { key: '/snippets/use-session-storage', label: withNewBadge('/snippets/use-session-storage', l['use-session-storage'], l) },
        { key: '/snippets/use-click-outside', label: l['use-click-outside'] },
        { key: '/snippets/use-media-query', label: l['use-media-query'] },
        { key: '/snippets/use-copy-to-clipboard', label: withNewBadge('/snippets/use-copy-to-clipboard', l['use-copy-to-clipboard'], l) },
        { key: '/snippets/use-interval', label: withNewBadge('/snippets/use-interval', l['use-interval'], l) },
        { key: '/snippets/use-timeout', label: withNewBadge('/snippets/use-timeout', l['use-timeout'], l) },
        { key: '/snippets/use-countdown', label: withNewBadge('/snippets/use-countdown', l['use-countdown'], l) },
        { key: '/snippets/use-fetch', label: withNewBadge('/snippets/use-fetch', l['use-fetch'], l) },
        { key: '/snippets/use-previous', label: withNewBadge('/snippets/use-previous', l['use-previous'], l) },
        { key: '/snippets/use-toggle', label: withNewBadge('/snippets/use-toggle', l['use-toggle'], l) },
        { key: '/snippets/use-window-size', label: withNewBadge('/snippets/use-window-size', l['use-window-size'], l) },
        { key: '/snippets/use-on-screen', label: withNewBadge('/snippets/use-on-screen', l['use-on-screen'], l) },
        { key: '/snippets/use-key-press', label: withNewBadge('/snippets/use-key-press', l['use-key-press'], l) },
        { key: '/snippets/use-event-listener', label: withNewBadge('/snippets/use-event-listener', l['use-event-listener'], l) },
        { key: '/snippets/use-throttle', label: withNewBadge('/snippets/use-throttle', l['use-throttle'], l) },
        { key: '/snippets/fisher-yates-shuffle', label: withNewBadge('/snippets/fisher-yates-shuffle', l['fisher-yates-shuffle'], l) },
        { key: '/snippets/use-undo', label: withNewBadge('/snippets/use-undo', l['use-undo'], l) },
        { key: '/snippets/use-network-status', label: withNewBadge('/snippets/use-network-status', l['use-network-status'], l) },
        { key: '/snippets/use-element-size', label: withNewBadge('/snippets/use-element-size', l['use-element-size'], l) },
        { key: '/snippets/use-mouse-position', label: withNewBadge('/snippets/use-mouse-position', l['use-mouse-position'], l) },
        { key: '/snippets/use-page-visibility', label: withNewBadge('/snippets/use-page-visibility', l['use-page-visibility'], l) },
        { key: '/snippets/use-async', label: withNewBadge('/snippets/use-async', l['use-async'], l) },
        { key: '/snippets/use-update-effect', label: withNewBadge('/snippets/use-update-effect', l['use-update-effect'], l) },
        { key: '/snippets/use-why-did-you-update', label: withNewBadge('/snippets/use-why-did-you-update', l['use-why-did-you-update'], l) },
        { key: '/snippets/use-boolean', label: withNewBadge('/snippets/use-boolean', l['use-boolean'], l) },
        { key: '/snippets/use-set', label: withNewBadge('/snippets/use-set', l['use-set'], l) },
        { key: '/snippets/use-counter', label: withNewBadge('/snippets/use-counter', l['use-counter'], l) },
        { key: '/snippets/use-lock-body-scroll', icon: <LockOutlined />, label: withNewBadge('/snippets/use-lock-body-scroll', l['use-lock-body-scroll'], l) },
        { key: '/snippets/use-stable-callback', icon: <CodeOutlined />, label: withNewBadge('/snippets/use-stable-callback', l['use-stable-callback'], l) },
        { key: '/snippets/use-hover', icon: <CodeOutlined />, label: withNewBadge('/snippets/use-hover', l['use-hover'], l) },
        { key: '/snippets/use-merged-ref', icon: <CodeOutlined />, label: withNewBadge('/snippets/use-merged-ref', l['use-merged-ref'], l) },
        { key: '/snippets/use-queue', icon: <CodeOutlined />, label: withNewBadge('/snippets/use-queue', l['use-queue'], l) },
        { key: '/snippets/use-long-press', label: withNewBadge('/snippets/use-long-press', l['use-long-press'], l) },
        { key: '/snippets/use-form', label: withNewBadge('/snippets/use-form', l['use-form'], l) },
        { key: '/snippets/use-preferred-color-scheme', label: withNewBadge('/snippets/use-preferred-color-scheme', l['use-preferred-color-scheme'], l) },
        { key: '/snippets/use-favicon', icon: <SmileOutlined />, label: withNewBadge('/snippets/use-favicon', l['use-favicon'], l) },
        { key: '/snippets/use-document-title', icon: <EditOutlined />, label: withNewBadge('/snippets/use-document-title', l['use-document-title'], l) },
        { key: '/snippets/use-list', icon: <OrderedListOutlined />, label: withNewBadge('/snippets/use-list', l['use-list'], l) },
        { key: '/snippets/use-map', icon: <AppstoreOutlined />, label: withNewBadge('/snippets/use-map', l['use-map'], l) },
        { key: '/snippets/use-state-with-history', icon: <HistoryOutlined />, label: withNewBadge('/snippets/use-state-with-history', l['use-state-with-history'], l) },
        { key: '/snippets/use-idle', icon: <ClockCircleOutlined />, label: withNewBadge('/snippets/use-idle', l['use-idle'], l) },
        { key: '/snippets/use-mutation-observer', icon: <CodeOutlined />, label: withNewBadge('/snippets/use-mutation-observer', l['use-mutation-observer'], l) },
        { key: '/snippets/use-resize-observer', icon: <CodeOutlined />, label: withNewBadge('/snippets/use-resize-observer', l['use-resize-observer'], l) },
        { key: '/snippets/use-hotkeys', icon: <CodeOutlined />, label: withNewBadge('/snippets/use-hotkeys', l['use-hotkeys'], l) },
        { key: '/snippets/use-speech-synthesis', icon: <SoundOutlined />, label: withNewBadge('/snippets/use-speech-synthesis', l['use-speech-synthesis'], l) },
        { key: '/snippets/use-pagination', icon: <CodeOutlined />, label: withNewBadge('/snippets/use-pagination', l['use-pagination'], l) },
        { key: '/snippets/use-controllable-state', icon: <CodeOutlined />, label: withNewBadge('/snippets/use-controllable-state', l['use-controllable-state'], l) },
        { key: '/snippets/use-window-focus', icon: <CodeOutlined />, label: withNewBadge('/snippets/use-window-focus', l['use-window-focus'], l) },
        { key: '/snippets/use-before-unload', icon: <WarningOutlined />, label: withNewBadge('/snippets/use-before-unload', l['use-before-unload'], l) },
        { key: '/snippets/use-count-up', icon: <CodeOutlined />, label: withNewBadge('/snippets/use-count-up', l['use-count-up'], l) },
        { key: '/snippets/use-script', icon: <CodeOutlined />, label: withNewBadge('/snippets/use-script', l['use-script'], l) },
        { key: '/snippets/use-battery', icon: <ThunderboltOutlined />, label: withNewBadge('/snippets/use-battery', l['use-battery'], l) },
        { key: '/snippets/use-geolocation', icon: <EnvironmentOutlined />, label: withNewBadge('/snippets/use-geolocation', l['use-geolocation'], l) },
        { key: '/snippets/debounce-throttle-functions', label: withNewBadge('/snippets/debounce-throttle-functions', l['debounce-throttle-functions'], l) },
        { key: '/snippets/lru-cache', label: withNewBadge('/snippets/lru-cache', l['lru-cache'], l) },
        { key: '/snippets/deep-clone-deep-equal', label: withNewBadge('/snippets/deep-clone-deep-equal', l['deep-clone-deep-equal'], l) },
      ],
    },
    {
      key: 'group-frontend',
      icon: <BgColorsOutlined />,
      label: l.frontend,
      children: [
        { key: '/frontend/contrast-checker', label: l['contrast-checker'] },
        { key: '/frontend/gradient-generator', label: withNewBadge('/frontend/gradient-generator', l['gradient-generator'], l) },
        { key: '/frontend/box-shadow-generator', label: withNewBadge('/frontend/box-shadow-generator', l['box-shadow-generator'], l) },
        { key: '/frontend/palette-generator', label: withNewBadge('/frontend/palette-generator', l['palette-generator'], l) },
        { key: '/frontend/border-radius-generator', label: withNewBadge('/frontend/border-radius-generator', l['border-radius-generator'], l) },
        { key: '/frontend/svg-placeholder-generator', icon: <PictureOutlined />, label: withNewBadge('/frontend/svg-placeholder-generator', l['svg-placeholder-generator'], l) },
        { key: '/frontend/cubic-bezier-editor', icon: <LineChartOutlined />, label: withNewBadge('/frontend/cubic-bezier-editor', l['cubic-bezier-editor'], l) },
        { key: '/frontend/svg-wave-generator', icon: <PictureOutlined />, label: withNewBadge('/frontend/svg-wave-generator', l['svg-wave-generator'], l) },
        { key: '/frontend/css-filter-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-filter-generator', l['css-filter-generator'], l) },
        { key: '/frontend/meta-tags-generator', icon: <GlobalOutlined />, label: withNewBadge('/frontend/meta-tags-generator', l['meta-tags-generator'], l) },
        { key: '/frontend/keyframe-generator', icon: <LineChartOutlined />, label: withNewBadge('/frontend/keyframe-generator', l['keyframe-generator'], l) },
        { key: '/frontend/clip-path-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/clip-path-generator', l['clip-path-generator'], l) },
        { key: '/frontend/scrollbar-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/scrollbar-generator', l['scrollbar-generator'], l) },
        { key: '/frontend/css-to-js', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-to-js', l['css-to-js'], l) },
        { key: '/frontend/clamp-generator', icon: <FontSizeOutlined />, label: withNewBadge('/frontend/clamp-generator', l['clamp-generator'], l) },
        { key: '/frontend/css-triangle-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-triangle-generator', l['css-triangle-generator'], l) },
        { key: '/frontend/font-face-generator', icon: <FontSizeOutlined />, label: withNewBadge('/frontend/font-face-generator', l['font-face-generator'], l) },
        { key: '/frontend/grid-areas-generator', icon: <AppstoreOutlined />, label: withNewBadge('/frontend/grid-areas-generator', l['grid-areas-generator'], l) },
        { key: '/frontend/pattern-background-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/pattern-background-generator', l['pattern-background-generator'], l) },
        { key: '/frontend/sitemap-generator', icon: <GlobalOutlined />, label: withNewBadge('/frontend/sitemap-generator', l['sitemap-generator'], l) },
        { key: '/frontend/web-app-manifest', icon: <MobileOutlined />, label: withNewBadge('/frontend/web-app-manifest', l['web-app-manifest'], l) },
        { key: '/frontend/css-spinner-generator', icon: <LoadingOutlined />, label: withNewBadge('/frontend/css-spinner-generator', l['css-spinner-generator'], l) },
        { key: '/frontend/color-blindness-simulator', icon: <EyeOutlined />, label: withNewBadge('/frontend/color-blindness-simulator', l['color-blindness-simulator'], l) },
        { key: '/frontend/text-shadow-generator', icon: <FontSizeOutlined />, label: withNewBadge('/frontend/text-shadow-generator', l['text-shadow-generator'], l) },
        { key: '/frontend/transform-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/transform-generator', l['transform-generator'], l) },
        { key: '/frontend/container-query-generator', icon: <AppstoreOutlined />, label: withNewBadge('/frontend/container-query-generator', l['container-query-generator'], l) },
        { key: '/frontend/scroll-snap-generator', icon: <PicCenterOutlined />, label: withNewBadge('/frontend/scroll-snap-generator', l['scroll-snap-generator'], l) },
        { key: '/frontend/css-transition-generator', icon: <SwapOutlined />, label: withNewBadge('/frontend/css-transition-generator', l['css-transition-generator'], l) },
        { key: '/frontend/css-tooltip-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-tooltip-generator', l['css-tooltip-generator'], l) },
        { key: '/frontend/gradient-text-generator', icon: <FontSizeOutlined />, label: withNewBadge('/frontend/gradient-text-generator', l['gradient-text-generator'], l) },
        { key: '/frontend/custom-properties-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/custom-properties-generator', l['custom-properties-generator'], l) },
        { key: '/frontend/css-columns-generator', icon: <ColumnWidthOutlined />, label: withNewBadge('/frontend/css-columns-generator', l['css-columns-generator'], l) },
        { key: '/frontend/css-breadcrumbs-generator', icon: <PartitionOutlined />, label: withNewBadge('/frontend/css-breadcrumbs-generator', l['css-breadcrumbs-generator'], l) },
        { key: '/frontend/css-tabs-generator', icon: <LayoutOutlined />, label: withNewBadge('/frontend/css-tabs-generator', l['css-tabs-generator'], l) },
        { key: '/frontend/css-progress-bar-generator', icon: <LoadingOutlined />, label: withNewBadge('/frontend/css-progress-bar-generator', l['css-progress-bar-generator'], l) },
        { key: '/frontend/css-modal-generator', icon: <ContainerOutlined />, label: withNewBadge('/frontend/css-modal-generator', l['css-modal-generator'], l) },
        { key: '/frontend/css-accordion-generator', icon: <ContainerOutlined />, label: withNewBadge('/frontend/css-accordion-generator', l['css-accordion-generator'], l) },
        { key: '/frontend/css-range-slider-generator', icon: <SlidersOutlined />, label: withNewBadge('/frontend/css-range-slider-generator', l['css-range-slider-generator'], l) },
        { key: '/frontend/css-star-rating-generator', icon: <StarOutlined />, label: withNewBadge('/frontend/css-star-rating-generator', l['css-star-rating-generator'], l) },
        { key: '/frontend/css-glassmorphism-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-glassmorphism-generator', l['css-glassmorphism-generator'], l) },
        { key: '/frontend/css-toggle-switch-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-toggle-switch-generator', l['css-toggle-switch-generator'], l) },
        { key: '/frontend/css-custom-checkbox-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-custom-checkbox-generator', l['css-custom-checkbox-generator'], l) },
        { key: '/frontend/css-radio-button-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-radio-button-generator', l['css-radio-button-generator'], l) },
        { key: '/frontend/css-chip-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-chip-generator', l['css-chip-generator'], l) },
        { key: '/frontend/css-pagination-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-pagination-generator', l['css-pagination-generator'], l) },
        { key: '/frontend/css-card-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-card-generator', l['css-card-generator'], l) },
        { key: '/frontend/css-dropdown-menu-generator', icon: <DownOutlined />, label: withNewBadge('/frontend/css-dropdown-menu-generator', l['css-dropdown-menu-generator'], l) },
        { key: '/frontend/css-skeleton-generator', icon: <LoadingOutlined />, label: withNewBadge('/frontend/css-skeleton-generator', l['css-skeleton-generator'], l) },
        { key: '/frontend/css-timeline-generator', icon: <FieldTimeOutlined />, label: withNewBadge('/frontend/css-timeline-generator', l['css-timeline-generator'], l) },
        { key: '/frontend/css-stepper-generator', icon: <OrderedListOutlined />, label: withNewBadge('/frontend/css-stepper-generator', l['css-stepper-generator'], l) },
        { key: '/frontend/css-speech-bubble-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-speech-bubble-generator', l['css-speech-bubble-generator'], l) },
        { key: '/frontend/css-button-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-button-generator', l['css-button-generator'], l) },
        { key: '/frontend/css-alert-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-alert-generator', l['css-alert-generator'], l) },
        { key: '/frontend/css-avatar-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-avatar-generator', l['css-avatar-generator'], l) },
        { key: '/frontend/css-hamburger-menu-generator', icon: <MenuOutlined />, label: withNewBadge('/frontend/css-hamburger-menu-generator', l['css-hamburger-menu-generator'], l) },
        { key: '/frontend/css-corner-ribbon-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-corner-ribbon-generator', l['css-corner-ribbon-generator'], l) },
        { key: '/frontend/css-pricing-table-generator', icon: <TableOutlined />, label: withNewBadge('/frontend/css-pricing-table-generator', l['css-pricing-table-generator'], l) },
        { key: '/frontend/css-image-hover-generator', icon: <PictureOutlined />, label: withNewBadge('/frontend/css-image-hover-generator', l['css-image-hover-generator'], l) },
        { key: '/frontend/css-segmented-control-generator', icon: <AppstoreOutlined />, label: withNewBadge('/frontend/css-segmented-control-generator', l['css-segmented-control-generator'], l) },
        { key: '/frontend/css-table-generator', icon: <TableOutlined />, label: withNewBadge('/frontend/css-table-generator', l['css-table-generator'], l) },
        { key: '/frontend/css-cursor-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-cursor-generator', l['css-cursor-generator'], l) },
        { key: '/frontend/css-flip-card-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-flip-card-generator', l['css-flip-card-generator'], l) },
        { key: '/frontend/css-progress-ring-generator', icon: <LoadingOutlined />, label: withNewBadge('/frontend/css-progress-ring-generator', l['css-progress-ring-generator'], l) },
        { key: '/frontend/css-divider-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-divider-generator', l['css-divider-generator'], l) },
        { key: '/frontend/svg-badge-generator', icon: <PictureOutlined />, label: withNewBadge('/frontend/svg-badge-generator', l['svg-badge-generator'], l) },
        { key: '/frontend/css-marquee-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-marquee-generator', l['css-marquee-generator'], l) },
        { key: '/frontend/css-carousel-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-carousel-generator', l['css-carousel-generator'], l) },
        { key: '/frontend/css-login-form-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-login-form-generator', l['css-login-form-generator'], l) },
        { key: '/frontend/css-neumorphism-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-neumorphism-generator', l['css-neumorphism-generator'], l) },
        { key: '/frontend/css-text-stroke-generator', icon: <FontSizeOutlined />, label: withNewBadge('/frontend/css-text-stroke-generator', l['css-text-stroke-generator'], l) },
        { key: '/frontend/css-line-clamp-generator', icon: <FontSizeOutlined />, label: withNewBadge('/frontend/css-line-clamp-generator', l['css-line-clamp-generator'], l) },
        { key: '/frontend/css-pulse-generator', icon: <BgColorsOutlined />, label: withNewBadge('/frontend/css-pulse-generator', l['css-pulse-generator'], l) },
      ],
    },
    {
      key: 'group-apis',
      icon: <ApiOutlined />,
      label: l.apis,
      children: [
        { key: '/apis/curl-generator', label: l['curl-generator'] },
        { key: '/apis/curl-to-code', icon: <CodeOutlined />, label: withNewBadge('/apis/curl-to-code', l['curl-to-code'], l) },
        { key: '/apis/webhook-payload-generator', label: withNewBadge('/apis/webhook-payload-generator', l['webhook-payload-generator'], l) },
      ],
    },
    {
      key: 'group-devops',
      icon: <ToolOutlined />,
      label: l.devops,
      children: [
        { key: '/devops/gitignore-generator', label: l['gitignore-generator'] },
        { key: '/devops/gitattributes-generator', icon: <FileTextOutlined />, label: withNewBadge('/devops/gitattributes-generator', l['gitattributes-generator'], l) },
        { key: '/devops/commit-message-generator', label: withNewBadge('/devops/commit-message-generator', l['commit-message-generator'], l) },
        { key: '/devops/changelog-generator', icon: <HistoryOutlined />, label: withNewBadge('/devops/changelog-generator', l['changelog-generator'], l) },
        { key: '/devops/env-tool', icon: <FileProtectOutlined />, label: withNewBadge('/devops/env-tool', l['env-tool'], l) },
        { key: '/devops/branch-name-generator', icon: <BranchesOutlined />, label: withNewBadge('/devops/branch-name-generator', l['branch-name-generator'], l) },
        { key: '/devops/kubectl-commands', icon: <ClusterOutlined />, label: withNewBadge('/devops/kubectl-commands', l['kubectl-commands'], l) },
        { key: '/devops/chmod-calculator', icon: <SafetyCertificateOutlined />, label: withNewBadge('/devops/chmod-calculator', l['chmod-calculator'], l) },
        { key: '/devops/dockerfile-generator', icon: <ContainerOutlined />, label: withNewBadge('/devops/dockerfile-generator', l['dockerfile-generator'], l) },
        { key: '/devops/caddyfile-generator', icon: <ContainerOutlined />, label: withNewBadge('/devops/caddyfile-generator', l['caddyfile-generator'], l) },
        { key: '/devops/htaccess-generator', icon: <FileTextOutlined />, label: withNewBadge('/devops/htaccess-generator', l['htaccess-generator'], l) },
        { key: '/devops/docker-compose-generator', icon: <ContainerOutlined />, label: withNewBadge('/devops/docker-compose-generator', l['docker-compose-generator'], l) },
        { key: '/devops/ansi-colors', icon: <BgColorsOutlined />, label: withNewBadge('/devops/ansi-colors', l['ansi-colors'], l) },
        { key: '/devops/openssl-commands', icon: <ContainerOutlined />, label: withNewBadge('/devops/openssl-commands', l['openssl-commands'], l) },
        { key: '/devops/sla-calculator', icon: <ExperimentOutlined />, label: withNewBadge('/devops/sla-calculator', l['sla-calculator'], l) },
        { key: '/devops/editorconfig-generator', icon: <FileTextOutlined />, label: withNewBadge('/devops/editorconfig-generator', l['editorconfig-generator'], l) },
        { key: '/devops/codeowners-generator', icon: <TeamOutlined />, label: withNewBadge('/devops/codeowners-generator', l['codeowners-generator'], l) },
        { key: '/devops/license-generator', icon: <FileTextOutlined />, label: withNewBadge('/devops/license-generator', l['license-generator'], l) },
        { key: '/devops/dockerignore-generator', icon: <ContainerOutlined />, label: withNewBadge('/devops/dockerignore-generator', l['dockerignore-generator'], l) },
        { key: '/devops/prettierrc-generator', icon: <FileTextOutlined />, label: withNewBadge('/devops/prettierrc-generator', l['prettierrc-generator'], l) },
        { key: '/devops/makefile-generator', icon: <FileTextOutlined />, label: withNewBadge('/devops/makefile-generator', l['makefile-generator'], l) },
        { key: '/devops/tsconfig-generator', icon: <CodeOutlined />, label: withNewBadge('/devops/tsconfig-generator', l['tsconfig-generator'], l) },
      ],
    },
    {
      key: 'group-database',
      icon: <DatabaseOutlined />,
      label: l.database,
      children: [
        { key: '/database/rate-limit-calculator', label: l['rate-limit-calculator'] },
        { key: '/database/json-to-sql', icon: <DatabaseOutlined />, label: withNewBadge('/database/json-to-sql', l['json-to-sql'], l) },
        { key: '/database/sql-formatter', icon: <FileTextOutlined />, label: withNewBadge('/database/sql-formatter', l['sql-formatter'], l) },
      ],
    },
    {
      key: 'group-cloud',
      icon: <CloudOutlined />,
      label: l.cloud,
      children: [
        { key: '/cloud/arn-parser', label: l['arn-parser'] },
      ],
    },
    {
      key: 'group-security',
      icon: <SafetyCertificateOutlined />,
      label: l.security,
      children: [
        { key: '/security/password-strength', label: l['password-strength'] },
        { key: '/security/robots-txt-generator', label: withNewBadge('/security/robots-txt-generator', l['robots-txt-generator'], l) },
        { key: '/security/csp-generator', label: withNewBadge('/security/csp-generator', l['csp-generator'], l) },
        { key: '/security/security-headers-generator', label: withNewBadge('/security/security-headers-generator', l['security-headers-generator'], l) },
        { key: '/security/sri-hash-generator', icon: <SafetyOutlined />, label: withNewBadge('/security/sri-hash-generator', l['sri-hash-generator'], l) },
        { key: '/security/security-txt-generator', icon: <SafetyOutlined />, label: withNewBadge('/security/security-txt-generator', l['security-txt-generator'], l) },
        { key: '/security/webhook-signature-validator', icon: <SafetyOutlined />, label: withNewBadge('/security/webhook-signature-validator', l['webhook-signature-validator'], l) },
        { key: '/security/asymmetric-key-generator', icon: <KeyOutlined />, label: withNewBadge('/security/asymmetric-key-generator', l['asymmetric-key-generator'], l) },
      ],
    },
    {
      key: 'group-data',
      icon: <FolderOutlined />,
      label: l.data,
      children: [
        { key: '/data/json-tree-viewer', label: l['json-tree-viewer'] },
        { key: '/data/csv-json-converter', label: withNewBadge('/data/csv-json-converter', l['csv-json-converter'], l) },
        { key: '/data/fake-data-generator', label: withNewBadge('/data/fake-data-generator', l['fake-data-generator'], l) },
        { key: '/data/json-diff', label: withNewBadge('/data/json-diff', l['json-diff'], l) },
        { key: '/data/json-path-explorer', label: withNewBadge('/data/json-path-explorer', l['json-path-explorer'], l) },
        { key: '/data/json-schema-generator', icon: <CodeOutlined />, label: withNewBadge('/data/json-schema-generator', l['json-schema-generator'], l) },
        { key: '/data/json-schema-validator', icon: <CodeOutlined />, label: withNewBadge('/data/json-schema-validator', l['json-schema-validator'], l) },
        { key: '/data/csv-markdown-table', icon: <TableOutlined />, label: withNewBadge('/data/csv-markdown-table', l['csv-markdown-table'], l) },
        { key: '/data/json-to-typescript', icon: <CodeOutlined />, label: withNewBadge('/data/json-to-typescript', l['json-to-typescript'], l) },
        { key: '/data/json-to-yaml', icon: <CodeOutlined />, label: withNewBadge('/data/json-to-yaml', l['json-to-yaml'], l) },
        { key: '/data/json-flatten', icon: <FileTextOutlined />, label: withNewBadge('/data/json-flatten', l['json-flatten'], l) },
      ],
    },
    {
      key: 'group-network',
      icon: <GlobalOutlined />,
      label: l.network,
      children: [
        { key: '/network/subnet-calculator', label: l['subnet-calculator'] },
        { key: '/network/user-agent-parser', icon: <UserOutlined />, label: withNewBadge('/network/user-agent-parser', l['user-agent-parser'], l) },
        { key: '/network/mime-lookup', icon: <InboxOutlined />, label: withNewBadge('/network/mime-lookup', l['mime-lookup'], l) },
        { key: '/network/common-ports', icon: <GlobalOutlined />, label: withNewBadge('/network/common-ports', l['common-ports'], l) },
        { key: '/network/ipv6-explorer', icon: <GlobalOutlined />, label: withNewBadge('/network/ipv6-explorer', l['ipv6-explorer'], l) },
        { key: '/network/mac-address-tool', icon: <GlobalOutlined />, label: withNewBadge('/network/mac-address-tool', l['mac-address-tool'], l) },
      ],
    },
    {
      key: 'group-ai',
      icon: <RobotOutlined />,
      label: l.ai,
      children: [
        { key: '/ai/anthropic-cost-calculator', label: l['anthropic-cost-calculator'] },
        { key: '/ai/token-counter', label: withNewBadge('/ai/token-counter', l['token-counter'], l) },
      ],
    },
    {
      key: 'group-mobile',
      icon: <MobileOutlined />,
      label: l.mobile,
      children: [
        { key: '/mobile/deep-link-tester', label: l['deep-link-tester'] },
      ],
    },
    {
      key: 'group-text',
      icon: <FontSizeOutlined />,
      label: l.text,
      children: [
        { key: '/text/word-counter', label: l['word-counter'] },
        { key: '/text/remove-accents', icon: <FontSizeOutlined />, label: withNewBadge('/text/remove-accents', l['remove-accents'], l) },
        { key: '/text/lines-tool', icon: <OrderedListOutlined />, label: withNewBadge('/text/lines-tool', l['lines-tool'], l) },
      ],
    },
    {
      key: 'group-references',
      icon: <ReadOutlined />,
      label: l.references,
      children: [
        { key: '/references/git-commands', label: l['git-commands'] },
        { key: '/references/http-status-codes', label: withNewBadge('/references/http-status-codes', l['http-status-codes'], l) },
        { key: '/references/docker-commands', label: withNewBadge('/references/docker-commands', l['docker-commands'], l) },
        { key: '/references/flexbox-cheatsheet', label: withNewBadge('/references/flexbox-cheatsheet', l['flexbox-cheatsheet'], l) },
        { key: '/references/sql-commands', label: withNewBadge('/references/sql-commands', l['sql-commands'], l) },
        { key: '/references/sql-joins', icon: <DatabaseOutlined />, label: withNewBadge('/references/sql-joins', l['sql-joins'], l) },
        { key: '/references/package-manager-commands', label: withNewBadge('/references/package-manager-commands', l['package-manager-commands'], l) },
        { key: '/references/vscode-shortcuts', label: withNewBadge('/references/vscode-shortcuts', l['vscode-shortcuts'], l) },
        { key: '/references/css-grid-cheatsheet', label: withNewBadge('/references/css-grid-cheatsheet', l['css-grid-cheatsheet'], l) },
        { key: '/references/bash-shortcuts', label: withNewBadge('/references/bash-shortcuts', l['bash-shortcuts'], l) },
        { key: '/references/http-methods', label: withNewBadge('/references/http-methods', l['http-methods'], l) },
        { key: '/references/markdown-syntax', icon: <FileMarkdownOutlined />, label: withNewBadge('/references/markdown-syntax', l['markdown-syntax'], l) },
        { key: '/references/html-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/html-cheatsheet', l['html-cheatsheet'], l) },
        { key: '/references/ascii-table', icon: <FontSizeOutlined />, label: withNewBadge('/references/ascii-table', l['ascii-table'], l) },
        { key: '/references/regex-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/regex-cheatsheet', l['regex-cheatsheet'], l) },
        { key: '/references/http-headers', icon: <SendOutlined />, label: withNewBadge('/references/http-headers', l['http-headers'], l) },
        { key: '/references/javascript-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/javascript-cheatsheet', l['javascript-cheatsheet'], l) },
        { key: '/references/tmux-cheatsheet', icon: <ColumnWidthOutlined />, label: withNewBadge('/references/tmux-cheatsheet', l['tmux-cheatsheet'], l) },
        { key: '/references/devtools-shortcuts', icon: <CodeOutlined />, label: withNewBadge('/references/devtools-shortcuts', l['devtools-shortcuts'], l) },
        { key: '/references/vim-cheatsheet', icon: <ColumnWidthOutlined />, label: withNewBadge('/references/vim-cheatsheet', l['vim-cheatsheet'], l) },
        { key: '/references/ssh-cheatsheet', icon: <SafetyCertificateOutlined />, label: withNewBadge('/references/ssh-cheatsheet', l['ssh-cheatsheet'], l) },
        { key: '/references/python-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/python-cheatsheet', l['python-cheatsheet'], l) },
        { key: '/references/grep-sed-awk', icon: <ColumnWidthOutlined />, label: withNewBadge('/references/grep-sed-awk', l['grep-sed-awk'], l) },
        { key: '/references/jq-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/jq-cheatsheet', l['jq-cheatsheet'], l) },
        { key: '/references/bash-scripting', icon: <CodeOutlined />, label: l['bash-scripting'] },
        { key: '/references/systemd-commands', icon: <ContainerOutlined />, label: withNewBadge('/references/systemd-commands', l['systemd-commands'], l) },
        { key: '/references/github-actions-cheatsheet', icon: <GithubOutlined />, label: withNewBadge('/references/github-actions-cheatsheet', l['github-actions-cheatsheet'], l) },
        { key: '/references/nginx-cheatsheet', icon: <GlobalOutlined />, label: withNewBadge('/references/nginx-cheatsheet', l['nginx-cheatsheet'], l) },
        { key: '/references/redis-commands', icon: <DatabaseOutlined />, label: withNewBadge('/references/redis-commands', l['redis-commands'], l) },
        { key: '/references/gh-cli-cheatsheet', icon: <GithubOutlined />, label: withNewBadge('/references/gh-cli-cheatsheet', l['gh-cli-cheatsheet'], l) },
        { key: '/references/typescript-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/typescript-cheatsheet', l['typescript-cheatsheet'], l) },
        { key: '/references/js-testing-cheatsheet', icon: <ExperimentOutlined />, label: withNewBadge('/references/js-testing-cheatsheet', l['js-testing-cheatsheet'], l) },
        { key: '/references/react-cheatsheet', icon: <CodeOutlined />, label: withNewBadge('/references/react-cheatsheet', l['react-cheatsheet'], l) },
        { key: '/references/tailwind-cheatsheet', icon: <BgColorsOutlined />, label: withNewBadge('/references/tailwind-cheatsheet', l['tailwind-cheatsheet'], l) },
        { key: '/references/css-selectors-cheatsheet', icon: <SelectOutlined />, label: withNewBadge('/references/css-selectors-cheatsheet', l['css-selectors-cheatsheet'], l) },
        { key: '/references/a11y-cheatsheet', icon: <SafetyOutlined />, label: withNewBadge('/references/a11y-cheatsheet', l['a11y-cheatsheet'], l) },
        { key: '/references/jwt-claims-cheatsheet', icon: <KeyOutlined />, label: withNewBadge('/references/jwt-claims-cheatsheet', l['jwt-claims-cheatsheet'], l) },
      ],
    },
    {
      key: 'group-extras',
      icon: <CalendarOutlined />,
      label: l.extras,
      children: [
        { key: '/extras/days-until', label: l['days-until'] },
        { key: '/extras/team-roulette', label: withNewBadge('/extras/team-roulette', l['team-roulette'], l) },
        { key: '/extras/pomodoro-timer', icon: <FieldTimeOutlined />, label: withNewBadge('/extras/pomodoro-timer', l['pomodoro-timer'], l) },
        { key: '/extras/uuid-collision-simulator', icon: <ExperimentOutlined />, label: withNewBadge('/extras/uuid-collision-simulator', l['uuid-collision-simulator'], l) },
        { key: '/extras/sorting-visualizer', icon: <OrderedListOutlined />, label: withNewBadge('/extras/sorting-visualizer', l['sorting-visualizer'], l) },
        { key: '/extras/typing-speed-test', icon: <FontSizeOutlined />, label: withNewBadge('/extras/typing-speed-test', l['typing-speed-test'], l) },
      ],
    },
  ]
}

const MOBILE_MENU_OPEN_KEYS = [
  'group-tools', 'group-styles', 'group-snippets', 'group-frontend', 'group-apis',
  'group-devops', 'group-database', 'group-cloud', 'group-security', 'group-data',
  'group-network', 'group-ai', 'group-mobile', 'group-text', 'group-references', 'group-extras',
]

export default function AppLayout() {
  const [collapsed, setCollapsed] = useState(false)
  const [mobileNavOpen, setMobileNavOpen] = useState(false)
  const navigate = useNavigate()
  const location = useLocation()
  const { lang, setLang } = useLanguage()
  const { token: { colorBgContainer, borderRadiusLG } } = theme.useToken()
  const contentRef = useRef(null)
  // Abaixo de 768px o Sider fixo não cabe — vira um Drawer sobreposto,
  // aberto só sob demanda pelo botão de hambúrguer do header.
  const isMobile = useMediaQuery('(max-width: 768px)')

  // Sincroniza NEW_ITEM_KEYS com os 24 itens mais recentes (ver
  // useNewItemKeys.js) antes de montar o menu — não precisamos do valor de
  // retorno aqui, só que o efeito rode e force este componente (e a
  // HomePage, filha dele) a re-renderizar quando os dados chegarem.
  useNewItemKeys()
  useVisitTracker()

  const menuItems = buildMenuItems(LABELS[lang])

  // O menu (Sider/Drawer) e o conteúdo rolam em containers separados — ao
  // trocar de rota, o scroll do conteúdo precisa voltar pro topo mesmo que o
  // menu continue rolado onde o usuário clicou. No mobile, a troca de rota
  // também fecha o drawer de navegação sozinha.
  useEffect(() => {
    contentRef.current?.scrollTo(0, 0)
    setMobileNavOpen(false)
  }, [location.pathname])

  const handleMenuClick = ({ key }) => {
    if (key.startsWith('/')) navigate(key)
  }

  const navMenu = (
    <Menu
      theme="dark"
      mode="inline"
      selectedKeys={[location.pathname]}
      defaultOpenKeys={MOBILE_MENU_OPEN_KEYS}
      items={menuItems}
      onClick={handleMenuClick}
    />
  )

  return (
    <Layout style={{ height: '100vh' }}>
      {isMobile ? (
        <Drawer
          placement="left"
          closable={false}
          onClose={() => setMobileNavOpen(false)}
          open={mobileNavOpen}
          width="min(80vw, 300px)"
          styles={{ body: { padding: 0, background: '#001529' } }}
        >
          <div style={{
            height: 32,
            margin: 16,
            display: 'flex',
            alignItems: 'center',
            color: '#fff',
            fontWeight: 700,
          }}>
            DevTools
          </div>
          {navMenu}
        </Drawer>
      ) : (
        <Sider trigger={null} collapsible collapsed={collapsed} style={{ height: '100vh', overflow: 'auto' }}>
          <div style={{
            height: 32,
            margin: 16,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: '#fff',
            fontWeight: 700,
            overflow: 'hidden',
            whiteSpace: 'nowrap',
          }}>
            {collapsed ? 'DT' : 'DevTools'}
          </div>
          {navMenu}
        </Sider>
      )}
      <Layout style={{ height: '100vh' }}>
        <Header style={{
          padding: '0 12px',
          background: colorBgContainer,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: 8,
        }}>
          {React.createElement(
            isMobile ? MenuUnfoldOutlined : (collapsed ? MenuUnfoldOutlined : MenuFoldOutlined),
            {
              onClick: () => (isMobile ? setMobileNavOpen(true) : setCollapsed(!collapsed)),
              style: { fontSize: 18, cursor: 'pointer', padding: 8, margin: -8 },
            }
          )}
          <Segmented
            value={lang}
            onChange={setLang}
            options={[
              { label: 'PT', value: 'pt' },
              { label: 'EN', value: 'en' },
            ]}
          />
        </Header>
        <Content style={{
          margin: isMobile ? 12 : 24,
          padding: isMobile ? 12 : 24,
          background: colorBgContainer,
          borderRadius: borderRadiusLG,
          minHeight: 0,
          overflow: 'hidden',
          display: 'flex',
          flexDirection: 'column',
        }}>
          <div ref={contentRef} style={{ overflow: 'auto', flex: 1 }}>
            <Outlet />
          </div>
        </Content>
      </Layout>
      <BugReportWidget />
    </Layout>
  )
}
