// Dados do cheat sheet de seletores CSS — compartilhado entre a página e
// eventuais testes. Cada entrada tem o snippet, a categoria e descrições em
// português e inglês.

export const CATEGORIES = [
  'basic',
  'combinators',
  'attributes',
  'pseudo-structural',
  'pseudo-state',
  'pseudo-nav',
  'pseudo-elements',
  'advanced',
]

export const CATEGORY_COLOR = {
  basic: 'blue',
  combinators: 'green',
  attributes: 'cyan',
  'pseudo-structural': 'purple',
  'pseudo-state': 'volcano',
  'pseudo-nav': 'geekblue',
  'pseudo-elements': 'magenta',
  advanced: 'gold',
}

export const labelOf = {
  basic: { pt: 'Básicos', en: 'Basic' },
  combinators: { pt: 'Combinadores', en: 'Combinators' },
  attributes: { pt: 'Atributos', en: 'Attributes' },
  'pseudo-structural': { pt: 'Pseudo-classes estruturais', en: 'Structural pseudo-classes' },
  'pseudo-state': { pt: 'Pseudo-classes de estado', en: 'State pseudo-classes' },
  'pseudo-nav': { pt: 'Pseudo-classes de navegação', en: 'Navigation pseudo-classes' },
  'pseudo-elements': { pt: 'Pseudo-elementos', en: 'Pseudo-elements' },
  advanced: { pt: 'Avançados', en: 'Advanced' },
}

export const ITEMS = [
  // ─── Básicos ─────────────────────────────────────────────────────────────
  { code: '*', cat: 'basic',
    pt: 'Seletor universal — casa com todos os elementos. Use com cuidado por performance.',
    en: 'Universal selector — matches every element. Use with care for performance.' },
  { code: 'p', cat: 'basic',
    pt: 'Seleciona todos os elementos <p>.',
    en: 'Selects all <p> elements.' },
  { code: '.button', cat: 'basic',
    pt: 'Seleciona elementos com a classe button.',
    en: 'Selects elements with the button class.' },
  { code: '#header', cat: 'basic',
    pt: 'Seleciona o elemento com id header. IDs devem ser únicos na página.',
    en: 'Selects the element with id header. IDs should be unique in the page.' },
  { code: 'div.container', cat: 'basic',
    pt: 'Elemento div que também tem a classe container (sem espaço entre eles).',
    en: 'A div element that also has the container class (no space between them).' },
  { code: 'h1, h2, h3', cat: 'basic',
    pt: 'Vírgula significa "ou": seleciona h1, h2 e h3 ao mesmo tempo.',
    en: 'Comma means "or": selects h1, h2 and h3 at the same time.' },

  // ─── Combinadores ────────────────────────────────────────────────────────
  { code: 'article p', cat: 'combinators',
    pt: 'Descendente: seleciona todo <p> dentro de <article>, em qualquer profundidade.',
    en: 'Descendant: selects every <p> inside <article>, at any depth.' },
  { code: 'ul > li', cat: 'combinators',
    pt: 'Filho direto: seleciona apenas <li> que são filhos imediatos de <ul>.',
    en: 'Direct child: selects only <li> elements that are immediate children of <ul>.' },
  { code: 'h2 + p', cat: 'combinators',
    pt: 'Irmão adjacente: seleciona o <p> que vem imediatamente após um <h2>.',
    en: 'Adjacent sibling: selects the <p> immediately following an <h2>.' },
  { code: 'h2 ~ p', cat: 'combinators',
    pt: 'Irmão geral: seleciona todos os <p> que são irmãos posteriores de um <h2>.',
    en: 'General sibling: selects all <p> siblings that come after an <h2>.' },

  // ─── Atributos ───────────────────────────────────────────────────────────
  { code: '[disabled]', cat: 'attributes',
    pt: 'Seleciona elementos que possuem o atributo disabled, independente do valor.',
    en: 'Selects elements that have the disabled attribute, regardless of value.' },
  { code: '[type="text"]', cat: 'attributes',
    pt: 'Seleciona elementos cujo atributo type é exatamente text.',
    en: 'Selects elements whose type attribute is exactly text.' },
  { code: '[class~="active"]', cat: 'attributes',
    pt: 'Casa quando a classe é uma das palavras separadas por espaço (útil em class).',
    en: 'Matches when the class is one of the whitespace-separated words (useful for class).' },
  { code: '[lang|="en"]', cat: 'attributes',
    pt: 'Casa com en ou valores começando com en- (ex: en-US).',
    en: 'Matches en or values starting with en- (e.g., en-US).' },
  { code: '[href^="https"]', cat: 'attributes',
    pt: 'Casa quando o atributo começa com https.',
    en: 'Matches when the attribute starts with https.' },
  { code: '[src$=".png"]', cat: 'attributes',
    pt: 'Casa quando o atributo termina com .png.',
    en: 'Matches when the attribute ends with .png.' },
  { code: '[title*="busca"]', cat: 'attributes',
    pt: 'Casa quando o atributo contém a substring busca.',
    en: 'Matches when the attribute contains the substring busca.' },
  { code: '[data-kind="primary" i]', cat: 'attributes',
    pt: 'Comparador case-insensitive: casa Primary, primary, PRIMARY etc.',
    en: 'Case-insensitive match: matches Primary, primary, PRIMARY, etc.' },

  // ─── Pseudo-classes estruturais ──────────────────────────────────────────
  { code: 'li:first-child', cat: 'pseudo-structural',
    pt: 'Primeiro filho do pai. Se o primeiro filho não for <li>, não casa.',
    en: 'First child of its parent. If the first child is not <li>, it does not match.' },
  { code: 'li:last-child', cat: 'pseudo-structural',
    pt: 'Último filho do pai.',
    en: 'Last child of its parent.' },
  { code: 'li:nth-child(2n+1)', cat: 'pseudo-structural',
    pt: 'Filhos ímpares. odd é alias para 2n+1; even para 2n.',
    en: 'Odd children. odd is alias for 2n+1; even for 2n.' },
  { code: 'li:nth-child(3)', cat: 'pseudo-structural',
    pt: 'Terceiro filho do pai.',
    en: 'Third child of its parent.' },
  { code: 'li:nth-last-child(2)', cat: 'pseudo-structural',
    pt: 'Penúltimo filho do pai.',
    en: 'Second-to-last child of its parent.' },
  { code: 'p:only-child', cat: 'pseudo-structural',
    pt: '<p> que é o único filho do seu pai.',
    en: 'A <p> that is the only child of its parent.' },
  { code: 'p:first-of-type', cat: 'pseudo-structural',
    pt: 'Primeiro <p> entre os irmãos, independente de outros tipos.',
    en: 'First <p> among siblings, regardless of other element types.' },
  { code: 'p:last-of-type', cat: 'pseudo-structural',
    pt: 'Último <p> entre os irmãos.',
    en: 'Last <p> among siblings.' },
  { code: 'p:nth-of-type(2)', cat: 'pseudo-structural',
    pt: 'Segundo <p> entre os irmãos.',
    en: 'Second <p> among siblings.' },
  { code: 'p:only-of-type', cat: 'pseudo-structural',
    pt: 'Único <p> entre os irmãos do pai.',
    en: 'The only <p> among the parent\'s siblings.' },
  { code: 'div:empty', cat: 'pseudo-structural',
    pt: 'Elemento sem filhos nem texto (espaços em branco contam como texto).',
    en: 'Element with no children or text (whitespace counts as text).' },

  // ─── Pseudo-classes de estado ────────────────────────────────────────────
  { code: 'a:hover', cat: 'pseudo-state',
    pt: 'Estado do cursor sobre o link/elemento.',
    en: 'Cursor-over state for a link/element.' },
  { code: 'input:focus', cat: 'pseudo-state',
    pt: 'Elemento que recebeu foco do teclado ou mouse.',
    en: 'Element that has received keyboard or mouse focus.' },
  { code: 'input:focus-visible', cat: 'pseudo-state',
    pt: 'Foco visível apenas quando navegado pelo teclado (melhor para acessibilidade).',
    en: 'Visible focus only when navigated by keyboard (better for accessibility).' },
  { code: 'button:active', cat: 'pseudo-state',
    pt: 'Momento exato do clique/toque no botão.',
    en: 'The exact moment of click/touch on the button.' },
  { code: 'input:checked', cat: 'pseudo-state',
    pt: 'Checkbox ou radio que está marcado.',
    en: 'Checkbox or radio that is checked.' },
  { code: 'input:disabled', cat: 'pseudo-state',
    pt: 'Campo desabilitado.',
    en: 'Disabled field.' },
  { code: 'input:enabled', cat: 'pseudo-state',
    pt: 'Campo habilitado (estado padrão).',
    en: 'Enabled field (default state).' },
  { code: 'input:valid', cat: 'pseudo-state',
    pt: 'Campo cujo valor atende às regras de validação HTML5.',
    en: 'Field whose value meets HTML5 validation rules.' },
  { code: 'input:invalid', cat: 'pseudo-state',
    pt: 'Campo cujo valor não atende às regras de validação.',
    en: 'Field whose value does not meet validation rules.' },
  { code: 'input:required', cat: 'pseudo-state',
    pt: 'Campo marcado como obrigatório.',
    en: 'Field marked as required.' },
  { code: 'input:optional', cat: 'pseudo-state',
    pt: 'Campo não obrigatório.',
    en: 'Field not marked as required.' },
  { code: 'input:read-only', cat: 'pseudo-state',
    pt: 'Campo que o usuário não pode editar.',
    en: 'Field the user cannot edit.' },
  { code: 'input:placeholder-shown', cat: 'pseudo-state',
    pt: 'Campo que ainda está exibindo o placeholder (não foi digitado nada).',
    en: 'Field still showing the placeholder (nothing typed yet).' },

  // ─── Pseudo-classes de navegação ───────────────────────────────────────
  { code: 'a:link', cat: 'pseudo-nav',
    pt: 'Link que ainda não foi visitado.',
    en: 'Link that has not been visited yet.' },
  { code: 'a:visited', cat: 'pseudo-nav',
    pt: 'Link que o usuário já visitou (privacidade limita os estilos aplicáveis).',
    en: 'Link the user has already visited (privacy limits applicable styles).' },
  { code: 'section:target', cat: 'pseudo-nav',
    pt: 'Elemento cujo id corresponde ao fragmento # da URL.',
    en: 'Element whose id matches the URL # fragment.' },
  { code: ':root', cat: 'pseudo-nav',
    pt: 'Elemento raiz do documento (<html>). Ideal para declarar CSS custom properties.',
    en: 'Root element of the document (<html>). Ideal for declaring CSS custom properties.' },
  { code: 'li:not(.active)', cat: 'pseudo-nav',
    pt: 'Elementos <li> que NÃO têm a classe active.',
    en: '<li> elements that do NOT have the active class.' },
  { code: ':is(h1, h2, h3) span', cat: 'pseudo-nav',
    pt: 'Agrupa seletores evitando repetição e simplificando especificidade.',
    en: 'Groups selectors avoiding repetition and simplifying specificity.' },
  { code: ':where(h1, h2, h3) span', cat: 'pseudo-nav',
    pt: 'Igual ao :is(), mas com especificidade zero.',
    en: 'Same as :is(), but with zero specificity.' },
  { code: 'article:has(img)', cat: 'pseudo-nav',
    pt: 'Seleciona <article> que contém pelo menos uma imagem (parent selector).',
    en: 'Selects <article> that contains at least one image (parent selector).' },

  // ─── Pseudo-elementos ────────────────────────────────────────────────────
  { code: '.quote::before', cat: 'pseudo-elements',
    pt: 'Insere conteúdo decorativo antes do elemento. Requer content.',
    en: 'Inserts decorative content before the element. Requires content.' },
  { code: '.quote::after', cat: 'pseudo-elements',
    pt: 'Insere conteúdo decorativo depois do elemento.',
    en: 'Inserts decorative content after the element.' },
  { code: 'p::first-line', cat: 'pseudo-elements',
    pt: 'Primeira linha de um bloco de texto.',
    en: 'First line of a text block.' },
  { code: 'p::first-letter', cat: 'pseudo-elements',
    pt: 'Primeira letra de um bloco de texto (capitular).',
    en: 'First letter of a text block (drop cap).' },
  { code: '::selection', cat: 'pseudo-elements',
    pt: 'Texto selecionado pelo usuário.',
    en: 'User-selected text.' },
  { code: 'input::placeholder', cat: 'pseudo-elements',
    pt: 'Texto de placeholder de um campo.',
    en: 'Placeholder text of a field.' },
  { code: 'li::marker', cat: 'pseudo-elements',
    pt: 'Marcador de item de lista (bullet ou número).',
    en: 'List item marker (bullet or number).' },
  { code: 'dialog::backdrop', cat: 'pseudo-elements',
    pt: 'Fundo escurecido de um <dialog> modal nativo.',
    en: 'Dimmed backdrop of a native modal <dialog>.' },

  // ─── Avançados ───────────────────────────────────────────────────────────
  { code: '[id="foo\\:bar"]', cat: 'advanced',
    pt: 'Escapa o caractere especial : dentro do valor de atributo.',
    en: 'Escapes the special : character inside the attribute value.' },
  { code: ':scope > li', cat: 'advanced',
    pt: 'Seleciona filhos diretos de <li> relativos ao escopo atual (útil em APIs DOM).',
    en: 'Selects direct <li> children relative to the current scope (useful in DOM APIs).' },
  { code: 'col.selected || td', cat: 'advanced',
  pt: 'Combinador de coluna (CSS Grid): células pertencentes a uma coluna selecionada.',
    en: 'Column combinator (CSS Grid): cells belonging to a selected column.' },
  { code: 'custom-element::part(button)', cat: 'advanced',
    pt: 'Estiliza uma parte exposta de um Web Component via Shadow DOM.',
    en: 'Styles an exposed part of a Web Component via Shadow DOM.' },
  { code: 'slot::slotted(img)', cat: 'advanced',
    pt: 'Estiliza elementos slotted em um slot de Web Component.',
    en: 'Styles slotted elements inside a Web Component slot.' },
]
