// Dados da referência de Design Patterns.
// Mantido 100% client-side; nenhum dado sai do navegador.

export const CATEGORIES = ['creational', 'structural', 'behavioral', 'architectural']

export const CATEGORY_COLOR = {
  creational: 'blue',
  structural: 'cyan',
  behavioral: 'purple',
  architectural: 'geekblue',
}

export const CATEGORY_LABEL = {
  creational: { pt: 'Criacionais', en: 'Creational' },
  structural: { pt: 'Estruturais', en: 'Structural' },
  behavioral: { pt: 'Comportamentais', en: 'Behavioral' },
  architectural: { pt: 'Arquiteturais', en: 'Architectural' },
}

export const ITEMS = [
  // ─── Criacionais ────────────────────────────────────────────────────────
  {
    cat: 'creational',
    name: { pt: 'Singleton', en: 'Singleton' },
    code: [
      'class Singleton {',
      '  static #instance',
      '  static getInstance() {',
      '    if (!this.#instance) this.#instance = new Singleton()',
      '    return this.#instance',
      '  }',
      '}',
      'const a = Singleton.getInstance()',
      'const b = Singleton.getInstance()',
      'console.log(a === b) // true',
    ].join('\n'),
    pt: 'Garante que uma classe tenha apenas uma instância e fornece um ponto global de acesso a ela. Útil para conexões, caches e configurações compartilhadas.',
    en: 'Ensures a class has only one instance and provides a global point of access to it. Useful for connections, caches and shared configurations.',
  },
  {
    cat: 'creational',
    name: { pt: 'Factory Method', en: 'Factory Method' },
    code: [
      'class NotificationFactory {',
      "  create(channel) {",
      "    if (channel === 'email') return new EmailNotification()",
      "    if (channel === 'sms') return new SmsNotification()",
      "    throw new Error('Unknown channel')",
      '  }',
      '}',
      'const factory = new NotificationFactory()',
      'const notifier = factory.create("email")',
      'notifier.send("Hello")',
    ].join('\n'),
    pt: 'Delega a criação de objetos para subclasses ou métodos especializados, permitindo que o código cliente use uma interface comum sem saber a classe concreta.',
    en: 'Delegates object creation to subclasses or specialized methods, letting client code use a common interface without knowing the concrete class.',
  },
  {
    cat: 'creational',
    name: { pt: 'Abstract Factory', en: 'Abstract Factory' },
    code: [
      'class DarkThemeFactory {',
      '  createButton() { return new DarkButton() }',
      '  createInput() { return new DarkInput() }',
      '}',
      'class LightThemeFactory {',
      '  createButton() { return new LightButton() }',
      '  createInput() { return new LightInput() }',
      '}',
      'function renderForm(factory) {',
      '  return { button: factory.createButton(), input: factory.createInput() }',
      '}',
    ].join('\n'),
    pt: 'Cria famílias de objetos relacionados sem especificar classes concretas. Ideal para temas, kits de UI ou drivers de banco que precisam permanecer consistentes.',
    en: 'Creates families of related objects without specifying concrete classes. Ideal for themes, UI kits or database drivers that must remain consistent.',
  },
  {
    cat: 'creational',
    name: { pt: 'Builder', en: 'Builder' },
    code: [
      'class QueryBuilder {',
      '  constructor() { this.parts = [] }',
      '  select(cols) {',
      '    this.parts.push(`SELECT ${cols}`)',
      '    return this',
      '  }',
      '  from(table) {',
      '    this.parts.push(`FROM ${table}`)',
      '    return this',
      '  }',
      '  build() { return this.parts.join(" ") }',
      '}',
      'const sql = new QueryBuilder().select("*").from("users").build()',
    ].join('\n'),
    pt: 'Separa a construção de um objeto complexo da sua representação, permitindo criar diferentes variantes passo a passo com um método fluent.',
    en: 'Separates the construction of a complex object from its representation, letting you create different variants step by step with a fluent interface.',
  },
  {
    cat: 'creational',
    name: { pt: 'Prototype', en: 'Prototype' },
    code: [
      'class Shape {',
      '  clone() {',
      '    return Object.assign(Object.create(Object.getPrototypeOf(this)), this)',
      '  }',
      '}',
      'const circle = new Shape()',
      'circle.radius = 10',
      'const copy = circle.clone()',
    ].join('\n'),
    pt: 'Cria novos objetos copiando um protótipo existente. Útil quando a inicialização do zero é cara ou quando se quer preservar o estado de um objeto.',
    en: 'Creates new objects by copying an existing prototype. Useful when initialization from scratch is expensive or when you want to preserve an object state.',
  },

  // ─── Estruturais ──────────────────────────────────────────────────────────
  {
    cat: 'structural',
    name: { pt: 'Adapter', en: 'Adapter' },
    code: [
      'class OldPrinter {',
      '  print(text) { console.log(text) }',
      '}',
      'class PrinterAdapter {',
      '  constructor(printer) { this.printer = printer }',
      '  write(data) { this.printer.print(data) }',
      '}',
      'const modern = new PrinterAdapter(new OldPrinter())',
      'modern.write("hello")',
    ].join('\n'),
    pt: 'Permite que classes com interfaces incompatíveis trabalhem juntas, convertendo a interface de uma classe em outra esperada pelo cliente.',
    en: 'Lets classes with incompatible interfaces work together by converting the interface of one class into another expected by the client.',
  },
  {
    cat: 'structural',
    name: { pt: 'Bridge', en: 'Bridge' },
    code: [
      'class Renderer {',
      '  renderCircle(radius) { /* ... */ }',
      '}',
      'class VectorRenderer extends Renderer { /* ... */ }',
      'class RasterRenderer extends Renderer { /* ... */ }',
      'class Shape {',
      '  constructor(renderer) { this.renderer = renderer }',
      '}',
      'class Circle extends Shape {',
      '  draw() { this.renderer.renderCircle(this.radius) }',
      '}',
    ].join('\n'),
    pt: 'Separa uma abstração da sua implementação para que ambas possam evoluir independentemente. Evita explosão de subclasses (ex.: VectorCircle, RasterCircle).',
    en: 'Separates an abstraction from its implementation so both can evolve independently. Prevents subclass explosions (e.g. VectorCircle, RasterCircle).',
  },
  {
    cat: 'structural',
    name: { pt: 'Composite', en: 'Composite' },
    code: [
      'class File {',
      '  constructor(name) { this.name = name }',
      '  getSize() { return 1 }',
      '}',
      'class Folder {',
      '  constructor() { this.children = [] }',
      '  add(child) { this.children.push(child) }',
      '  getSize() {',
      '    return this.children.reduce((s, c) => s + c.getSize(), 0)',
      '  }',
      '}',
    ].join('\n'),
    pt: 'Compõe objetos em estruturas de árvore para representar hierarquias parte-todo. Clientes tratam folhas e compostos de forma uniforme.',
    en: 'Composes objects into tree structures to represent part-whole hierarchies. Clients treat leaves and composites uniformly.',
  },
  {
    cat: 'structural',
    name: { pt: 'Decorator', en: 'Decorator' },
    code: [
      'class Coffee {',
      '  cost() { return 5 }',
      '}',
      'class Milk {',
      '  constructor(coffee) { this.coffee = coffee }',
      '  cost() { return this.coffee.cost() + 1 }',
      '}',
      'const drink = new Milk(new Coffee())',
      'console.log(drink.cost()) // 6',
    ].join('\n'),
    pt: 'Adiciona responsabilidades a um objeto dinamicamente, sem alterar o código da classe original. Uma alternativa flexível à herança.',
    en: 'Adds responsibilities to an object dynamically without changing the original class code. A flexible alternative to subclassing.',
  },
  {
    cat: 'structural',
    name: { pt: 'Facade', en: 'Facade' },
    code: [
      'class ComputerFacade {',
      '  constructor() {',
      '    this.cpu = new CPU()',
      '    this.memory = new Memory()',
      '    this.disk = new Disk()',
      '  }',
      '  start() {',
      '    this.cpu.freeze()',
      '    this.memory.load()',
      '    this.disk.read()',
      '    this.cpu.jump()',
      '  }',
      '}',
    ].join('\n'),
    pt: 'Fornece uma interface simplificada para um conjunto complexo de subsistemas, escondendo a complexidade e reduzindo o acoplamento.',
    en: 'Provides a simplified interface to a complex set of subsystems, hiding complexity and reducing coupling.',
  },
  {
    cat: 'structural',
    name: { pt: 'Flyweight', en: 'Flyweight' },
    code: [
      'const glyphCache = new Map()',
      'function getGlyph(char) {',
      '  if (!glyphCache.has(char)) {',
      "    glyphCache.set(char, { char, font: 'Arial' })",
      '  }',
      '  return glyphCache.get(char)',
      '}',
      'const a1 = getGlyph("a")',
      'const a2 = getGlyph("a")',
      'console.log(a1 === a2) // true',
    ].join('\n'),
    pt: 'Compartilha objetos leves para minimizar o uso de memória quando muitas instâncias semelhantes são necessárias (texto, sprites, conexões).',
    en: 'Shares lightweight objects to minimize memory usage when many similar instances are needed (text, sprites, connections).',
  },
  {
    cat: 'structural',
    name: { pt: 'Proxy', en: 'Proxy' },
    code: [
      'class RealImage {',
      '  constructor(src) { this.src = src; this.load() }',
      '}',
      'class ImageProxy {',
      '  constructor(src) { this.src = src }',
      '  display() {',
      '    if (!this.real) this.real = new RealImage(this.src)',
      '    this.real.display()',
      '  }',
      '}',
    ].join('\n'),
    pt: 'Controla o acesso a um objeto, adicionando lazy loading, cache, controle de permissões ou logging sem modificar o objeto real.',
    en: 'Controls access to an object, adding lazy loading, caching, permission control or logging without modifying the real object.',
  },

  // ─── Comportamentais ────────────────────────────────────────────────────
  {
    cat: 'behavioral',
    name: { pt: 'Chain of Responsibility', en: 'Chain of Responsibility' },
    code: [
      'class Handler {',
      '  setNext(next) { this.next = next; return next }',
      '  handle(req) { return this.next?.handle(req) }',
      '}',
      'class AuthHandler extends Handler {',
      '  handle(req) {',
      '    if (!req.token) return "Unauthorized"',
      '    return super.handle(req)',
      '  }',
      '}',
    ].join('\n'),
    pt: 'Permite passar uma requisição por uma cadeia de handlers até que um a processe. Desacopla remetente e receptores.',
    en: 'Lets a request pass through a chain of handlers until one processes it. Decouples sender and receivers.',
  },
  {
    cat: 'behavioral',
    name: { pt: 'Command', en: 'Command' },
    code: [
      'class Light {',
      '  on() { console.log("on") }',
      '  off() { console.log("off") }',
      '}',
      'class LightOnCommand {',
      '  constructor(light) { this.light = light }',
      '  execute() { this.light.on() }',
      '  undo() { this.light.off() }',
      '}',
      'const remote = new LightOnCommand(new Light())',
      'remote.execute()',
    ].join('\n'),
    pt: 'Encapsula uma requisição como um objeto, permitindo parametrizar ações, enfileirar jobs, fazer undo/redo e desacoplar invocador do receptor.',
    en: 'Encapsulates a request as an object, letting you parameterize actions, queue jobs, implement undo/redo and decouple invoker from receiver.',
  },
  {
    cat: 'behavioral',
    name: { pt: 'Iterator', en: 'Iterator' },
    code: [
      'class Playlist {',
      '  constructor() { this.songs = [] }',
      '  [Symbol.iterator]() {',
      '    let i = 0',
      '    return {',
      '      next: () => ({',
      '        value: this.songs[i],',
      '        done: i++ >= this.songs.length',
      '      })',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    pt: 'Fornece uma forma de acessar elementos de uma coleção sequencialmente sem expor a sua representação interna.',
    en: 'Provides a way to access elements of a collection sequentially without exposing its internal representation.',
  },
  {
    cat: 'behavioral',
    name: { pt: 'Observer', en: 'Observer' },
    code: [
      'class Subject {',
      '  constructor() { this.observers = [] }',
      '  subscribe(fn) { this.observers.push(fn) }',
      '  notify(data) { this.observers.forEach((fn) => fn(data)) }',
      '}',
      'const news = new Subject()',
      'news.subscribe((data) => console.log(data))',
      'news.notify("New article")',
    ].join('\n'),
    pt: 'Define uma dependência um-para-muitos entre objetos: quando um muda, todos os dependentes são notificados automaticamente.',
    en: 'Defines a one-to-many dependency between objects: when one changes, all dependents are notified automatically.',
  },
  {
    cat: 'behavioral',
    name: { pt: 'Strategy', en: 'Strategy' },
    code: [
      'class PayPalStrategy {',
      '  pay(amount) { console.log(`PayPal $${amount}`) }',
      '}',
      'class CreditCardStrategy {',
      '  pay(amount) { console.log(`Card $${amount}`) }',
      '}',
      'class Checkout {',
      '  setStrategy(strategy) { this.strategy = strategy }',
      '  pay(amount) { this.strategy.pay(amount) }',
      '}',
    ].join('\n'),
    pt: 'Define uma família de algoritmos intercambiáveis e os torna independentes dos clientes que os usam.',
    en: 'Defines a family of interchangeable algorithms and makes them independent from the clients that use them.',
  },
  {
    cat: 'behavioral',
    name: { pt: 'Template Method', en: 'Template Method' },
    code: [
      'class DataParser {',
      '  parse(file) {',
      '    this.open(file)',
      '    this.read()',
      '    this.close()',
      '  }',
      '  open(file) { /* default */ }',
      '  close() { /* default */ }',
      '}',
      'class CsvParser extends DataParser {',
      '  read() { /* parse CSV */ }',
      '}',
    ].join('\n'),
    pt: 'Define o esqueleto de um algoritmo numa classe base, permitindo que subclasses sobrescrevam etapas específicas sem alterar a estrutura.',
    en: 'Defines the skeleton of an algorithm in a base class, letting subclasses override specific steps without changing the structure.',
  },
  {
    cat: 'behavioral',
    name: { pt: 'State', en: 'State' },
    code: [
      'class DraftState {',
      '  review() { return new ReviewState() }',
      '}',
      'class ReviewState {',
      '  approve() { return new PublishedState() }',
      '}',
      'class Document {',
      '  constructor() { this.state = new DraftState() }',
      '  publish() {',
      "    if (this.state.approve) this.state = this.state.approve()",
      '  }',
      '}',
    ].join('\n'),
    pt: 'Permite que um objeto altere seu comportamento quando o seu estado interno muda, parecendo que mudou de classe.',
    en: 'Lets an object alter its behavior when its internal state changes, appearing as if it changed class.',
  },
  {
    cat: 'behavioral',
    name: { pt: 'Visitor', en: 'Visitor' },
    code: [
      'class Visitor {',
      '  visitDog(dog) { console.log("dog") }',
      '  visitCat(cat) { console.log("cat") }',
      '}',
      'class Dog {',
      '  accept(visitor) { visitor.visitDog(this) }',
      '}',
      'const zoo = [new Dog()]',
      'zoo.forEach((animal) => animal.accept(new Visitor()))',
    ].join('\n'),
    pt: 'Separa um algoritmo dos elementos sobre os quais ele opera. Útil para adicionar operações a uma hierarquia de objetos sem modificá-la.',
    en: 'Separates an algorithm from the objects it operates on. Useful for adding operations to an object hierarchy without modifying it.',
  },
  {
    cat: 'behavioral',
    name: { pt: 'Mediator', en: 'Mediator' },
    code: [
      'class ChatRoom {',
      '  constructor() { this.users = [] }',
      '  join(user) { this.users.push(user) }',
      '  send(message, from) {',
      '    this.users.forEach((u) => u.receive(message, from))',
      '  }',
      '}',
    ].join('\n'),
    pt: 'Define um objeto central que coordena a comunicação entre componentes, reduzindo o acoplamento direto entre eles.',
    en: 'Defines a central object that coordinates communication between components, reducing direct coupling among them.',
  },
  {
    cat: 'behavioral',
    name: { pt: 'Memento', en: 'Memento' },
    code: [
      'class Editor {',
      '  setContent(text) { this.content = text }',
      '  save() { return new Memento(this.content) }',
      '  restore(m) { this.content = m.content }',
      '}',
      'class Memento {',
      '  constructor(content) { this.content = content }',
      '}',
      'const editor = new Editor()',
      'editor.setContent("v1")',
      'const backup = editor.save()',
    ].join('\n'),
    pt: 'Captura e externaliza o estado interno de um objeto sem violar o encapsulamento, possibilitando restaurá-lo depois.',
    en: 'Captures and externalizes an object internal state without breaking encapsulation, so it can be restored later.',
  },

  // ─── Arquiteturais / outros ─────────────────────────────────────────────
  {
    cat: 'architectural',
    name: { pt: 'Dependency Injection', en: 'Dependency Injection' },
    code: [
      'class Service {',
      '  greet() { return "hi" }',
      '}',
      'class Controller {',
      '  constructor(service) { this.service = service }',
      '  hello() { return this.service.greet() }',
      '}',
      'const app = new Controller(new Service())',
      'console.log(app.hello())',
    ].join('\n'),
    pt: 'Injeta dependências de fora em vez de o objeto criá-las, facilitando testes, substituição de implementações e desacoplamento.',
    en: 'Injects dependencies from outside instead of letting the object create them, making tests, swapping implementations and decoupling easier.',
  },
  {
    cat: 'architectural',
    name: { pt: 'Repository', en: 'Repository' },
    code: [
      'class UserRepository {',
      '  constructor(db) { this.db = db }',
      '  findById(id) {',
      "    return this.db.query('SELECT * FROM users WHERE id = ?', [id])",
      '  }',
      '  save(user) {',
      '    this.db.query("INSERT ...", [user])',
      '  }',
      '}',
    ].join('\n'),
    pt: 'Abstrai a camada de persistência, expondo operações de domínio como se a coleção de entidades estivesse em memória.',
    en: 'Abstracts the persistence layer, exposing domain operations as if the entity collection were in memory.',
  },
  {
    cat: 'architectural',
    name: { pt: 'Unit of Work', en: 'Unit of Work' },
    code: [
      'class UnitOfWork {',
      '  constructor() {',
      '    this.new = []',
      '    this.dirty = []',
      '    this.deleted = []',
      '  }',
      '  registerNew(entity) { this.new.push(entity) }',
      '  registerDirty(entity) { this.dirty.push(entity) }',
      '  registerDeleted(entity) { this.deleted.push(entity) }',
      '  commit() { /* insert, update, delete */ }',
      '}',
    ].join('\n'),
    pt: 'Agrupa operações de escrita numa única transação, garantindo consistência e evitando múltiplas idas ao banco.',
    en: 'Groups write operations into a single transaction, ensuring consistency and avoiding multiple round trips to the database.',
  },
  {
    cat: 'architectural',
    name: { pt: 'MVC', en: 'MVC' },
    code: [
      'class Model {',
      '  getData() { return [1, 2] }',
      '}',
      'class View {',
      '  render(data) { console.log(data) }',
      '}',
      'class Controller {',
      '  constructor(model, view) { this.model = model; this.view = view }',
      '  show() { this.view.render(this.model.getData()) }',
      '}',
      'new Controller(new Model(), new View()).show()',
    ].join('\n'),
    pt: 'Separa a aplicação em Model (dados), View (apresentação) e Controller (lógica de entrada), promovendo organização e testabilidade.',
    en: 'Separates the application into Model (data), View (presentation) and Controller (input logic), promoting organization and testability.',
  },
  {
    cat: 'architectural',
    name: { pt: 'Circuit Breaker', en: 'Circuit Breaker' },
    code: [
      'class CircuitBreaker {',
      '  constructor(fn) {',
      '    this.fn = fn',
      '    this.failures = 0',
      '    this.threshold = 5',
      "    this.state = 'CLOSED'",
      '  }',
      '  async call(...args) {',
      "    if (this.state === 'OPEN') throw new Error('Open')",
      '    try {',
      '      const result = await this.fn(...args)',
      '      this.failures = 0',
      '      return result',
      '    } catch (e) {',
      '      if (++this.failures >= this.threshold) this.state = "OPEN"',
      '      throw e',
      '    }',
      '  }',
      '}',
    ].join('\n'),
    pt: 'Evita chamadas repetidas a um serviço falho, abrindo o circuito após um limite de erros e protegendo o sistema em cascata.',
    en: 'Prevents repeated calls to a failing service, opening the circuit after an error threshold and protecting the system from cascading failures.',
  },
]
