const PRESETS = {
  minimum: {
    name: {
      pt: 'Mínimo',
      en: 'Minimum',
    },
    description: {
      pt: 'Normalização básica de quebras de linha e marcação de binários.',
      en: 'Basic line ending normalization and binary marking.',
    },
    lines: [
      '# Normalize line endings automatically',
      '* text=auto',
      '',
      '# Mark common binary files',
      '*.png binary',
      '*.jpg binary',
      '*.jpeg binary',
      '*.gif binary',
      '*.ico binary',
      '*.webp binary',
      '*.pdf binary',
      '*.zip binary',
      '*.tar.gz binary',
      '*.mp4 binary',
      '*.mp3 binary',
    ],
  },
  strictLf: {
    name: {
      pt: 'LF Estrito',
      en: 'Strict LF',
    },
    description: {
      pt: 'Força LF em scripts e configurações, útil para times mistos Windows/Unix.',
      en: 'Forces LF on scripts and configs, useful for mixed Windows/Unix teams.',
    },
    lines: [
      '# Force LF line endings on checkout for scripts and configs',
      '*.sh text eol=lf',
      '*.bash text eol=lf',
      '*.zsh text eol=lf',
      '*.py text eol=lf',
      '*.rb text eol=lf',
      '*.js text eol=lf',
      '*.jsx text eol=lf',
      '*.ts text eol=lf',
      '*.tsx text eol=lf',
      '*.json text eol=lf',
      '*.yml text eol=lf',
      '*.yaml text eol=lf',
      '*.md text eol=lf',
      '*.xml text eol=lf',
      '*.conf text eol=lf',
      '*.sh eol=lf',
      '',
      '# Windows-only files can keep CRLF',
      '*.bat text eol=crlf',
      '*.cmd text eol=crlf',
      '*.ps1 text eol=crlf',
    ],
  },
  node: {
    name: {
      pt: 'Node.js',
      en: 'Node.js',
    },
    description: {
      pt: 'Regras comuns para projetos Node/npm: lockfiles, YAML, scripts shell.',
      en: 'Common rules for Node/npm projects: lockfiles, YAML, shell scripts.',
    },
    lines: [
      '# Normalize line endings automatically',
      '* text=auto',
      '',
      '# Source files',
      '*.js text eol=lf',
      '*.jsx text eol=lf',
      '*.ts text eol=lf',
      '*.tsx text eol=lf',
      '*.mjs text eol=lf',
      '*.cjs text eol=lf',
      '*.json text eol=lf',
      '*.css text eol=lf',
      '*.scss text eol=lf',
      '*.html text eol=lf',
      '',
      '# Config / data files',
      '*.yml text eol=lf',
      '*.yaml text eol=lf',
      '*.toml text eol=lf',
      '*.ini text eol=lf',
      '*.env* text eol=lf',
      '.editorconfig text eol=lf',
      '',
      '# Lockfiles: keep ours on merge conflicts',
      'package-lock.json merge=ours text eol=lf',
      'yarn.lock merge=ours text eol=lf',
      'pnpm-lock.yaml merge=ours text eol=lf',
      'bun.lockb merge=ours binary',
      '',
      '# Scripts',
      '*.sh text eol=lf',
      '*.bash text eol=lf',
      '*.zsh text eol=lf',
      '',
      '# Binary assets',
      '*.png binary',
      '*.jpg binary',
      '*.jpeg binary',
      '*.gif binary',
      '*.ico binary',
      '*.webp binary',
      '*.svg text eol=lf',
      '*.woff binary',
      '*.woff2 binary',
      '*.ttf binary',
      '*.eot binary',
      '*.mp4 binary',
      '*.mp3 binary',
    ],
  },
  python: {
    name: {
      pt: 'Python',
      en: 'Python',
    },
    description: {
      pt: 'Regras para projetos Python: LF obrigatório, diffs específicos, binários.',
      en: 'Rules for Python projects: mandatory LF, specific diffs, binaries.',
    },
    lines: [
      '# Normalize line endings automatically',
      '* text=auto',
      '',
      '# Python source files',
      '*.py text eol=lf diff=python',
      '*.pyw text eol=lf diff=python',
      '*.pyi text eol=lf diff=python',
      '',
      '# Requirements and config files',
      'requirements*.txt text eol=lf',
      '*.cfg text eol=lf',
      '*.ini text eol=lf',
      '*.toml text eol=lf',
      '*.yaml text eol=lf',
      '*.yml text eol=lf',
      'Pipfile text eol=lf',
      'Pipfile.lock merge=ours text eol=lf',
      'poetry.lock merge=ours text eol=lf',
      '',
      '# Jupyter notebooks: diff as JSON',
      '*.ipynb text eol=lf diff=json',
      '',
      '# Virtual environments and caches',
      '.venv/** linguist-generated=true',
      'venv/** linguist-generated=true',
      '__pycache__/** linguist-generated=true',
      '*.pyc binary',
      '*.pyo binary',
      '*.pyd binary',
      '',
      '# Binary assets',
      '*.png binary',
      '*.jpg binary',
      '*.jpeg binary',
      '*.gif binary',
      '*.ico binary',
      '*.webp binary',
      '*.mp4 binary',
      '*.mp3 binary',
    ],
  },
  java: {
    name: {
      pt: 'Java',
      en: 'Java',
    },
    description: {
      pt: 'Regras para projetos Java/Kotlin/Gradle/Maven.',
      en: 'Rules for Java/Kotlin/Gradle/Maven projects.',
    },
    lines: [
      '# Normalize line endings automatically',
      '* text=auto',
      '',
      '# Source files',
      '*.java text eol=lf diff=java',
      '*.kt text eol=lf diff=kotlin',
      '*.kts text eol=lf diff=kotlin',
      '*.scala text eol=lf diff=scala',
      '*.groovy text eol=lf diff=groovy',
      '',
      '# Build files',
      '*.gradle text eol=lf',
      '*.gradle.kts text eol=lf',
      'pom.xml text eol=lf',
      'gradle.properties text eol=lf',
      'settings.gradle text eol=lf',
      '',
      '# Lock / wrapper files',
      'gradle-wrapper.jar binary',
      'gradlew text eol=lf',
      'gradlew.bat text eol=crlf',
      '',
      '# Binary assets',
      '*.jar binary',
      '*.war binary',
      '*.ear binary',
      '*.class binary',
      '*.png binary',
      '*.jpg binary',
      '*.jpeg binary',
      '*.gif binary',
      '*.ico binary',
      '*.webp binary',
    ],
  },
  web: {
    name: {
      pt: 'Web (HTML/CSS/JS)',
      en: 'Web (HTML/CSS/JS)',
    },
    description: {
      pt: 'Regras para sites e apps web: LF, diffs linguist e assets binários.',
      en: 'Rules for websites and web apps: LF, linguist diffs and binary assets.',
    },
    lines: [
      '# Normalize line endings automatically',
      '* text=auto',
      '',
      '# Web source files',
      '*.html text eol=lf diff=html',
      '*.htm text eol=lf diff=html',
      '*.css text eol=lf diff=css',
      '*.scss text eol=lf diff=css',
      '*.sass text eol=lf diff=css',
      '*.less text eol=lf diff=css',
      '*.js text eol=lf diff=javascript',
      '*.jsx text eol=lf diff=javascript',
      '*.mjs text eol=lf diff=javascript',
      '*.ts text eol=lf diff=javascript',
      '*.tsx text eol=lf diff=javascript',
      '*.vue text eol=lf diff=javascript',
      '*.svelte text eol=lf diff=javascript',
      '',
      '# Config / data files',
      '*.json text eol=lf',
      '*.yaml text eol=lf',
      '*.yml text eol=lf',
      '*.xml text eol=lf',
      '*.toml text eol=lf',
      '*.env* text eol=lf',
      '',
      '# Generated files (hide in diffs)',
      'dist/** linguist-generated=true',
      'build/** linguist-generated=true',
      '*.min.js linguist-generated=true',
      '*.min.css linguist-generated=true',
      '',
      '# Binary assets',
      '*.png binary',
      '*.jpg binary',
      '*.jpeg binary',
      '*.gif binary',
      '*.ico binary',
      '*.webp binary',
      '*.svg text eol=lf',
      '*.woff binary',
      '*.woff2 binary',
      '*.ttf binary',
      '*.eot binary',
      '*.mp4 binary',
      '*.mp3 binary',
      '*.webm binary',
    ],
  },
  docs: {
    name: {
      pt: 'Documentação',
      en: 'Documentation',
    },
    description: {
      pt: 'Regras para repositórios focados em Markdown e documentação.',
      en: 'Rules for Markdown and documentation-focused repositories.',
    },
    lines: [
      '# Normalize line endings automatically',
      '* text=auto',
      '',
      '# Documentation files',
      '*.md text eol=lf diff=markdown',
      '*.mdx text eol=lf diff=markdown',
      '*.txt text eol=lf',
      '*.rst text eol=lf',
      '*.adoc text eol=lf',
      '',
      '# GitHub / GitLab metadata',
      '*.yml text eol=lf',
      '*.yaml text eol=lf',
      'LICENSE text eol=lf',
      'CONTRIBUTING* text eol=lf',
      'CODE_OF_CONDUCT* text eol=lf',
      'CHANGELOG* text eol=lf',
      'README* text eol=lf',
      '',
      '# Exclude from exported archives',
      '.github/ export-ignore',
      'docs/ export-ignore',
      'examples/ export-ignore',
    ],
  },
  archives: {
    name: {
      pt: 'Arquivos & Binários',
      en: 'Archives & Binaries',
    },
    description: {
      pt: 'Marca uma grande lista de extensões como binárias para evitar diffs.',
      en: 'Marks a broad list of extensions as binary to avoid diffs.',
    },
    lines: [
      '# Treat common archive and binary formats as binary',
      '*.zip binary',
      '*.tar binary',
      '*.tar.gz binary',
      '*.tgz binary',
      '*.rar binary',
      '*.7z binary',
      '*.bz2 binary',
      '*.xz binary',
      '',
      '# Images',
      '*.png binary',
      '*.jpg binary',
      '*.jpeg binary',
      '*.gif binary',
      '*.bmp binary',
      '*.tiff binary',
      '*.webp binary',
      '*.ico binary',
      '*.svg text eol=lf',
      '',
      '# Audio / video',
      '*.mp3 binary',
      '*.ogg binary',
      '*.wav binary',
      '*.mp4 binary',
      '*.webm binary',
      '*.avi binary',
      '*.mov binary',
      '',
      '# Fonts',
      '*.woff binary',
      '*.woff2 binary',
      '*.ttf binary',
      '*.eot binary',
      '*.otf binary',
    ],
  },
}

export function getPresets(lang) {
  return Object.entries(PRESETS).map(([key, preset]) => ({
    key,
    name: preset.name[lang] || preset.name.en,
    description: preset.description[lang] || preset.description.en,
  }))
}

export function buildGitattributes(selectedKeys, lang) {
  const seen = new Set()
  const result = []

  selectedKeys.forEach((key) => {
    const preset = PRESETS[key]
    if (!preset) return
    if (result.length > 0) result.push('')
    result.push(`# ${preset.name[lang] || preset.name.en}`)
    if (preset.description[lang] || preset.description.en) {
      result.push(`# ${preset.description[lang] || preset.description.en}`)
    }
    preset.lines.forEach((line) => {
      if (line === '' || line.startsWith('#')) {
        result.push(line)
        return
      }
      if (seen.has(line)) return
      seen.add(line)
      result.push(line)
    })
  })

  return result.join('\n').trim()
}

export function getDefaultSelectedKeys() {
  return ['minimum']
}
