// Dados da referência de claims JWT (JSON Web Token).
// 100% client-side; textos em pt/en para suporte bilíngue da página.

export const CATEGORIES = [
  'registered',
  'time',
  'public',
  'private',
  'security',
]

export const CATEGORY_COLOR = {
  registered: 'blue',
  time: 'volcano',
  public: 'green',
  private: 'purple',
  security: 'red',
}

export const labelOf = {
  registered: { pt: 'Claims Registradas (RFC 7519)', en: 'Registered Claims (RFC 7519)' },
  time: { pt: 'Claims de Tempo', en: 'Time Claims' },
  public: { pt: 'Claims Públicas Comuns', en: 'Common Public Claims' },
  private: { pt: 'Claims Privadas / Customizadas', en: 'Private / Custom Claims' },
  security: { pt: 'Boas Práticas de Segurança', en: 'Security Best Practices' },
}

export const ITEMS = [
  // Registered claims
  {
    cat: 'registered',
    code: '"iss": "https://auth.example.com"',
    pt: 'Emissor (issuer). Identifica quem assinou o token. Sempre valide contra uma lista de emissores confiáveis.',
    en: 'Issuer. Identifies who issued the token. Always validate it against a trusted issuers list.',
  },
  {
    cat: 'registered',
    code: '"sub": "auth0|123456"',
    pt: 'Sujeito (subject). Identifica o principal do token — geralmente o ID do usuário. Deve ser único e estável dentro do emissor.',
    en: 'Subject. Identifies the principal of the token — usually the user ID. Must be unique and stable within the issuer.',
  },
  {
    cat: 'registered',
    code: '"aud": "https://api.example.com"',
    pt: 'Audiência (audience). Indica para qual serviço o token foi emitido. Recuse tokens cuja audiência não corresponda à sua API.',
    en: 'Audience. Indicates the service the token was issued for. Reject tokens whose audience does not match your API.',
  },
  {
    cat: 'registered',
    code: '"aud": ["api", "dashboard"]',
    pt: 'A audiência também pode ser um array. Sua API deve aceitar apenas se sua identidade estiver na lista.',
    en: 'The audience can also be an array. Your API should accept it only if its own identifier is in the list.',
  },
  {
    cat: 'registered',
    code: '"jti": "a1b2c3d4-e5f6-7890"',
    pt: 'JWT ID. Identificador único do token. Útil para listas de revogação (token deny-list) e prevenção de replay.',
    en: 'JWT ID. Unique identifier for the token. Useful for revocation lists (deny-lists) and replay prevention.',
  },
  {
    cat: 'registered',
    code: '"azp": "my-single-page-app"',
    pt: 'Authorized party (OIDC). Indica o client_id que solicitou o token. Ajuda a detectar uso indevido por aplicações não autorizadas.',
    en: 'Authorized party (OIDC). Indicates the client_id that requested the token. Helps detect misuse by unauthorized applications.',
  },
  {
    cat: 'registered',
    code: '"nonce": "n-0S6_WzA2M"',
    pt: 'Nonce (OIDC). Valor gerado pelo cliente e devolvido no ID token para mitigar ataques de replay no fluxo implícito/híbrido.',
    en: 'Nonce (OIDC). Value generated by the client and returned in the ID token to mitigate replay attacks in implicit/hybrid flows.',
  },
  {
    cat: 'registered',
    code: '"at_hash": "Xy0..."',
    pt: 'Access token hash (OIDC). Hash do access_token vinculado ao ID token, permitindo ao cliente validar que ambos pertencem ao mesmo fluxo.',
    en: 'Access token hash (OIDC). Hash of the access token bound to the ID token, letting the client validate they belong to the same flow.',
  },

  // Time claims
  {
    cat: 'time',
    code: '"iat": 1700000000',
    pt: 'Issued at. Timestamp (segundos desde Epoch) em que o token foi emitido. Opcional, mas recomendado para auditoria.',
    en: 'Issued at. Timestamp (seconds since Epoch) when the token was issued. Optional, but recommended for auditing.',
  },
  {
    cat: 'time',
    code: '"exp": 1700003600',
    pt: 'Expiration. Timestamp de expiração. O token não deve ser aceito após esse instante. Defina o menor tempo possível para o caso de uso.',
    en: 'Expiration timestamp. The token must not be accepted after this instant. Set the shortest feasible lifetime for the use case.',
  },
  {
    cat: 'time',
    code: '"nbf": 1700000000',
    pt: 'Not before. O token só deve ser aceito a partir deste timestamp. Útil para agendamento ou troca de chaves.',
    en: 'Not before. The token must not be accepted before this timestamp. Useful for scheduling or key rollover.',
  },
  {
    cat: 'time',
    code: '"auth_time": 1699999000',
    pt: 'Authentication time (OIDC). Momento em que o usuário se autenticou pela última vez. Diferente de iat quando há refresh.',
    en: 'Authentication time (OIDC). Moment when the user last authenticated. Differs from iat when there is a refresh.',
  },

  // Public claims
  {
    cat: 'public',
    code: '"name": "Ada Lovelace"',
    pt: 'Nome completo do usuário. Claim pública padronizada pelo OpenID Connect (profile scope).',
    en: 'Full name of the user. Public claim standardized by OpenID Connect (profile scope).',
  },
  {
    cat: 'public',
    code: '"email": "ada@example.com"',
    pt: 'Endereço de e-mail do usuário. Requer o email scope no OIDC; combine com email_verified antes de confiar.',
    en: 'User email address. Requires the email scope in OIDC; combine with email_verified before trusting it.',
  },
  {
    cat: 'public',
    code: '"email_verified": true',
    pt: 'Indica se o e-mail foi confirmado. Nunca trate email como verificado se esta claim for false ou ausente.',
    en: 'Indicates whether the email was confirmed. Never treat email as verified if this claim is false or missing.',
  },
  {
    cat: 'public',
    code: '"preferred_username": "ada"',
    pt: 'Nome de usuário preferido. Não garante unicidade global; valide antes de usá-lo como identificador.',
    en: 'Preferred username. Does not guarantee global uniqueness; validate it before using it as an identifier.',
  },
  {
    cat: 'public',
    code: '"picture": "https://cdn.example.com/avatar.png"',
    pt: 'URL da foto/avatar do usuário. A aplicação deve sanitizar e evitar renderização direta sem checagem de origem.',
    en: 'URL of the user picture/avatar. The application should sanitize it and avoid direct rendering without origin checks.',
  },
  {
    cat: 'public',
    code: '"roles": ["editor", "viewer"]',
    pt: 'Papéis (RBAC). Liste grupos de permissão; a API ainda deve verificar autorização no momento da ação.',
    en: 'Roles (RBAC). List permission groups; the API must still check authorization at the time of the action.',
  },
  {
    cat: 'public',
    code: '"permissions": ["posts:write", "posts:read"]',
    pt: 'Permissões finas (ABAC/scope). Prefera escopos no formato recurso:ação e valide cada endpoint.',
    en: 'Fine-grained permissions (ABAC/scope). Prefer resource:action format scopes and validate them on every endpoint.',
  },
  {
    cat: 'public',
    code: '"scope": "read write"',
    pt: 'Escopos OAuth 2.0 como string espaçada. Separe e valide cada escopo; nunca confie apenas na presença do token.',
    en: 'OAuth 2.0 scopes as a space-delimited string. Split and validate each scope; never rely only on the token presence.',
  },
  {
    cat: 'public',
    code: '"groups": ["engineering", "oncall"]',
    pt: 'Grupos de diretório (LDAP/AD). Útil para mapear permissões, mas pode crescer muito — evite tokens gigantes.',
    en: 'Directory groups (LDAP/AD). Useful for mapping permissions, but can grow large — avoid huge tokens.',
  },
  {
    cat: 'public',
    code: '"session_id": "sess_abc123"',
    pt: 'ID da sessão. Permite correlacionar o token a uma sessão no backend para logout centralizado ou auditoria.',
    en: 'Session ID. Lets the backend correlate the token with a session for centralized logout or auditing.',
  },

  // Private claims
  {
    cat: 'private',
    code: '"tenant_id": "tenant_42"',
    pt: 'Claim privada de exemplo para multitenancy. Use nomes curtos, claros e com prefixo do domínio para evitar colisões.',
    en: 'Example private claim for multitenancy. Use short, clear names with a domain prefix to avoid collisions.',
  },
  {
    cat: 'private',
    code: '"https://example.com/claims/plan": "pro"',
    pt: 'Namespace collision-resistant (recomendado pelo RFC). Ideal para claims específicas do seu domínio.',
    en: 'Collision-resistant namespace (recommended by the RFC). Ideal for claims specific to your domain.',
  },
  {
    cat: 'private',
    code: '"internal_invited_by": "user_99"',
    pt: 'Claim customizada de uso interno. Documente-a no contrato de API e mantenha-a estável para não quebrar consumidores.',
    en: 'Internal custom claim. Document it in the API contract and keep it stable so consumers do not break.',
  },
  {
    cat: 'private',
    code: '{ "x_": "deprecated" }',
    pt: 'Evite prefixos genéricos como x_ sem domínio. Prefira nomes descritivos e, quando exposto publicamente, namespace.',
    en: 'Avoid generic prefixes like x_ without a domain. Prefer descriptive names and, when exposed publicly, a namespace.',
  },

  // Security best practices
  {
    cat: 'security',
    code: '// Valide tudo antes de confiar\nverify(token, {\n  issuer: "https://auth.example.com",\n  audience: "https://api.example.com",\n  algorithms: ["RS256"]\n})',
    pt: 'Sempre valide issuer, audience, algoritmo, exp e nbf. Nunca aceite algoritmo none a menos que esteja em ambiente de teste isolado.',
    en: 'Always validate issuer, audience, algorithm, exp, and nbf. Never accept algorithm none unless in an isolated test environment.',
  },
  {
    cat: 'security',
    code: '// Não coloque segredos no payload\n{ "credit_card": "4111..." } // ❌',
    pt: 'JWTs assinados não são criptografados. Nunca coloque dados sensíveis (senhas, cartões, PII) no payload sem criptografia adicional (JWE).',
    en: 'Signed JWTs are not encrypted. Never put sensitive data (passwords, cards, PII) in the payload without additional encryption (JWE).',
  },
  {
    cat: 'security',
    code: '{\n  "sub": "user_123",\n  "roles": ["reader"],\n  "exp": 1700003600\n}',
    pt: 'Mantenha o payload enxuto. Tokens grandes aumentam o tráfego e podem estourar limites de cabeçalho/cookie.',
    en: 'Keep the payload lean. Large tokens increase traffic and may exceed header/cookie size limits.',
  },
  {
    cat: 'security',
    code: 'const leeway = 30 // segundos',
    pt: 'Adicione uma pequena folga de clock skew (costuma-se 30–60s) ao validar exp/nbf, mas não abuse dela para alongar a vida do token.',
    en: 'Add a small clock skew leeway (usually 30–60s) when validating exp/nbf, but do not abuse it to extend token lifetime.',
  },
  {
    cat: 'security',
    code: '"crit": ["b64"]',
    pt: 'Header claim crit lista extensões obrigatórias. Rejeite o token se você não entender alguma entrada dela.',
    en: 'Header claim crit lists mandatory extensions. Reject the token if you do not understand any of its entries.',
  },
  {
    cat: 'security',
    code: '{ "kid": "2024-08-13" }',
    pt: 'Key ID no header. Use kid para rotacionar chaves sem invalidar tokens antigos de imediato, desde que exp ainda seja válido.',
    en: 'Key ID in the header. Use kid to rotate keys without immediately invalidating old tokens, as long as exp is still valid.',
  },
  {
    cat: 'security',
    code: '// jti + deny-list\nawait redis.set(`deny:${jti}`, "1", "EX", ttl)',
    pt: 'Tokens stateless não podem ser revogados sozinhos. Para logout imediato, mantenha uma deny-list de jti até a expiração natural.',
    en: 'Stateless tokens cannot be revoked alone. For instant logout, keep a deny-list of jti values until their natural expiration.',
  },
]
