/**
 * Calculadora de orçamento de latência end-to-end.
 *
 * Cada etapa contribui com uma latência média (μ) e um desvio padrão (σ).
 * Como as latências de etapas independentes se somam, temos:
 *   μ_total = Σ μ_i
 *   σ_total = √(Σ σ_i²)
 *
 * Para um percentil-alvo normal usamos:
 *   P = μ_total + Z × σ_total
 */

export const PERCENTILE_Z = {
  p90: 1.2816,
  p95: 1.6449,
  p99: 2.3263,
  'p99.9': 3.0902,
}

export const PERCENTILE_OPTIONS = ['p90', 'p95', 'p99', 'p99.9']

export function formatNumber(value, digits = 2) {
  if (value === null || value === undefined || Number.isNaN(value)) return '—'
  if (!Number.isFinite(value)) return '∞'
  if (value === 0) return '0'
  const abs = Math.abs(value)
  if (abs < 0.001 || abs >= 1_000_000) {
    return value.toExponential(digits)
  }
  const fixed = value.toFixed(digits)
  return fixed.replace(/\.?0+$/, '')
}

function cleanNumber(v) {
  if (v === '' || v === undefined || v === null) return null
  const n = Number(v)
  return Number.isNaN(n) ? null : n
}

export function calculateBudget(steps, targetPercentile = 'p95') {
  const z = PERCENTILE_Z[targetPercentile] ?? PERCENTILE_Z.p95

  const cleaned = steps.map((s) => ({
    id: s.id,
    name: typeof s.name === 'string' ? s.name.trim() : '',
    mean: cleanNumber(s.mean),
    stdDev: cleanNumber(s.stdDev),
  }))

  if (cleaned.length === 0) {
    return {
      valid: false,
      error: 'EMPTY',
      totalMean: 0,
      totalStdDev: 0,
      targetPercentile,
      z,
      percentileLatency: 0,
      breakdown: [],
    }
  }

  const invalidStep = cleaned.findIndex(
    (s) => s.mean === null || s.mean < 0 || s.stdDev === null || s.stdDev < 0
  )

  if (invalidStep !== -1) {
    return {
      valid: false,
      error: 'INVALID_STEP',
      invalidStep,
      totalMean: 0,
      totalStdDev: 0,
      targetPercentile,
      z,
      percentileLatency: 0,
      breakdown: [],
    }
  }

  const totalMean = cleaned.reduce((sum, s) => sum + s.mean, 0)
  const varianceSum = cleaned.reduce((sum, s) => sum + s.stdDev * s.stdDev, 0)
  const totalStdDev = Math.sqrt(varianceSum)
  const percentileLatency = totalMean + z * totalStdDev

  const breakdown = cleaned.map((s) => {
    const contributionPct = totalMean === 0 ? 0 : (s.mean / totalMean) * 100
    const stepPercentile = s.mean + z * s.stdDev
    return {
      ...s,
      contributionPct,
      stepPercentile,
    }
  })

  // Etapa que mais contribui para a latência média.
  const biggestContributor = [...breakdown].sort(
    (a, b) => b.contributionPct - a.contributionPct
  )[0]

  return {
    valid: true,
    totalMean,
    totalStdDev,
    targetPercentile,
    z,
    percentileLatency,
    breakdown,
    biggestContributor,
  }
}

export function exportMarkdown(result, lang = 'pt') {
  if (!result.valid) {
    return lang === 'pt'
      ? 'Dados inválidos — verifique as etapas.'
      : 'Invalid data — check the steps.'
  }

  const t =
    lang === 'pt'
      ? {
          title: 'Orçamento de Latência End-to-End',
          target: 'Percentil-alvo',
          totalMean: 'Latência média total',
          totalStd: 'Desvio padrão total',
          percentile: 'Latência no percentil-alvo',
          breakdown: 'Breakdown por etapa',
          step: 'Etapa',
          mean: 'Média (ms)',
          std: 'σ (ms)',
          contribution: 'Contribuição',
          stepPercentile: 'Percentil da etapa',
          biggest: 'Maior contribuinte',
          generated: 'Gerado por devtools',
        }
      : {
          title: 'End-to-End Latency Budget',
          target: 'Target percentile',
          totalMean: 'Total mean latency',
          totalStd: 'Total standard deviation',
          percentile: 'Target percentile latency',
          breakdown: 'Breakdown by step',
          step: 'Step',
          mean: 'Mean (ms)',
          std: 'σ (ms)',
          contribution: 'Contribution',
          stepPercentile: 'Step percentile',
          biggest: 'Biggest contributor',
          generated: 'Generated by devtools',
        }

  const rows = result.breakdown
    .map(
      (s) =>
        `| ${s.name || '-'} | ${formatNumber(s.mean)} | ${formatNumber(
          s.stdDev
        )} | ${formatNumber(s.contributionPct)}% | ${formatNumber(
          s.stepPercentile
        )} |`
    )
    .join('\n')

  return `# ${t.title}

- **${t.target}:** ${result.targetPercentile.toUpperCase()} (Z = ${formatNumber(
    result.z
  )})
- **${t.totalMean}:** ${formatNumber(result.totalMean)} ms
- **${t.totalStd}:** ${formatNumber(result.totalStdDev)} ms
- **${t.percentile}:** ${formatNumber(result.percentileLatency)} ms
- **${t.biggest}:** ${result.biggestContributor?.name || '-'}

## ${t.breakdown}

| ${t.step} | ${t.mean} | ${t.std} | ${t.contribution} | ${t.stepPercentile} |
|---|---|---|---|---|
${rows}

_${t.generated}_
`
}

export function createStep(name = '', mean = 0, stdDev = 0) {
  return {
    id: `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
    name,
    mean,
    stdDev,
  }
}

export function getPresets(lang = 'pt') {
  const labels = {
    pt: {
      simpleWeb: 'Requisição web simples',
      ecommerceCheckout: 'Checkout de e-commerce',
      microservices: 'API em microserviços',
      videoStreaming: 'Streaming de vídeo',
      globalDatabase: 'Edge → DB global',
    },
    en: {
      simpleWeb: 'Simple web request',
      ecommerceCheckout: 'E-commerce checkout',
      microservices: 'Microservices API',
      videoStreaming: 'Video streaming',
      globalDatabase: 'Edge → global DB',
    },
  }

  const l = labels[lang] || labels.en

  return [
    {
      key: 'simpleWeb',
      label: l.simpleWeb,
      steps: [
        { name: lang === 'pt' ? 'DNS' : 'DNS', mean: 15, stdDev: 5 },
        { name: lang === 'pt' ? 'TCP + TLS' : 'TCP + TLS', mean: 60, stdDev: 20 },
        { name: lang === 'pt' ? 'Servidor' : 'Server', mean: 80, stdDev: 30 },
        { name: lang === 'pt' ? 'Banco de dados' : 'Database', mean: 25, stdDev: 10 },
      ],
    },
    {
      key: 'ecommerceCheckout',
      label: l.ecommerceCheckout,
      steps: [
        { name: lang === 'pt' ? 'CDN' : 'CDN', mean: 40, stdDev: 15 },
        { name: lang === 'pt' ? 'API Gateway' : 'API Gateway', mean: 30, stdDev: 10 },
        { name: lang === 'pt' ? 'Autenticação' : 'Authentication', mean: 60, stdDev: 20 },
        { name: lang === 'pt' ? 'Carrinho' : 'Cart', mean: 45, stdDev: 15 },
        { name: lang === 'pt' ? 'Pagamento' : 'Payment', mean: 200, stdDev: 50 },
        { name: lang === 'pt' ? 'Banco de dados' : 'Database', mean: 30, stdDev: 10 },
        { name: lang === 'pt' ? 'Webhook' : 'Webhook', mean: 120, stdDev: 40 },
      ],
    },
    {
      key: 'microservices',
      label: l.microservices,
      steps: [
        { name: lang === 'pt' ? 'Edge' : 'Edge', mean: 10, stdDev: 3 },
        { name: lang === 'pt' ? 'API Gateway' : 'API Gateway', mean: 25, stdDev: 8 },
        { name: lang === 'pt' ? 'Serviço A' : 'Service A', mean: 60, stdDev: 20 },
        { name: lang === 'pt' ? 'Serviço B' : 'Service B', mean: 80, stdDev: 25 },
        { name: lang === 'pt' ? 'Serviço C' : 'Service C', mean: 50, stdDev: 15 },
        { name: lang === 'pt' ? 'Banco de dados' : 'Database', mean: 30, stdDev: 10 },
      ],
    },
    {
      key: 'videoStreaming',
      label: l.videoStreaming,
      steps: [
        { name: lang === 'pt' ? 'CDN' : 'CDN', mean: 30, stdDev: 10 },
        { name: lang === 'pt' ? 'Manifesto' : 'Manifest', mean: 80, stdDev: 25 },
        { name: lang === 'pt' ? 'Segmento' : 'Segment', mean: 120, stdDev: 40 },
        { name: lang === 'pt' ? 'Decode' : 'Decode', mean: 20, stdDev: 5 },
        { name: lang === 'pt' ? 'Render' : 'Render', mean: 16, stdDev: 4 },
      ],
    },
    {
      key: 'globalDatabase',
      label: l.globalDatabase,
      steps: [
        { name: lang === 'pt' ? 'Edge' : 'Edge', mean: 20, stdDev: 6 },
        { name: lang === 'pt' ? 'Região A' : 'Region A', mean: 120, stdDev: 40 },
        {
          name: lang === 'pt' ? 'Cross-region' : 'Cross-region',
          mean: 180,
          stdDev: 60,
        },
        {
          name: lang === 'pt' ? 'DB primário' : 'DB primary',
          mean: 45,
          stdDev: 15,
        },
        {
          name: lang === 'pt' ? 'Replicação' : 'Replication',
          mean: 80,
          stdDev: 30,
        },
      ],
    },
  ]
}
